### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.AspNetCore.Hosting.IWebHostEnvironment?alt=Microsoft.AspNetCore.Hosting.IWebHostEnvironment&text=IWebHostEnvironment" data-throw-if-not-resolved="True"/>
  type: property
  uid: AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  commentId: P:AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  name: Environment
  fullName: AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  nameWithType: Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  attributesWithMoniker:
  - value: Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject]

        public Microsoft.AspNetCore.Hosting.IWebHostEnvironment Environment { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject>]

        member this.Environment : Microsoft.AspNetCore.Hosting.IWebHostEnvironment
  - lang: vb
    values:
    - value: Public ReadOnly Property Environment As IWebHostEnvironment
  monikers:
  - msal-model-dotnet-latest
  metadata: {}
uid: AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment*
commentId: Overload:AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
namespace: AspNetCore
name: Environment
fullName: AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
nameWithType: Areas_MicrosoftIdentity_Pages__ViewStart.Environment
assembliesWithMoniker:
- value: Microsoft.Identity.Web.UI.Views.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web.UI v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  - AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.get_Environment
  api_location:
  - Microsoft.Identity.Web.UI.Views.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - AspNetCore.Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  - AspNetCore::Areas_MicrosoftIdentity_Pages__ViewStart::Environment
  - Environment
  - Areas_MicrosoftIdentity_Pages__ViewStart.Environment
  - Areas_MicrosoftIdentity_Pages__ViewStart::Environment
  helpviewer_keywords:
  - Areas_MicrosoftIdentity_Pages__ViewStart.Environment property [.NET]
  - Environment property [.NET], class Areas_MicrosoftIdentity_Pages__ViewStart
  monikers:
  - msal-model-dotnet-latest
