### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  name: UserInfoEndpoint
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  nameWithType: OpenIdConnectConfiguration.UserInfoEndpoint
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="userinfo_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string UserInfoEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="userinfo_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.UserInfoEndpoint : string with get, set
  - lang: vb
    values:
    - value: Public Property UserInfoEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'user_info_endpoint'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: UserInfoEndpoint
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
nameWithType: OpenIdConnectConfiguration.UserInfoEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_UserInfoEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_UserInfoEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::UserInfoEndpoint
  - UserInfoEndpoint
  - OpenIdConnectConfiguration.UserInfoEndpoint
  - OpenIdConnectConfiguration::UserInfoEndpoint
  helpviewer_keywords:
  - OpenIdConnectConfiguration.UserInfoEndpoint property [.NET]
  - UserInfoEndpoint property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
