### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Abstractions.IdentityApplicationOptions?alt=Microsoft.Identity.Abstractions.IdentityApplicationOptions&text=IdentityApplicationOptions" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor
  monikers:
  - msal-model-dotnet-latest
properties:
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.EditProfilePolicyId
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  inheritedFrom: Microsoft.Identity.Abstractions.IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  monikers:
  - msal-model-dotnet-latest
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
commentId: T:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
namespace: Microsoft.Identity.Abstractions
name: MicrosoftIdentityApplicationOptions
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
nameWithType: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class MicrosoftIdentityApplicationOptions : Microsoft.Identity.Abstractions.IdentityApplicationOptions'
- lang: fsharp
  values:
  - value: >-
      type MicrosoftIdentityApplicationOptions = class
          inherit IdentityApplicationOptions
- lang: vb
  values:
  - value: >-
      Public Class MicrosoftIdentityApplicationOptions

      Inherits IdentityApplicationOptions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
summary: Options for configuring authentication using Azure Active Directory. It has both AAD and B2C configuration attributes.
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions
  - MicrosoftIdentityApplicationOptions
  helpviewer_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions class [.NET]
  monikers:
  - msal-model-dotnet-latest
