### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
methods:
- uid: Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions.WithAppTokenProvider(Microsoft.Identity.Client.ConfidentialClientApplicationBuilder,System.Func{Microsoft.Identity.Client.Extensibility.AppTokenProviderParameters,System.Threading.Tasks.Task{Microsoft.Identity.Client.Extensibility.AppTokenProviderResult}})
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
commentId: T:Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
namespace: Microsoft.Identity.Client.Extensibility
name: ConfidentialClientApplicationBuilderExtensions
fullName: Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
nameWithType: Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public static class ConfidentialClientApplicationBuilderExtensions
- lang: fsharp
  values:
  - value: type ConfidentialClientApplicationBuilderExtensions = class
- lang: vb
  values:
  - value: Public Module ConfidentialClientApplicationBuilderExtensions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: Extensibility methods for <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplicationBuilder"></xref>
metadata:
  api_name:
  - Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions
  - Microsoft::Identity::Client::Extensibility::ConfidentialClientApplicationBuilderExtensions
  - ConfidentialClientApplicationBuilderExtensions
  helpviewer_keywords:
  - Microsoft.Identity.Client.Extensibility.ConfidentialClientApplicationBuilderExtensions class [.NET]
  monikers:
  - msal-dotnet-latest
