### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor
  name: ConfigurationValidationResult()
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ConfigurationValidationResult()
  nameWithType: ConfigurationValidationResult.ConfigurationValidationResult()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public ConfigurationValidationResult ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor
namespace: Microsoft.IdentityModel.Protocols
name: ConfigurationValidationResult
fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ConfigurationValidationResult
nameWithType: ConfigurationValidationResult.ConfigurationValidationResult
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor
  - Microsoft::IdentityModel::Protocols::ConfigurationValidationResult::#ctor
  - '#ctor'
  - ConfigurationValidationResult.#ctor
  - ConfigurationValidationResult::#ctor
  helpviewer_keywords:
  - ConfigurationValidationResult class [.NET], constructors
  - ConfigurationValidationResult() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
