### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions
constructors:
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor
  monikers:
  - msal-model-dotnet-latest
properties:
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  monikers:
  - msal-model-dotnet-latest
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions
commentId: T:Microsoft.Identity.Abstractions.IdentityApplicationOptions
namespace: Microsoft.Identity.Abstractions
name: IdentityApplicationOptions
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions
nameWithType: Microsoft.Identity.Abstractions.IdentityApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public class IdentityApplicationOptions
- lang: fsharp
  values:
  - value: type IdentityApplicationOptions = class
- lang: vb
  values:
  - value: Public Class IdentityApplicationOptions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
summary: >-
  Options for configuring authentication in a web app, web API or daemon app.

  <p>

  This class contains configuration properties for any OAuth 2.0 identity provider.

  For Azure AD specific options see the derived class: <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions"></xref>.

  </p>
examples: ""
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions
  - IdentityApplicationOptions
  helpviewer_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions class [.NET]
  monikers:
  - msal-model-dotnet-latest
