### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
methods:
- uid: Microsoft.Identity.Client.PublicClientApplicationExtensions.IsProofOfPossessionSupportedByClient(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.PublicClientApplicationExtensions
commentId: T:Microsoft.Identity.Client.PublicClientApplicationExtensions
namespace: Microsoft.Identity.Client
name: PublicClientApplicationExtensions
fullName: Microsoft.Identity.Client.PublicClientApplicationExtensions
nameWithType: Microsoft.Identity.Client.PublicClientApplicationExtensions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public static class PublicClientApplicationExtensions
- lang: fsharp
  values:
  - value: type PublicClientApplicationExtensions = class
- lang: vb
  values:
  - value: Public Module PublicClientApplicationExtensions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: Extensibility methods for <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IPublicClientApplication"></xref>
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationExtensions
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationExtensions
  - Microsoft::Identity::Client::PublicClientApplicationExtensions
  - PublicClientApplicationExtensions
  helpviewer_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationExtensions class [.NET]
  monikers:
  - msal-dotnet-latest
