### YamlMime:NetNamespace
classes:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
commentId: N:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
name: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
devLangs:
- csharp
monikers:
- msal-web-dotnet-latest
metadata:
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::Configuration
  - Configuration
  - OpenIdConnect.Configuration
  - OpenIdConnect::Configuration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration namespace [.NET]
  monikers:
  - msal-web-dotnet-latest
