### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder&text=MicrosoftIdentityAppCallsWebApiAuthenticationBuilder" data-throw-if-not-resolved="True"/>
    description: The authentication builder to chain.
  type: method
  uid: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  commentId: M:Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  name: EnableTokenAcquisitionToCallDownstreamApi()
  fullName: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi()
  nameWithType: MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder EnableTokenAcquisitionToCallDownstreamApi ();
  - lang: fsharp
    values:
    - value: 'override this.EnableTokenAcquisitionToCallDownstreamApi : unit -> Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder'
  - lang: vb
    values:
    - value: Public Function EnableTokenAcquisitionToCallDownstreamApi () As MicrosoftIdentityAppCallsWebApiAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Protects the web API with Microsoft identity platform (formerly Azure AD v2.0).

    This method expects the configuration file will have a section, named "AzureAd" as default, with the necessary settings to initialize authentication options.
  metadata: {}
uid: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi*
commentId: Overload:Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
namespace: Microsoft.Identity.Web
name: EnableTokenAcquisitionToCallDownstreamApi
fullName: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
nameWithType: MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  - Microsoft::Identity::Web::MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration::EnableTokenAcquisitionToCallDownstreamApi
  - EnableTokenAcquisitionToCallDownstreamApi
  - MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  - MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration::EnableTokenAcquisitionToCallDownstreamApi
  helpviewer_keywords:
  - MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi method [.NET]
  - EnableTokenAcquisitionToCallDownstreamApi method [.NET], class MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  - MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi() method [.NET]
  - EnableTokenAcquisitionToCallDownstreamApi() method [.NET], class MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  monikers:
  - msal-model-dotnet-latest
