### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.Identity.Client.IByRefreshToken?alt=Microsoft.Identity.Client.IByRefreshToken&text=IByRefreshToken" data-throw-if-not-resolved="True"/>
- value: <xref href="Microsoft.Identity.Client.IClientApplicationBase?alt=Microsoft.Identity.Client.IClientApplicationBase&text=IClientApplicationBase" data-throw-if-not-resolved="True"/>
- value: <xref href="Microsoft.Identity.Client.IPublicClientApplication?alt=Microsoft.Identity.Client.IPublicClientApplication&text=IPublicClientApplication" data-throw-if-not-resolved="True"/>
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Client.ClientApplicationBase?alt=Microsoft.Identity.Client.ClientApplicationBase&text=ClientApplicationBase" data-throw-if-not-resolved="True"/>
extensionMethods:
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsEmbeddedWebViewAvailable(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsSystemWebViewAvailable(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsUserInteractive(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationExtensions.IsProofOfPossessionSupportedByClient(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
constructors:
- uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String,Microsoft.Identity.Client.TokenCache)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String)
  monikers:
  - msal-dotnet-latest
methods:
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByIntegratedWindowsAuth(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByIntegratedWindowsAuthAsync(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByIntegratedWindowsAuthAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByUsernamePassword(System.Collections.Generic.IEnumerable{System.String},System.String,System.Security.SecureString)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByUsernamePassword(System.Collections.Generic.IEnumerable{System.String},System.String,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenByUsernamePasswordAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Security.SecureString)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenInteractive(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenWithDeviceCode(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task},System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task},System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountAsync(System.String,System.Threading.CancellationToken)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.Threading.CancellationToken)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String,System.Threading.CancellationToken)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetUser(System.String)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.IsBrokerAvailable
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.IsUserInteractive
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Remove(Microsoft.Identity.Client.IUser)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount,System.Threading.CancellationToken)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
eiis:
- uid: Microsoft.Identity.Client.PublicClientApplication.Microsoft#Identity#Client#IByRefreshToken#AcquireTokenByRefreshToken(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.Microsoft#Identity#Client#IByRefreshToken#AcquireTokenByRefreshTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.ClientApplicationBase.AppConfig
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Authority
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.ClientId
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Component
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.IsSystemWebViewAvailable
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RedirectUri
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.SliceParameters
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Users
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.UserTokenCache
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.ValidateAuthority
  inheritedFrom: Microsoft.Identity.Client.ClientApplicationBase
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.PublicClientApplication
commentId: T:Microsoft.Identity.Client.PublicClientApplication
namespace: Microsoft.Identity.Client
name: PublicClientApplication
fullName: Microsoft.Identity.Client.PublicClientApplication
nameWithType: Microsoft.Identity.Client.PublicClientApplication
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public sealed class PublicClientApplication : Microsoft.Identity.Client.ClientApplicationBase, Microsoft.Identity.Client.IByRefreshToken, Microsoft.Identity.Client.IPublicClientApplication'
- lang: fsharp
  values:
  - value: >-
      type PublicClientApplication = class
          inherit ClientApplicationBase
          interface IPublicClientApplication
          interface IClientApplicationBase
          interface IByRefreshToken
- lang: vb
  values:
  - value: >-
      Public NotInheritable Class PublicClientApplication

      Inherits ClientApplicationBase

      Implements IByRefreshToken, IPublicClientApplication
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Abstract class containing common API methods and properties.

  For details see https://aka.ms/msal-net-client-applications
remarks: <p><ul><li>Contrary to <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplication"></xref>, public clients are unable to hold configuration time secrets, and as a result have no client secret</li><li>The redirect URL is proposed by the library. It does not need to be passed in the constructor</li></ul></p>
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplication
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplication
  - Microsoft::Identity::Client::PublicClientApplication
  - PublicClientApplication
  helpviewer_keywords:
  - Microsoft.Identity.Client.PublicClientApplication class [.NET]
  monikers:
  - msal-dotnet-latest
