### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  commentId: F:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  name: MinimumAutomaticRefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  nameWithType: BaseConfigurationManager.MinimumAutomaticRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan MinimumAutomaticRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable MinimumAutomaticRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly MinimumAutomaticRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 5 minutes is the minimum value for automatic refresh. <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval"></xref> can not be set less than this value.
  metadata: {}
namespace: Microsoft.IdentityModel.Tokens
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::MinimumAutomaticRefreshInterval
  - MinimumAutomaticRefreshInterval
  - BaseConfigurationManager.MinimumAutomaticRefreshInterval
  - BaseConfigurationManager::MinimumAutomaticRefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.MinimumAutomaticRefreshInterval field [.NET]
  - MinimumAutomaticRefreshInterval field [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
