### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration?alt=Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration&text=IssuerValidatorUsingConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
  name: IssuerValidatorUsingConfiguration
  fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
  nameWithType: TokenValidationParameters.IssuerValidatorUsingConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration IssuerValidatorUsingConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.IssuerValidatorUsingConfiguration : Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property IssuerValidatorUsingConfiguration As IssuerValidatorUsingConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets a delegate that will be used to validate the issuer of the token.
  remarks: <p>If set, this delegate will be called to validate the 'issuer' of the token, instead of default processing. This means that no default 'issuer' validation will occur. Even if <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.ValidateIssuer"></xref> is false, this delegate will still be called. This delegate should be used if properties from the configuration retrieved from the authority are necessary to validate the issuer. If both <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidator"></xref> are set, IssuerValidatorUsingConfiguration takes priority.</p>
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: IssuerValidatorUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
nameWithType: TokenValidationParameters.IssuerValidatorUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.get_IssuerValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.set_IssuerValidatorUsingConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerValidatorUsingConfiguration
  - Microsoft::IdentityModel::Tokens::TokenValidationParameters::IssuerValidatorUsingConfiguration
  - IssuerValidatorUsingConfiguration
  - TokenValidationParameters.IssuerValidatorUsingConfiguration
  - TokenValidationParameters::IssuerValidatorUsingConfiguration
  helpviewer_keywords:
  - TokenValidationParameters.IssuerValidatorUsingConfiguration property [.NET]
  - IssuerValidatorUsingConfiguration property [.NET], class TokenValidationParameters
  monikers:
  - msal-web-dotnet-latest
