### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  name: Authority
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  nameWithType: MicrosoftIdentityApplicationOptions.Authority
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public override string? Authority { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Authority : string with get, set'
  - lang: vb
    values:
    - value: Public Overrides Property Authority As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the Authority to use when making OpenIdConnect calls.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
namespace: Microsoft.Identity.Abstractions
name: Authority
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
nameWithType: MicrosoftIdentityApplicationOptions.Authority
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_Authority
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_Authority
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Authority
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::Authority
  - Authority
  - MicrosoftIdentityApplicationOptions.Authority
  - MicrosoftIdentityApplicationOptions::Authority
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.Authority property [.NET]
  - Authority property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
