### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: Configuration of type T.
  parameters:
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  name: GetBaseConfigurationAsync(CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.GetBaseConfigurationAsync(CancellationToken)
  nameWithType: StaticConfigurationManager<T>.GetBaseConfigurationAsync(CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public override System.Threading.Tasks.Task<Microsoft.IdentityModel.Tokens.BaseConfiguration> GetBaseConfigurationAsync (System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'override this.GetBaseConfigurationAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Tokens.BaseConfiguration>'
  - lang: vb
    values:
    - value: Public Overrides Function GetBaseConfigurationAsync (cancel As CancellationToken) As Task(Of BaseConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Obtains an updated version of Configuration.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync*
commentId: Overload:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync
namespace: Microsoft.IdentityModel.Protocols
name: GetBaseConfigurationAsync
fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.GetBaseConfigurationAsync
nameWithType: StaticConfigurationManager<T>.GetBaseConfigurationAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetBaseConfigurationAsync
  - Microsoft::IdentityModel::Protocols::StaticConfigurationManager`1::GetBaseConfigurationAsync
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager.GetBaseConfigurationAsync
  - GetBaseConfigurationAsync
  - StaticConfigurationManager`1.GetBaseConfigurationAsync
  - StaticConfigurationManager`1::GetBaseConfigurationAsync
  helpviewer_keywords:
  - StaticConfigurationManager<T>.GetBaseConfigurationAsync method [.NET]
  - GetBaseConfigurationAsync method [.NET], class StaticConfigurationManager<T>
  - StaticConfigurationManager<T>.GetBaseConfigurationAsync(CancellationToken) method [.NET]
  - GetBaseConfigurationAsync(CancellationToken) method [.NET], class StaticConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
