### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.PublicClientApplicationBuilder?alt=Microsoft.Identity.Client.PublicClientApplicationBuilder&text=PublicClientApplicationBuilder" data-throw-if-not-resolved="True"/>
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: servicePrincipalName
    description: Service principal name to get Kerberos Service Ticket.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: ticketContainer
    description: Container to use for Kerberos Ticket.
    type: <xref href="Microsoft.Identity.Client.Kerberos.KerberosTicketContainer?alt=Microsoft.Identity.Client.Kerberos.KerberosTicketContainer&text=KerberosTicketContainer" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim(System.String,Microsoft.Identity.Client.Kerberos.KerberosTicketContainer)
  commentId: M:Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim(System.String,Microsoft.Identity.Client.Kerberos.KerberosTicketContainer)
  name: WithKerberosTicketClaim(String, KerberosTicketContainer)
  fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim(String, KerberosTicketContainer)
  nameWithType: PublicClientApplicationBuilder.WithKerberosTicketClaim(String, KerberosTicketContainer)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.PublicClientApplicationBuilder WithKerberosTicketClaim (string servicePrincipalName, Microsoft.Identity.Client.Kerberos.KerberosTicketContainer ticketContainer);
  - lang: fsharp
    values:
    - value: 'member this.WithKerberosTicketClaim : string * Microsoft.Identity.Client.Kerberos.KerberosTicketContainer -> Microsoft.Identity.Client.PublicClientApplicationBuilder'
  - lang: vb
    values:
    - value: Public Function WithKerberosTicketClaim (servicePrincipalName As String, ticketContainer As KerberosTicketContainer) As PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: Sets the parameters required to get a Kerberos Ticket from Azure AD service.
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim
namespace: Microsoft.Identity.Client
name: WithKerberosTicketClaim
fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim
nameWithType: PublicClientApplicationBuilder.WithKerberosTicketClaim
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim
  - Microsoft::Identity::Client::PublicClientApplicationBuilder::WithKerberosTicketClaim
  - WithKerberosTicketClaim
  - PublicClientApplicationBuilder.WithKerberosTicketClaim
  - PublicClientApplicationBuilder::WithKerberosTicketClaim
  helpviewer_keywords:
  - PublicClientApplicationBuilder.WithKerberosTicketClaim method [.NET]
  - WithKerberosTicketClaim method [.NET], class PublicClientApplicationBuilder
  - PublicClientApplicationBuilder.WithKerberosTicketClaim(String, KerberosTicketContainer) method [.NET]
  - WithKerberosTicketClaim(String, KerberosTicketContainer) method [.NET], class PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
