### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.Kerberos.KerberosTicketContainer?alt=Microsoft.Identity.Client.Kerberos.KerberosTicketContainer&text=KerberosTicketContainer" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  name: TicketContainer
  fullName: Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  nameWithType: ApplicationOptions.TicketContainer
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.Kerberos.KerberosTicketContainer TicketContainer { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.TicketContainer : Microsoft.Identity.Client.Kerberos.KerberosTicketContainer with get, set'
  - lang: vb
    values:
    - value: Public Property TicketContainer As KerberosTicketContainer
  monikers:
  - msal-dotnet-latest
  summary: Kerberos Service Ticket container to be used.
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.TicketContainer*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.TicketContainer
namespace: Microsoft.Identity.Client
name: TicketContainer
fullName: Microsoft.Identity.Client.ApplicationOptions.TicketContainer
nameWithType: ApplicationOptions.TicketContainer
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  - Microsoft.Identity.Client.ApplicationOptions.get_TicketContainer
  - Microsoft.Identity.Client.ApplicationOptions.set_TicketContainer
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  - Microsoft::Identity::Client::ApplicationOptions::TicketContainer
  - TicketContainer
  - ApplicationOptions.TicketContainer
  - ApplicationOptions::TicketContainer
  helpviewer_keywords:
  - ApplicationOptions.TicketContainer property [.NET]
  - TicketContainer property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
