### YamlMime:NetMember
type: method
members:
- type: method
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
  commentId: M:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
  name: RequestRefresh()
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh()
  nameWithType: BaseConfigurationManager.RequestRefresh()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public abstract void RequestRefresh ();
  - lang: fsharp
    values:
    - value: 'abstract member RequestRefresh : unit -> unit'
  - lang: vb
    values:
    - value: Public MustOverride Sub RequestRefresh ()
  monikers:
  - msal-web-dotnet-latest
  summary: Indicate that the configuration may be stale (as indicated by failing to process incoming tokens).
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
namespace: Microsoft.IdentityModel.Tokens
name: RequestRefresh
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
nameWithType: BaseConfigurationManager.RequestRefresh
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::RequestRefresh
  - RequestRefresh
  - BaseConfigurationManager.RequestRefresh
  - BaseConfigurationManager::RequestRefresh
  helpviewer_keywords:
  - BaseConfigurationManager.RequestRefresh method [.NET]
  - RequestRefresh method [.NET], class BaseConfigurationManager
  - BaseConfigurationManager.RequestRefresh() method [.NET]
  - RequestRefresh() method [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
