### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  name: ResetPasswordPolicyId
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  nameWithType: MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? ResetPasswordPolicyId { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ResetPasswordPolicyId : string with get, set'
  - lang: vb
    values:
    - value: Public Property ResetPasswordPolicyId As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the reset password user flow name for B2C, e.g. B2C_1_password_reset.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
namespace: Microsoft.Identity.Abstractions
name: ResetPasswordPolicyId
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
nameWithType: MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_ResetPasswordPolicyId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_ResetPasswordPolicyId
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::ResetPasswordPolicyId
  - ResetPasswordPolicyId
  - MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId
  - MicrosoftIdentityApplicationOptions::ResetPasswordPolicyId
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.ResetPasswordPolicyId property [.NET]
  - ResetPasswordPolicyId property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
