### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  name: SendX5C
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  nameWithType: MicrosoftIdentityApplicationOptions.SendX5C
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool SendX5C { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.SendX5C : bool with get, set'
  - lang: vb
    values:
    - value: Public Property SendX5C As Boolean
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Specifies if the x5c claim (public key of the certificate) should be sent to the STS.

    Sending the x5c enables application developers to achieve easy certificate rollover in Azure AD:

    this method will send the public certificate to Azure AD along with the token request,

    so that Azure AD can use it to validate the subject name based on a trusted issuer policy.

    This saves the application admin from the need to explicitly manage the certificate rollover

    (either via the app registration portal or using PowerShell/CLI). 

    For details see https://aka.ms/msal-net-sni.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
namespace: Microsoft.Identity.Abstractions
name: SendX5C
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
nameWithType: MicrosoftIdentityApplicationOptions.SendX5C
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_SendX5C
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_SendX5C
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SendX5C
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::SendX5C
  - SendX5C
  - MicrosoftIdentityApplicationOptions.SendX5C
  - MicrosoftIdentityApplicationOptions::SendX5C
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.SendX5C property [.NET]
  - SendX5C property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
