### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ConfidentialClientApplicationBuilder?alt=Microsoft.Identity.Client.ConfidentialClientApplicationBuilder&text=ConfidentialClientApplicationBuilder" data-throw-if-not-resolved="True"/>
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: azureRegion
    description: >-
      Either the string with the region (preferred) or        
                  use <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplication.AttemptRegionDiscovery"></xref> and MSAL.NET will attempt to auto-detect the region.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion(System.String)
  commentId: M:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion(System.String)
  name: WithAzureRegion(String)
  fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion(String)
  nameWithType: ConfidentialClientApplicationBuilder.WithAzureRegion(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.ConfidentialClientApplicationBuilder WithAzureRegion (string azureRegion = "TryAutoDetect");
  - lang: fsharp
    values:
    - value: 'member this.WithAzureRegion : string -> Microsoft.Identity.Client.ConfidentialClientApplicationBuilder'
  - lang: vb
    values:
    - value: Public Function WithAzureRegion (Optional azureRegion As String = "TryAutoDetect") As ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: Instructs MSAL.NET to use an Azure regional token service.
  remarks: <p>Region names as per https://azure.microsoft.com/en-ca/global-infrastructure/geographies/. See https://aka.ms/region-map for more details on region names. The region value should be short region name for the region where the service is deployed. For example "centralus" is short name for region Central US. Not all auth flows can use the regional token service. Service To Service (client credential flow) tokens can be obtained from the regional service. Requires configuration at the tenant level. Auto-detection works on a limited number of Azure artifacts (VMs, Azure functions). If auto-detection fails, the non-regional endpoint will be used. If an invalid region name is provided, the non-regional endpoint MIGHT be used or the token request MIGHT fail. See https://aka.ms/msal-net-region-discovery for more details.</p>
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion
namespace: Microsoft.Identity.Client
name: WithAzureRegion
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion
nameWithType: ConfidentialClientApplicationBuilder.WithAzureRegion
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithAzureRegion
  - Microsoft::Identity::Client::ConfidentialClientApplicationBuilder::WithAzureRegion
  - WithAzureRegion
  - ConfidentialClientApplicationBuilder.WithAzureRegion
  - ConfidentialClientApplicationBuilder::WithAzureRegion
  helpviewer_keywords:
  - ConfidentialClientApplicationBuilder.WithAzureRegion method [.NET]
  - WithAzureRegion method [.NET], class ConfidentialClientApplicationBuilder
  - ConfidentialClientApplicationBuilder.WithAzureRegion(String) method [.NET]
  - WithAzureRegion(String) method [.NET], class ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
