### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.ConfigurationManager`1
- value: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1
constructors:
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  monikers:
  - msal-web-dotnet-latest
fields:
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumAutomaticRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
commentId: T:Microsoft.IdentityModel.Tokens.BaseConfigurationManager
namespace: Microsoft.IdentityModel.Tokens
name: BaseConfigurationManager
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
nameWithType: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public abstract class BaseConfigurationManager
- lang: fsharp
  values:
  - value: type BaseConfigurationManager = class
- lang: vb
  values:
  - value: Public MustInherit Class BaseConfigurationManager
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Represents a generic configuration manager.
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager
  - BaseConfigurationManager
  helpviewer_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager class [.NET]
  monikers:
  - msal-web-dotnet-latest
