### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  commentId: P:Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  name: EnablePiiLogging
  fullName: Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  nameWithType: IAppConfig.EnablePiiLogging
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool EnablePiiLogging { get; }
  - lang: fsharp
    values:
    - value: 'member this.EnablePiiLogging : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property EnablePiiLogging As Boolean
  monikers:
  - msal-dotnet-latest
  seeAlso: >+
    - <xref:Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled>

  summary: >-
    Flag telling if logging of Personally Identifiable Information (PII) is enabled/disabled for

    the application. See https://aka.ms/msal-net-logging.
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.EnablePiiLogging*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
namespace: Microsoft.Identity.Client
name: EnablePiiLogging
fullName: Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
nameWithType: IAppConfig.EnablePiiLogging
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  - Microsoft.Identity.Client.IAppConfig.get_EnablePiiLogging
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  - Microsoft::Identity::Client::IAppConfig::EnablePiiLogging
  - EnablePiiLogging
  - IAppConfig.EnablePiiLogging
  - IAppConfig::EnablePiiLogging
  helpviewer_keywords:
  - IAppConfig.EnablePiiLogging property [.NET]
  - EnablePiiLogging property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
