### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
  commentId: M:Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
  name: IsEmbeddedWebViewAvailable()
  fullName: Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable()
  nameWithType: PublicClientApplication.IsEmbeddedWebViewAvailable()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsEmbeddedWebViewAvailable ();
  - lang: fsharp
    values:
    - value: 'member this.IsEmbeddedWebViewAvailable : unit -> bool'
  - lang: vb
    values:
    - value: Public Function IsEmbeddedWebViewAvailable () As Boolean
  monikers:
  - msal-dotnet-latest
  summary: Returns true if MSAL can use an embedded web view (browser).
  remarks: <p>Currently there are no embedded web views on Mac and Linux. On Windows, app developers or users should install the WebView2 runtime and this property will inform if the runtime is available, see https://aka.ms/msal-net-webview2</p>
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
namespace: Microsoft.Identity.Client
name: IsEmbeddedWebViewAvailable
fullName: Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
nameWithType: PublicClientApplication.IsEmbeddedWebViewAvailable
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplication.IsEmbeddedWebViewAvailable
  - Microsoft::Identity::Client::PublicClientApplication::IsEmbeddedWebViewAvailable
  - IsEmbeddedWebViewAvailable
  - PublicClientApplication.IsEmbeddedWebViewAvailable
  - PublicClientApplication::IsEmbeddedWebViewAvailable
  helpviewer_keywords:
  - PublicClientApplication.IsEmbeddedWebViewAvailable method [.NET]
  - IsEmbeddedWebViewAvailable method [.NET], class PublicClientApplication
  - PublicClientApplication.IsEmbeddedWebViewAvailable() method [.NET]
  - IsEmbeddedWebViewAvailable() method [.NET], class PublicClientApplication
  monikers:
  - msal-dotnet-latest
