### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  commentId: P:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  name: Succeeded
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  nameWithType: ConfigurationValidationResult.Succeeded
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool Succeeded { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Succeeded : bool with get, set'
  - lang: vb
    values:
    - value: Public Property Succeeded As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets a bool indicating if the configuration validation was successful.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded*
commentId: Overload:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
namespace: Microsoft.IdentityModel.Protocols
name: Succeeded
fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
nameWithType: ConfigurationValidationResult.Succeeded
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.get_Succeeded
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.set_Succeeded
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  - Microsoft::IdentityModel::Protocols::ConfigurationValidationResult::Succeeded
  - Succeeded
  - ConfigurationValidationResult.Succeeded
  - ConfigurationValidationResult::Succeeded
  helpviewer_keywords:
  - ConfigurationValidationResult.Succeeded property [.NET]
  - Succeeded property [.NET], class ConfigurationValidationResult
  monikers:
  - msal-web-dotnet-latest
