### YamlMime:NetType
typeParameters:
- name: T
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder
- value: Microsoft.Identity.Client.PublicClientApplicationBuilder
methods:
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAdfsAuthority(System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AadAuthorityAudience,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,Microsoft.Identity.Client.AadAuthorityAudience,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,System.Guid,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.Guid,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.Uri,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithB2CAuthority(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithCacheOptions(Microsoft.Identity.Client.CacheOptions)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientCapabilities(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientId(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientVersion(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithDebugLoggingCallback(Microsoft.Identity.Client.LogLevel,System.Boolean,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExperimentalFeatures(System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExtraQueryParameters(System.Collections.Generic.IDictionary{System.String,System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExtraQueryParameters(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDicoveryMetadata(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDicoveryMetadata(System.Uri)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscovery(System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.Uri)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLegacyCacheCompatibility(System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLogging(Microsoft.Identity.Client.LogCallback,System.Nullable{Microsoft.Identity.Client.LogLevel},System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithOptions(Microsoft.Identity.Client.ApplicationOptions)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithRedirectUri(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithTelemetry(Microsoft.Identity.Client.ITelemetryConfig)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithTenantId(System.String)
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1
commentId: T:Microsoft.Identity.Client.AbstractApplicationBuilder`1
namespace: Microsoft.Identity.Client
name: AbstractApplicationBuilder<T>
fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>
nameWithType: Microsoft.Identity.Client.AbstractApplicationBuilder<T>
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public abstract class AbstractApplicationBuilder<T> where T : AbstractApplicationBuilder<T>'
- lang: fsharp
  values:
  - value: type AbstractApplicationBuilder<'T (requires 'T :> AbstractApplicationBuilder<'T>)> = class
- lang: vb
  values:
  - value: Public MustInherit Class AbstractApplicationBuilder(Of T)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1
  - Microsoft::Identity::Client::AbstractApplicationBuilder`1
  - Microsoft.Identity.Client.AbstractApplicationBuilder
  - AbstractApplicationBuilder`1
  helpviewer_keywords:
  - Microsoft.Identity.Client.AbstractApplicationBuilder<T> class [.NET]
  monikers:
  - msal-dotnet-latest
