### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
- value: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
constructors:
- uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.Issuer
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Tokens.BaseConfiguration
commentId: T:Microsoft.IdentityModel.Tokens.BaseConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: BaseConfiguration
fullName: Microsoft.IdentityModel.Tokens.BaseConfiguration
nameWithType: Microsoft.IdentityModel.Tokens.BaseConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public abstract class BaseConfiguration
- lang: fsharp
  values:
  - value: type BaseConfiguration = class
- lang: vb
  values:
  - value: Public MustInherit Class BaseConfiguration
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Represents a generic metadata configuration which is applicable for both XML and JSON based configurations.
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration
  - Microsoft::IdentityModel::Tokens::BaseConfiguration
  - BaseConfiguration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration class [.NET]
  monikers:
  - msal-web-dotnet-latest
