### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ConfidentialClientApplicationBuilder?alt=Microsoft.Identity.Client.ConfidentialClientApplicationBuilder&text=ConfidentialClientApplicationBuilder" data-throw-if-not-resolved="True"/>
    description: >-
      A <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplicationBuilder"></xref> from which to set more
                  parameters, and to create a confidential client application instance
  parameters:
  - namesWithMoniker:
    - value: clientId
    description: >-
      Client ID (also known as App ID) of the application as registered in the
                  application registration portal (https://aka.ms/msal-net-register-app)/.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create(System.String)
  commentId: M:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create(System.String)
  name: Create(String)
  fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create(String)
  nameWithType: ConfidentialClientApplicationBuilder.Create(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.Identity.Client.ConfidentialClientApplicationBuilder Create (string clientId);
  - lang: fsharp
    values:
    - value: 'static member Create : string -> Microsoft.Identity.Client.ConfidentialClientApplicationBuilder'
  - lang: vb
    values:
    - value: Public Shared Function Create (clientId As String) As ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: >-
    Creates a ConfidentialClientApplicationBuilder from a clientID.

    See https://aka.ms/msal-net-application-configuration
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create
namespace: Microsoft.Identity.Client
name: Create
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create
nameWithType: ConfidentialClientApplicationBuilder.Create
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Create
  - Microsoft::Identity::Client::ConfidentialClientApplicationBuilder::Create
  - Create
  - ConfidentialClientApplicationBuilder.Create
  - ConfidentialClientApplicationBuilder::Create
  helpviewer_keywords:
  - ConfidentialClientApplicationBuilder.Create method [.NET]
  - Create method [.NET], class ConfidentialClientApplicationBuilder
  - ConfidentialClientApplicationBuilder.Create(String) method [.NET]
  - Create(String) method [.NET], class ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
