### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  name: TokenEndpoint
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  nameWithType: WsFederationConfiguration.TokenEndpoint
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string TokenEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.TokenEndpoint : string with get, set'
  - lang: vb
    values:
    - value: Public Property TokenEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets token endpoint.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: TokenEndpoint
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
nameWithType: WsFederationConfiguration.TokenEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.get_TokenEndpoint
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.set_TokenEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration::TokenEndpoint
  - TokenEndpoint
  - WsFederationConfiguration.TokenEndpoint
  - WsFederationConfiguration::TokenEndpoint
  helpviewer_keywords:
  - WsFederationConfiguration.TokenEndpoint property [.NET]
  - TokenEndpoint property [.NET], class WsFederationConfiguration
  monikers:
  - msal-web-dotnet-latest
