### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration?alt=Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration&text=IssuerSigningKeyResolverUsingConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  name: IssuerSigningKeyResolverUsingConfiguration
  fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  nameWithType: TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration IssuerSigningKeyResolverUsingConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.IssuerSigningKeyResolverUsingConfiguration : Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property IssuerSigningKeyResolverUsingConfiguration As IssuerSigningKeyResolverUsingConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets or sets a delegate that will be called to retrieve a <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> used for signature validation using the

    <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration"></xref>.
  remarks: <p>This <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> will be used to check the signature. This can be helpful when the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityToken"></xref> does not contain a key identifier. This delegate should be used if properties from the configuration retrieved from the authority are necessary to resolve the issuer signing key. If both <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolver"></xref> are set, IssuerSigningKeyResolverUsingConfiguration takes priority.</p>
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: IssuerSigningKeyResolverUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
nameWithType: TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.get_IssuerSigningKeyResolverUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.set_IssuerSigningKeyResolverUsingConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  - Microsoft::IdentityModel::Tokens::TokenValidationParameters::IssuerSigningKeyResolverUsingConfiguration
  - IssuerSigningKeyResolverUsingConfiguration
  - TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration
  - TokenValidationParameters::IssuerSigningKeyResolverUsingConfiguration
  helpviewer_keywords:
  - TokenValidationParameters.IssuerSigningKeyResolverUsingConfiguration property [.NET]
  - IssuerSigningKeyResolverUsingConfiguration property [.NET], class TokenValidationParameters
  monikers:
  - msal-web-dotnet-latest
