### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  name: TenantId
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  nameWithType: MicrosoftIdentityApplicationOptions.TenantId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? TenantId { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.TenantId : string with get, set'
  - lang: vb
    values:
    - value: Public Property TenantId As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the tenant ID.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
namespace: Microsoft.Identity.Abstractions
name: TenantId
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
nameWithType: MicrosoftIdentityApplicationOptions.TenantId
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_TenantId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_TenantId
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::TenantId
  - TenantId
  - MicrosoftIdentityApplicationOptions.TenantId
  - MicrosoftIdentityApplicationOptions::TenantId
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.TenantId property [.NET]
  - TenantId property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
