### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  name: LastKnownGoodConfiguration
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  nameWithType: BaseConfigurationManager.LastKnownGoodConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.BaseConfiguration LastKnownGoodConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.LastKnownGoodConfiguration : Microsoft.IdentityModel.Tokens.BaseConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property LastKnownGoodConfiguration As BaseConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: The last known good configuration or LKG (a configuration retrieved in the past that we were able to successfully validate a token against).
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: LastKnownGoodConfiguration
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
nameWithType: BaseConfigurationManager.LastKnownGoodConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_LastKnownGoodConfiguration
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_LastKnownGoodConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::LastKnownGoodConfiguration
  - LastKnownGoodConfiguration
  - BaseConfigurationManager.LastKnownGoodConfiguration
  - BaseConfigurationManager::LastKnownGoodConfiguration
  helpviewer_keywords:
  - BaseConfigurationManager.LastKnownGoodConfiguration property [.NET]
  - LastKnownGoodConfiguration property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
