### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  commentId: P:Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  name: RequiredScopesConfigurationKey
  fullName: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  nameWithType: RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredScopesConfigurationKey { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredScopesConfigurationKey : string with get, set'
  - lang: vb
    values:
    - value: Public Property RequiredScopesConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Fully qualified name of the configuration key containing the required scopes (separated

    by spaces).
  examples: >-
    If the appsettings.json file contains a section named "AzureAd", in which

    a property named "Scopes" contains the required scopes, the attribute on the

    controller/page/action to protect should be set to the following:


    ```

    [RequiredScopeOrAppPermission(RequiredScopesConfigurationKey="AzureAd:Scopes")]

    ```
  metadata: {}
uid: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
namespace: Microsoft.Identity.Web.Resource
name: RequiredScopesConfigurationKey
fullName: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
nameWithType: RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.get_RequiredScopesConfigurationKey
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.set_RequiredScopesConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  - Microsoft::Identity::Web::Resource::RequiredScopeOrAppPermissionAttribute::RequiredScopesConfigurationKey
  - RequiredScopesConfigurationKey
  - RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey
  - RequiredScopeOrAppPermissionAttribute::RequiredScopesConfigurationKey
  helpviewer_keywords:
  - RequiredScopeOrAppPermissionAttribute.RequiredScopesConfigurationKey property [.NET]
  - RequiredScopesConfigurationKey property [.NET], class RequiredScopeOrAppPermissionAttribute
  monikers:
  - msal-model-dotnet-latest
