### YamlMime:NetMember
type: constructor
members:
- parameters:
  - namesWithMoniker:
    - value: configuration
    description: Configuration of type OpenIdConnectConfiguration or OpenIdConnectConfiguration.
    type: T
  type: constructor
  uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.#ctor(`0)
  commentId: M:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.#ctor(`0)
  name: StaticConfigurationManager<T>(T)
  fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.StaticConfigurationManager<T>(T)
  nameWithType: StaticConfigurationManager<T>.StaticConfigurationManager<T>(T)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public StaticConfigurationManager (T configuration);
  - lang: fsharp
    values:
    - value: "new Microsoft.IdentityModel.Protocols.StaticConfigurationManager<'T (requires 'T : null)> : 'T -> Microsoft.IdentityModel.Protocols.StaticConfigurationManager<'T (requires 'T : null)>"
  - lang: vb
    values:
    - value: Public Sub New (configuration As T)
  monikers:
  - msal-web-dotnet-latest
  summary: Initializes an new instance of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1"></xref> with a Configuration instance.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.#ctor
namespace: Microsoft.IdentityModel.Protocols
name: StaticConfigurationManager<T>
fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.StaticConfigurationManager
nameWithType: StaticConfigurationManager<T>.StaticConfigurationManager<T>
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.#ctor
  - Microsoft::IdentityModel::Protocols::StaticConfigurationManager`1::#ctor
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager.#ctor
  - '#ctor'
  - StaticConfigurationManager`1.#ctor
  - StaticConfigurationManager`1::#ctor
  helpviewer_keywords:
  - StaticConfigurationManager<T> class [.NET], constructors
  - StaticConfigurationManager<T>(T) class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
