### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.AuthenticationResult?alt=Microsoft.Identity.Client.AuthenticationResult&text=AuthenticationResult" data-throw-if-not-resolved="True"/>&gt;
    description: Authentication result containing token of the user for the requested scopes
  parameters:
  - namesWithMoniker:
    - value: scopes
    description: Array of scopes requested for resource
    type: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  - namesWithMoniker:
    - value: userAssertion
    description: Instance of UserAssertion containing user's token.
    type: <xref href="Microsoft.Identity.Client.UserAssertion?alt=Microsoft.Identity.Client.UserAssertion&text=UserAssertion" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion)
  commentId: M:Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion)
  name: AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion)
  fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion)
  nameWithType: IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public System.Threading.Tasks.Task<Microsoft.Identity.Client.AuthenticationResult> AcquireTokenOnBehalfOfAsync (System.Collections.Generic.IEnumerable<string> scopes, Microsoft.Identity.Client.UserAssertion userAssertion);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        abstract member AcquireTokenOnBehalfOfAsync : seq<string> * Microsoft.Identity.Client.UserAssertion -> System.Threading.Tasks.Task<Microsoft.Identity.Client.AuthenticationResult>
  - lang: vb
    values:
    - value: Public Function AcquireTokenOnBehalfOfAsync (scopes As IEnumerable(Of String), userAssertion As UserAssertion) As Task(Of AuthenticationResult)
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. '
  summary: '[V3 API] Acquires token using On-Behalf-Of flow. (See https://aka.ms/msal-net-on-behalf-of)'
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.AuthenticationResult?alt=Microsoft.Identity.Client.AuthenticationResult&text=AuthenticationResult" data-throw-if-not-resolved="True"/>&gt;
    description: Authentication result containing token of the user for the requested scopes
  parameters:
  - namesWithMoniker:
    - value: scopes
    description: Array of scopes requested for resource
    type: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  - namesWithMoniker:
    - value: userAssertion
    description: Instance of UserAssertion containing user's token.
    type: <xref href="Microsoft.Identity.Client.UserAssertion?alt=Microsoft.Identity.Client.UserAssertion&text=UserAssertion" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: authority
    description: Specific authority for which the token is requested. Passing a different value than configured does not change the configured value
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion,System.String)
  commentId: M:Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion,System.String)
  name: AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion, String)
  fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion, String)
  nameWithType: IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion, String)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public System.Threading.Tasks.Task<Microsoft.Identity.Client.AuthenticationResult> AcquireTokenOnBehalfOfAsync (System.Collections.Generic.IEnumerable<string> scopes, Microsoft.Identity.Client.UserAssertion userAssertion, string authority);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        abstract member AcquireTokenOnBehalfOfAsync : seq<string> * Microsoft.Identity.Client.UserAssertion * string -> System.Threading.Tasks.Task<Microsoft.Identity.Client.AuthenticationResult>
  - lang: vb
    values:
    - value: Public Function AcquireTokenOnBehalfOfAsync (scopes As IEnumerable(Of String), userAssertion As UserAssertion, authority As String) As Task(Of AuthenticationResult)
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use AcquireTokenOnBehalfOf instead. See https://aka.ms/msal-net-3-breaking-changes. '
  summary: '[V3 API] Acquires token using On-Behalf-Of flow. (See https://aka.ms/msal-net-on-behalf-of)'
  metadata: {}
uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync*
commentId: Overload:Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
namespace: Microsoft.Identity.Client
name: AcquireTokenOnBehalfOfAsync
fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
nameWithType: IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
  - Microsoft::Identity::Client::IConfidentialClientApplication::AcquireTokenOnBehalfOfAsync
  - AcquireTokenOnBehalfOfAsync
  - IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync
  - IConfidentialClientApplication::AcquireTokenOnBehalfOfAsync
  helpviewer_keywords:
  - IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync method [.NET]
  - AcquireTokenOnBehalfOfAsync method [.NET], interface IConfidentialClientApplication
  - IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion) method [.NET]
  - AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion) method [.NET], interface IConfidentialClientApplication
  - IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion, String) method [.NET]
  - AcquireTokenOnBehalfOfAsync(IEnumerable<String>, UserAssertion, String) method [.NET], interface IConfidentialClientApplication
  monikers:
  - msal-dotnet-latest
