### YamlMime:NetDelegate
returnsWithMoniker:
  type:
  - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Tokens.SecurityKey?alt=Microsoft.IdentityModel.Tokens.SecurityKey&text=SecurityKey" data-throw-if-not-resolved="True"/>&gt;
  description: A <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> to use when validating a signature.
parameters:
- namesWithMoniker:
  - value: token
  description: The <xref data-throw-if-not-resolved="true" uid="System.String"></xref> representation of the token that is being validated.
  type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: securityToken
  description: The <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityToken"></xref> that is being validated. It may be null.
  type: <xref href="Microsoft.IdentityModel.Tokens.SecurityToken?alt=Microsoft.IdentityModel.Tokens.SecurityToken&text=SecurityToken" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: kid
  description: A key identifier. It may be null.
  type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: validationParameters
  description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters"></xref> required for validation.
  type: <xref href="Microsoft.IdentityModel.Tokens.TokenValidationParameters?alt=Microsoft.IdentityModel.Tokens.TokenValidationParameters&text=TokenValidationParameters" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: configuration
  description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration"></xref> required for validation.
  type: <xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>
inheritances:
- <xref href="System.Delegate" data-throw-if-not-resolved="True"/>
uid: Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
commentId: T:Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: IssuerSigningKeyResolverUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
nameWithType: Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public delegate System.Collections.Generic.IEnumerable<Microsoft.IdentityModel.Tokens.SecurityKey> IssuerSigningKeyResolverUsingConfiguration(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters, BaseConfiguration configuration);
- lang: fsharp
  values:
  - value: type IssuerSigningKeyResolverUsingConfiguration = delegate of string * SecurityToken * string * TokenValidationParameters * BaseConfiguration -> seq<SecurityKey>
- lang: vb
  values:
  - value: 'Public Delegate Function IssuerSigningKeyResolverUsingConfiguration(token As String, securityToken As SecurityToken, kid As String, validationParameters As TokenValidationParameters, configuration As BaseConfiguration) As IEnumerable(Of SecurityKey) '
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Definition for IssuerSigningKeyResolverUsingConfiguration.
remarks: <p>If both <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolver"></xref> are set, IssuerSigningKeyResolverUsingConfiguration takes priority.</p>
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration..ctor
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration.Invoke
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration.BeginInvoke
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration.EndInvoke
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration
  - Microsoft::IdentityModel::Tokens::IssuerSigningKeyResolverUsingConfiguration
  - IssuerSigningKeyResolverUsingConfiguration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolverUsingConfiguration delegate [.NET]
  monikers:
  - msal-web-dotnet-latest
