### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Abstractions.CredentialDescription?alt=Microsoft.Identity.Abstractions.CredentialDescription&text=CredentialDescription" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  name: ClientCredentials
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  nameWithType: IdentityApplicationOptions.ClientCredentials
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<Microsoft.Identity.Abstractions.CredentialDescription>? ClientCredentials { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ClientCredentials : seq<Microsoft.Identity.Abstractions.CredentialDescription> with get, set'
  - lang: vb
    values:
    - value: Public Property ClientCredentials As IEnumerable(Of CredentialDescription)
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Description of the client credentials provided to prove the identity of the web app,

    web API, or daemon app.
  examples: >-
    An example in the appsetting.json:


    ```

    "ClientCredentials": [
      {
        "SourceType": "StoreWithDistinguishedName",
         "CertificateStorePath": "CurrentUser/My",
         "CertificateDistinguishedName": "CN=WebAppCallingWebApiCert"
        }
       ]
    ```
                 See also https://aka.ms/ms-id-web-certificates.
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
namespace: Microsoft.Identity.Abstractions
name: ClientCredentials
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
nameWithType: IdentityApplicationOptions.ClientCredentials
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_ClientCredentials
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_ClientCredentials
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientCredentials
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::ClientCredentials
  - ClientCredentials
  - IdentityApplicationOptions.ClientCredentials
  - IdentityApplicationOptions::ClientCredentials
  helpviewer_keywords:
  - IdentityApplicationOptions.ClientCredentials property [.NET]
  - ClientCredentials property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
