### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  name: ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'token_endpoint_auth_signing_alg_values_supported' (TokenEndpointAuthSigningAlgValuesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  - ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  - OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  - OpenIdConnectConfiguration::ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported method [.NET]
  - ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported() method [.NET]
  - ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
