### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  commentId: F:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  name: DefaultAutomaticRefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  nameWithType: BaseConfigurationManager.DefaultAutomaticRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan DefaultAutomaticRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable DefaultAutomaticRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly DefaultAutomaticRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 12 hours is the default time interval that afterwards will obtain new configuration.
  metadata: {}
namespace: Microsoft.IdentityModel.Tokens
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultAutomaticRefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::DefaultAutomaticRefreshInterval
  - DefaultAutomaticRefreshInterval
  - BaseConfigurationManager.DefaultAutomaticRefreshInterval
  - BaseConfigurationManager::DefaultAutomaticRefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.DefaultAutomaticRefreshInterval field [.NET]
  - DefaultAutomaticRefreshInterval field [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
