### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  commentId: P:Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  name: RequiredAppPermissionsConfigurationKey
  fullName: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  nameWithType: ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredAppPermissionsConfigurationKey { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredAppPermissionsConfigurationKey : string with get, set'
  - lang: vb
    values:
    - value: Public Property RequiredAppPermissionsConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets the optional list of app permission values from configuration.
  metadata: {}
uid: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
namespace: Microsoft.Identity.Web
name: RequiredAppPermissionsConfigurationKey
fullName: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
nameWithType: ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.get_RequiredAppPermissionsConfigurationKey
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.set_RequiredAppPermissionsConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  - Microsoft::Identity::Web::ScopeOrAppPermissionAuthorizationRequirement::RequiredAppPermissionsConfigurationKey
  - RequiredAppPermissionsConfigurationKey
  - ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey
  - ScopeOrAppPermissionAuthorizationRequirement::RequiredAppPermissionsConfigurationKey
  helpviewer_keywords:
  - ScopeOrAppPermissionAuthorizationRequirement.RequiredAppPermissionsConfigurationKey property [.NET]
  - RequiredAppPermissionsConfigurationKey property [.NET], class ScopeOrAppPermissionAuthorizationRequirement
  monikers:
  - msal-model-dotnet-latest
