### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor(System.String)
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create(System.String)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeAcrValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeDisplayValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeGrantTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIdTokenEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIdTokenEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIdTokenSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeScopesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthMethodsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeTokenEndpointAuthSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeUILocalesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeUserInfoEndpointEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeUserInfoEndpointEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeUserInfoEndpointSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AcrValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ClaimsLocalesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ClaimsParameterSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ClaimsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ClaimTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.DisplayValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.EndSessionEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.FrontchannelLogoutSessionSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.FrontchannelLogoutSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.HttpLogoutSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IdTokenEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IdTokenEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IdTokenSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpointAuthMethodsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpointAuthSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JwksUri
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.LogoutSessionSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpTosUri
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestParameterSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestUriParameterSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ResponseModesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ResponseTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ScopesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ServiceDocumentation
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SubjectTypesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UILocalesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpoint
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpointEncryptionAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpointEncryptionEncValuesSupported
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.UserInfoEndpointSigningAlgValuesSupported
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
commentId: T:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: OpenIdConnectConfiguration
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
nameWithType: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
attributesWithMoniker:
- value: Microsoft.IdentityModel.Json.JsonObjectAttribute
syntaxWithMoniker:
- lang: csharp
  values:
  - value: >-
      [Microsoft.IdentityModel.Json.JsonObject]

      public class OpenIdConnectConfiguration : Microsoft.IdentityModel.Tokens.BaseConfiguration
- lang: fsharp
  values:
  - value: >-
      [<Microsoft.IdentityModel.Json.JsonObject>]

      type OpenIdConnectConfiguration = class
          inherit BaseConfiguration
- lang: vb
  values:
  - value: >-
      Public Class OpenIdConnectConfiguration

      Inherits BaseConfiguration
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Contains OpenIdConnect configuration that can be populated from a json string.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration
  - OpenIdConnectConfiguration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration class [.NET]
  monikers:
  - msal-web-dotnet-latest
