### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.Issuer
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfiguration
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfiguration
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.TokenEndpoint
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
commentId: T:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: WsFederationConfiguration
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
nameWithType: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class WsFederationConfiguration : Microsoft.IdentityModel.Tokens.BaseConfiguration'
- lang: fsharp
  values:
  - value: >-
      type WsFederationConfiguration = class
          inherit BaseConfiguration
- lang: vb
  values:
  - value: >-
      Public Class WsFederationConfiguration

      Inherits BaseConfiguration
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Contains WsFederation metadata that can be populated from a XML string.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration
  - WsFederationConfiguration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration class [.NET]
  monikers:
  - msal-web-dotnet-latest
