### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Xml.Signature?alt=Microsoft.IdentityModel.Xml.Signature&text=Signature" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  commentId: P:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  name: Signature
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  nameWithType: WsFederationConfiguration.Signature
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Xml.Signature Signature { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Signature : Microsoft.IdentityModel.Xml.Signature with get, set'
  - lang: vb
    values:
    - value: Public Property Signature As Signature
  monikers:
  - msal-web-dotnet-latest
  summary: The <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Xml.Signature"></xref> element that was found when reading metadata.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: Signature
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
nameWithType: WsFederationConfiguration.Signature
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.get_Signature
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.set_Signature
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.Signature
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration::Signature
  - Signature
  - WsFederationConfiguration.Signature
  - WsFederationConfiguration::Signature
  helpviewer_keywords:
  - WsFederationConfiguration.Signature property [.NET]
  - Signature property [.NET], class WsFederationConfiguration
  monikers:
  - msal-web-dotnet-latest
