### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  commentId: P:Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  name: IsBrokerEnabled
  fullName: Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  nameWithType: IAppConfig.IsBrokerEnabled
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsBrokerEnabled { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsBrokerEnabled : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsBrokerEnabled As Boolean
  monikers:
  - msal-dotnet-latest
  summary: Indicates whether or not the current application object is configured to use brokered authentication.
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
namespace: Microsoft.Identity.Client
name: IsBrokerEnabled
fullName: Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
nameWithType: IAppConfig.IsBrokerEnabled
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  - Microsoft.Identity.Client.IAppConfig.get_IsBrokerEnabled
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  - Microsoft::Identity::Client::IAppConfig::IsBrokerEnabled
  - IsBrokerEnabled
  - IAppConfig.IsBrokerEnabled
  - IAppConfig::IsBrokerEnabled
  helpviewer_keywords:
  - IAppConfig.IsBrokerEnabled property [.NET]
  - IsBrokerEnabled property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
