### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: Configuration of type Configuration.
  parameters:
  - namesWithMoniker:
    - value: cancel
    description: CancellationToken
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  name: GetBaseConfigurationAsync(CancellationToken)
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync(CancellationToken)
  nameWithType: BaseConfigurationManager.GetBaseConfigurationAsync(CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public virtual System.Threading.Tasks.Task<Microsoft.IdentityModel.Tokens.BaseConfiguration> GetBaseConfigurationAsync (System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: >-
        abstract member GetBaseConfigurationAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Tokens.BaseConfiguration>

        override this.GetBaseConfigurationAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Tokens.BaseConfiguration>
  - lang: vb
    values:
    - value: Public Overridable Function GetBaseConfigurationAsync (cancel As CancellationToken) As Task(Of BaseConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Obtains an updated version of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration"></xref> if the appropriate refresh interval has passed.

    This method may return a cached version of the configuration.
  remarks: <p>This method on the base class throws a <xref data-throw-if-not-resolved="true" uid="System.NotImplementedException"></xref> as it is meant to be overridden by the class that extends it.</p>
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync
namespace: Microsoft.IdentityModel.Tokens
name: GetBaseConfigurationAsync
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync
nameWithType: BaseConfigurationManager.GetBaseConfigurationAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.GetBaseConfigurationAsync
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::GetBaseConfigurationAsync
  - GetBaseConfigurationAsync
  - BaseConfigurationManager.GetBaseConfigurationAsync
  - BaseConfigurationManager::GetBaseConfigurationAsync
  helpviewer_keywords:
  - BaseConfigurationManager.GetBaseConfigurationAsync method [.NET]
  - GetBaseConfigurationAsync method [.NET], class BaseConfigurationManager
  - BaseConfigurationManager.GetBaseConfigurationAsync(CancellationToken) method [.NET]
  - GetBaseConfigurationAsync(CancellationToken) method [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
