### YamlMime:NetType
type: interface
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ClientApplicationBase
- value: Microsoft.Identity.Client.ConfidentialClientApplication
- value: Microsoft.Identity.Client.IConfidentialClientApplication
- value: Microsoft.Identity.Client.IPublicClientApplication
- value: Microsoft.Identity.Client.PublicClientApplication
methods:
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountAsync(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetUser(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Remove(Microsoft.Identity.Client.IUser)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.IClientApplicationBase.AppConfig
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Authority
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ClientId
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Component
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RedirectUri
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.SliceParameters
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Users
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.IClientApplicationBase
commentId: T:Microsoft.Identity.Client.IClientApplicationBase
namespace: Microsoft.Identity.Client
name: IClientApplicationBase
fullName: Microsoft.Identity.Client.IClientApplicationBase
nameWithType: Microsoft.Identity.Client.IClientApplicationBase
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public interface IClientApplicationBase
- lang: fsharp
  values:
  - value: type IClientApplicationBase = interface
- lang: vb
  values:
  - value: Public Interface IClientApplicationBase
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Abstract class containing common API methods and properties. Both <xref data-throw-if-not-resolved="true" uid="PublicClientApplication"></xref> and <xref data-throw-if-not-resolved="true" uid="ConfidentialClientApplication"></xref>

  extend this class. For details see https://aka.ms/msal-net-client-applications.
metadata:
  api_name:
  - Microsoft.Identity.Client.IClientApplicationBase
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IClientApplicationBase
  - Microsoft::Identity::Client::IClientApplicationBase
  - IClientApplicationBase
  helpviewer_keywords:
  - Microsoft.Identity.Client.IClientApplicationBase interface [.NET]
  monikers:
  - msal-dotnet-latest
