### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ConfidentialClientApplicationOptions
- value: Microsoft.Identity.Client.PublicClientApplicationOptions
constructors:
- uid: Microsoft.Identity.Client.ApplicationOptions.#ctor
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.AzureCloudInstance
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientId
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientName
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientVersion
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.Component
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.Instance
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.IsDefaultPlatformLoggingEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.LogLevel
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.RedirectUri
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.TenantId
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.ApplicationOptions
commentId: T:Microsoft.Identity.Client.ApplicationOptions
namespace: Microsoft.Identity.Client
name: ApplicationOptions
fullName: Microsoft.Identity.Client.ApplicationOptions
nameWithType: Microsoft.Identity.Client.ApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public abstract class ApplicationOptions
- lang: fsharp
  values:
  - value: type ApplicationOptions = class
- lang: vb
  values:
  - value: Public MustInherit Class ApplicationOptions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Base class for options objects with string values loadable from a configuration file

  (for instance a JSON file, as in an asp.net configuration scenario)

  See https://aka.ms/msal-net-application-configuration

  See also derived classes <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.PublicClientApplicationOptions"></xref>

  and <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplicationOptions"></xref>
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions
  - Microsoft::Identity::Client::ApplicationOptions
  - ApplicationOptions
  helpviewer_keywords:
  - Microsoft.Identity.Client.ApplicationOptions class [.NET]
  monikers:
  - msal-dotnet-latest
