### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  name: ShouldSerializeRequestObjectSigningAlgValuesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeRequestObjectSigningAlgValuesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeRequestObjectSigningAlgValuesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeRequestObjectSigningAlgValuesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'request_object_signing_alg_values_supported' (RequestObjectSigningAlgValuesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeRequestObjectSigningAlgValuesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeRequestObjectSigningAlgValuesSupported
  - ShouldSerializeRequestObjectSigningAlgValuesSupported
  - OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported
  - OpenIdConnectConfiguration::ShouldSerializeRequestObjectSigningAlgValuesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported method [.NET]
  - ShouldSerializeRequestObjectSigningAlgValuesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeRequestObjectSigningAlgValuesSupported() method [.NET]
  - ShouldSerializeRequestObjectSigningAlgValuesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
