### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.TenantId
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.TenantId
  name: TenantId
  fullName: Microsoft.Identity.Client.ApplicationOptions.TenantId
  nameWithType: ApplicationOptions.TenantId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string TenantId { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.TenantId : string with get, set'
  - lang: vb
    values:
    - value: Public Property TenantId As String
  monikers:
  - msal-dotnet-latest
  summary: >-
    Tenant from which the application will allow users to sign it. This can be:

    a domain associated with a tenant, a GUID (tenant id), or a meta-tenant (e.g. consumers).

    This property is mutually exclusive with <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience"></xref>. If both

    are provided, an exception will be thrown.
  remarks: <p>The name of the property was chosen to ensure compatibility with AzureAdOptions in ASP.NET Core configuration files (even the semantics would be tenant)</p>
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.TenantId*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.TenantId
namespace: Microsoft.Identity.Client
name: TenantId
fullName: Microsoft.Identity.Client.ApplicationOptions.TenantId
nameWithType: ApplicationOptions.TenantId
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.TenantId
  - Microsoft.Identity.Client.ApplicationOptions.get_TenantId
  - Microsoft.Identity.Client.ApplicationOptions.set_TenantId
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.TenantId
  - Microsoft::Identity::Client::ApplicationOptions::TenantId
  - TenantId
  - ApplicationOptions.TenantId
  - ApplicationOptions::TenantId
  helpviewer_keywords:
  - ApplicationOptions.TenantId property [.NET]
  - TenantId property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
