### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor
  commentId: M:Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor
  name: BaseConfiguration()
  fullName: Microsoft.IdentityModel.Tokens.BaseConfiguration.BaseConfiguration()
  nameWithType: BaseConfiguration.BaseConfiguration()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected BaseConfiguration ();
  - lang: vb
    values:
    - value: Protected Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor
namespace: Microsoft.IdentityModel.Tokens
name: BaseConfiguration
fullName: Microsoft.IdentityModel.Tokens.BaseConfiguration.BaseConfiguration
nameWithType: BaseConfiguration.BaseConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration..ctor
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration.#ctor
  - Microsoft::IdentityModel::Tokens::BaseConfiguration::#ctor
  - '#ctor'
  - BaseConfiguration.#ctor
  - BaseConfiguration::#ctor
  helpviewer_keywords:
  - BaseConfiguration class [.NET], constructors
  - BaseConfiguration() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
