### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder&text=MicrosoftIdentityBaseAuthenticationBuilder" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder&text=MicrosoftIdentityWebAppAuthenticationBuilder" data-throw-if-not-resolved="True"/>
methods:
- uid: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder.EnableTokenAcquisitionToCallDownstreamApi(System.Action{Microsoft.Identity.Client.ConfidentialClientApplicationOptions},System.Collections.Generic.IEnumerable{System.String})
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-model-dotnet-latest
properties:
- uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.Services
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
uid: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
commentId: T:Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
namespace: Microsoft.Identity.Web
name: MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
fullName: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
nameWithType: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration : Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder'
- lang: fsharp
  values:
  - value: >-
      type MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration = class
          inherit MicrosoftIdentityWebAppAuthenticationBuilder
- lang: vb
  values:
  - value: >-
      Public Class MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration

      Inherits MicrosoftIdentityWebAppAuthenticationBuilder
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
summary: >-
  Builder for a Microsoft identity web app authentication where configuration is

  available for EnableTokenAcquisitionToCallDownstreamApi.
metadata:
  api_name:
  - Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  - Microsoft::Identity::Web::MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  - MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  helpviewer_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration class [.NET]
  monikers:
  - msal-model-dotnet-latest
