### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.Identity.Client.IClientApplicationBase?alt=Microsoft.Identity.Client.IClientApplicationBase&text=IClientApplicationBase" data-throw-if-not-resolved="True"/>
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ConfidentialClientApplication
- value: Microsoft.Identity.Client.PublicClientApplication
methods:
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,System.String,System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountAsync(System.String,System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountAsync(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String,System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.GetUser(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Remove(Microsoft.Identity.Client.IUser)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount,System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.ClientApplicationBase.AppConfig
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Authority
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.ClientId
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Component
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.RedirectUri
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.SliceParameters
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.Users
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.UserTokenCache
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ClientApplicationBase.ValidateAuthority
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.ClientApplicationBase
commentId: T:Microsoft.Identity.Client.ClientApplicationBase
namespace: Microsoft.Identity.Client
name: ClientApplicationBase
fullName: Microsoft.Identity.Client.ClientApplicationBase
nameWithType: Microsoft.Identity.Client.ClientApplicationBase
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public abstract class ClientApplicationBase : Microsoft.Identity.Client.IClientApplicationBase'
- lang: fsharp
  values:
  - value: >-
      type ClientApplicationBase = class
          interface IClientApplicationBase
- lang: vb
  values:
  - value: >-
      Public MustInherit Class ClientApplicationBase

      Implements IClientApplicationBase
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Abstract class containing common API methods and properties. Both <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.PublicClientApplication"></xref> and 

  ConfidentialClientApplication

  extend this class. For details see https://aka.ms/msal-net-client-applications
metadata:
  api_name:
  - Microsoft.Identity.Client.ClientApplicationBase
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ClientApplicationBase
  - Microsoft::Identity::Client::ClientApplicationBase
  - ClientApplicationBase
  helpviewer_keywords:
  - Microsoft.Identity.Client.ClientApplicationBase class [.NET]
  monikers:
  - msal-dotnet-latest
