### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: T
  parameters:
  - namesWithMoniker:
    - value: clientName
    description: The name of the application for telemetry purposes.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName(System.String)
  commentId: M:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName(System.String)
  name: WithClientName(String)
  fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithClientName(String)
  nameWithType: AbstractApplicationBuilder<T>.WithClientName(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public T WithClientName (string clientName);
  - lang: fsharp
    values:
    - value: "member this.WithClientName : string -> 'T"
  - lang: vb
    values:
    - value: Public Function WithClientName (clientName As String) As T
  monikers:
  - msal-dotnet-latest
  summary: Sets the name of the calling application for telemetry purposes.
  metadata: {}
uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName*
commentId: Overload:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName
namespace: Microsoft.Identity.Client
name: WithClientName
fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithClientName
nameWithType: AbstractApplicationBuilder<T>.WithClientName
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName
  - Microsoft::Identity::Client::AbstractApplicationBuilder`1::WithClientName
  - Microsoft.Identity.Client.AbstractApplicationBuilder.WithClientName
  - WithClientName
  - AbstractApplicationBuilder`1.WithClientName
  - AbstractApplicationBuilder`1::WithClientName
  helpviewer_keywords:
  - AbstractApplicationBuilder<T>.WithClientName method [.NET]
  - WithClientName method [.NET], class AbstractApplicationBuilder<T>
  - AbstractApplicationBuilder<T>.WithClientName(String) method [.NET]
  - WithClientName(String) method [.NET], class AbstractApplicationBuilder<T>
  monikers:
  - msal-dotnet-latest
