### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  name: ShouldSerializeSubjectTypesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeSubjectTypesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeSubjectTypesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeSubjectTypesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'subject_types_supported' (SubjectTypesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeSubjectTypesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeSubjectTypesSupported
  - ShouldSerializeSubjectTypesSupported
  - OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported
  - OpenIdConnectConfiguration::ShouldSerializeSubjectTypesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported method [.NET]
  - ShouldSerializeSubjectTypesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeSubjectTypesSupported() method [.NET]
  - ShouldSerializeSubjectTypesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
