### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  commentId: F:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  name: DefaultLastKnownGoodConfigurationLifetime
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  nameWithType: BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan DefaultLastKnownGoodConfigurationLifetime;
  - lang: fsharp
    values:
    - value: ' staticval mutable DefaultLastKnownGoodConfigurationLifetime : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly DefaultLastKnownGoodConfigurationLifetime As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 1 hour is the default time interval that a last known good configuration will last for.
  metadata: {}
namespace: Microsoft.IdentityModel.Tokens
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::DefaultLastKnownGoodConfigurationLifetime
  - DefaultLastKnownGoodConfigurationLifetime
  - BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime
  - BaseConfigurationManager::DefaultLastKnownGoodConfigurationLifetime
  helpviewer_keywords:
  - BaseConfigurationManager.DefaultLastKnownGoodConfigurationLifetime field [.NET]
  - DefaultLastKnownGoodConfigurationLifetime field [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
