### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Xml.KeyInfo?alt=Microsoft.IdentityModel.Xml.KeyInfo&text=KeyInfo" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  commentId: P:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  name: KeyInfos
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  nameWithType: WsFederationConfiguration.KeyInfos
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.ICollection<Microsoft.IdentityModel.Xml.KeyInfo> KeyInfos { get; }
  - lang: fsharp
    values:
    - value: 'member this.KeyInfos : System.Collections.Generic.ICollection<Microsoft.IdentityModel.Xml.KeyInfo>'
  - lang: vb
    values:
    - value: Public ReadOnly Property KeyInfos As ICollection(Of KeyInfo)
  monikers:
  - msal-web-dotnet-latest
  summary: Get the <xref data-throw-if-not-resolved="true" uid="System.Collections.Generic.IList`1"></xref> that the IdentityProvider indicates are to be used signing keys.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: KeyInfos
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
nameWithType: WsFederationConfiguration.KeyInfos
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.get_KeyInfos
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.KeyInfos
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration::KeyInfos
  - KeyInfos
  - WsFederationConfiguration.KeyInfos
  - WsFederationConfiguration::KeyInfos
  helpviewer_keywords:
  - WsFederationConfiguration.KeyInfos property [.NET]
  - KeyInfos property [.NET], class WsFederationConfiguration
  monikers:
  - msal-web-dotnet-latest
