### YamlMime:NetType
typeParameters:
- description: The type of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref>.
  name: T
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationManager`1?alt=Microsoft.IdentityModel.Protocols.IConfigurationManager`1&text=IConfigurationManager%3CT%3E" data-throw-if-not-resolved="True"/>
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.IdentityModel.Tokens.BaseConfigurationManager?alt=Microsoft.IdentityModel.Tokens.BaseConfigurationManager&text=BaseConfigurationManager" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.#ctor(System.String,Microsoft.IdentityModel.Protocols.IConfigurationRetriever{`0},System.Net.Http.HttpClient)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.#ctor(System.String,Microsoft.IdentityModel.Protocols.IConfigurationRetriever{`0},Microsoft.IdentityModel.Protocols.IDocumentRetriever,Microsoft.IdentityModel.Protocols.IConfigurationValidator{`0})
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.#ctor(System.String,Microsoft.IdentityModel.Protocols.IConfigurationRetriever{`0},Microsoft.IdentityModel.Protocols.IDocumentRetriever)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.#ctor(System.String,Microsoft.IdentityModel.Protocols.IConfigurationRetriever{`0})
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetBaseConfigurationAsync(System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodConfiguration
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  inheritedFrom: Microsoft.IdentityModel.Tokens.BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
fields:
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultAutomaticRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1
commentId: T:Microsoft.IdentityModel.Protocols.ConfigurationManager`1
namespace: Microsoft.IdentityModel.Protocols
name: ConfigurationManager<T>
fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>
nameWithType: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class ConfigurationManager<T> : Microsoft.IdentityModel.Tokens.BaseConfigurationManager, Microsoft.IdentityModel.Protocols.IConfigurationManager<T> where T : class'
- lang: fsharp
  values:
  - value: >-
      type ConfigurationManager<'T (requires 'T : null)> = class
          inherit BaseConfigurationManager
          interface IConfigurationManager<'T (requires 'T : null)>
- lang: vb
  values:
  - value: >-
      Public Class ConfigurationManager(Of T)

      Inherits BaseConfigurationManager

      Implements IConfigurationManager(Of T)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Manages the retrieval of Configuration data.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1
  - Microsoft::IdentityModel::Protocols::ConfigurationManager`1
  - Microsoft.IdentityModel.Protocols.ConfigurationManager
  - ConfigurationManager`1
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager<T> class [.NET]
  monikers:
  - msal-web-dotnet-latest
