### YamlMime:NetMember
type: method
members:
- type: method
  uid: Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
  commentId: M:Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
  name: InitializeProcessSecurity()
  fullName: Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity()
  nameWithType: WindowsNativeUtils.InitializeProcessSecurity()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static void InitializeProcessSecurity ();
  - lang: fsharp
    values:
    - value: 'static member InitializeProcessSecurity : unit -> unit'
  - lang: vb
    values:
    - value: Public Shared Sub InitializeProcessSecurity ()
  monikers:
  - msal-dotnet-latest
  summary: Registers security and sets the security values for the process.
  remarks: Workaround to enable WAM Account Picker in an elevated process.
  metadata: {}
uid: Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity*
commentId: Overload:Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
namespace: Microsoft.Identity.Client.Utils.Windows
name: InitializeProcessSecurity
fullName: Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
nameWithType: WindowsNativeUtils.InitializeProcessSecurity
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.Utils.Windows.WindowsNativeUtils.InitializeProcessSecurity
  - Microsoft::Identity::Client::Utils::Windows::WindowsNativeUtils::InitializeProcessSecurity
  - InitializeProcessSecurity
  - WindowsNativeUtils.InitializeProcessSecurity
  - WindowsNativeUtils::InitializeProcessSecurity
  helpviewer_keywords:
  - WindowsNativeUtils.InitializeProcessSecurity method [.NET]
  - InitializeProcessSecurity method [.NET], class WindowsNativeUtils
  - WindowsNativeUtils.InitializeProcessSecurity() method [.NET]
  - InitializeProcessSecurity() method [.NET], class WindowsNativeUtils
  monikers:
  - msal-dotnet-latest
