### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.LogLevel?alt=Microsoft.Identity.Client.LogLevel&text=LogLevel" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.LogLevel
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.LogLevel
  name: LogLevel
  fullName: Microsoft.Identity.Client.ApplicationOptions.LogLevel
  nameWithType: ApplicationOptions.LogLevel
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.LogLevel LogLevel { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.LogLevel : Microsoft.Identity.Client.LogLevel with get, set'
  - lang: vb
    values:
    - value: Public Property LogLevel As LogLevel
  monikers:
  - msal-dotnet-latest
  summary: >-
    Enables you to configure the level of logging you want. The default value is <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.LogLevel.Info"></xref>. Setting it to <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.LogLevel.Error"></xref> will only get errors

    Setting it to <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.LogLevel.Warning"></xref> will get errors and warning, etc..

    See https://aka.ms/msal-net-logging
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.LogLevel*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.LogLevel
namespace: Microsoft.Identity.Client
name: LogLevel
fullName: Microsoft.Identity.Client.ApplicationOptions.LogLevel
nameWithType: ApplicationOptions.LogLevel
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.LogLevel
  - Microsoft.Identity.Client.ApplicationOptions.get_LogLevel
  - Microsoft.Identity.Client.ApplicationOptions.set_LogLevel
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.LogLevel
  - Microsoft::Identity::Client::ApplicationOptions::LogLevel
  - LogLevel
  - ApplicationOptions.LogLevel
  - ApplicationOptions::LogLevel
  helpviewer_keywords:
  - ApplicationOptions.LogLevel property [.NET]
  - LogLevel property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
