### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  name: Audience
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  nameWithType: IdentityApplicationOptions.Audience
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? Audience { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Audience : string with get, set'
  - lang: vb
    values:
    - value: Public Property Audience As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    In a web API, audience of the tokens that will be accepted by the web API.

    <p>If your web API accepts several audiences, see <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences"></xref>.</p>
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
namespace: Microsoft.Identity.Abstractions
name: Audience
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
nameWithType: IdentityApplicationOptions.Audience
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_Audience
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_Audience
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::Audience
  - Audience
  - IdentityApplicationOptions.Audience
  - IdentityApplicationOptions::Audience
  helpviewer_keywords:
  - IdentityApplicationOptions.Audience property [.NET]
  - Audience property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
