### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  name: SignUpSignInPolicyId
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  nameWithType: MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? SignUpSignInPolicyId { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.SignUpSignInPolicyId : string with get, set'
  - lang: vb
    values:
    - value: Public Property SignUpSignInPolicyId As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the sign up or sign in user flow name for B2C, e.g. b2c_1_susi.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
namespace: Microsoft.Identity.Abstractions
name: SignUpSignInPolicyId
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
nameWithType: MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_SignUpSignInPolicyId
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_SignUpSignInPolicyId
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::SignUpSignInPolicyId
  - SignUpSignInPolicyId
  - MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId
  - MicrosoftIdentityApplicationOptions::SignUpSignInPolicyId
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.SignUpSignInPolicyId property [.NET]
  - SignUpSignInPolicyId property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
