### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.TenantId
  commentId: P:Microsoft.Identity.Client.IAppConfig.TenantId
  name: TenantId
  fullName: Microsoft.Identity.Client.IAppConfig.TenantId
  nameWithType: IAppConfig.TenantId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string TenantId { get; }
  - lang: fsharp
    values:
    - value: 'member this.TenantId : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property TenantId As String
  monikers:
  - msal-dotnet-latest
  summary: Audience for the application. See <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ApplicationOptions.TenantId"></xref>
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.TenantId*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.TenantId
namespace: Microsoft.Identity.Client
name: TenantId
fullName: Microsoft.Identity.Client.IAppConfig.TenantId
nameWithType: IAppConfig.TenantId
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.TenantId
  - Microsoft.Identity.Client.IAppConfig.get_TenantId
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.TenantId
  - Microsoft::Identity::Client::IAppConfig::TenantId
  - TenantId
  - IAppConfig.TenantId
  - IAppConfig::TenantId
  helpviewer_keywords:
  - IAppConfig.TenantId property [.NET]
  - TenantId property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
