### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  name: LegacyCacheCompatibilityEnabled
  fullName: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  nameWithType: ApplicationOptions.LegacyCacheCompatibilityEnabled
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool LegacyCacheCompatibilityEnabled { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.LegacyCacheCompatibilityEnabled : bool with get, set'
  - lang: vb
    values:
    - value: Public Property LegacyCacheCompatibilityEnabled As Boolean
  monikers:
  - msal-dotnet-latest
  summary: Enables legacy ADAL cache serialization and deserialization.
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
namespace: Microsoft.Identity.Client
name: LegacyCacheCompatibilityEnabled
fullName: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
nameWithType: ApplicationOptions.LegacyCacheCompatibilityEnabled
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  - Microsoft.Identity.Client.ApplicationOptions.get_LegacyCacheCompatibilityEnabled
  - Microsoft.Identity.Client.ApplicationOptions.set_LegacyCacheCompatibilityEnabled
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  - Microsoft::Identity::Client::ApplicationOptions::LegacyCacheCompatibilityEnabled
  - LegacyCacheCompatibilityEnabled
  - ApplicationOptions.LegacyCacheCompatibilityEnabled
  - ApplicationOptions::LegacyCacheCompatibilityEnabled
  helpviewer_keywords:
  - ApplicationOptions.LegacyCacheCompatibilityEnabled property [.NET]
  - LegacyCacheCompatibilityEnabled property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
