### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.BaseConfigurationManager?alt=Microsoft.IdentityModel.Tokens.BaseConfigurationManager&text=BaseConfigurationManager" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
  commentId: P:Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
  name: ConfigurationManager
  fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
  nameWithType: TokenValidationParameters.ConfigurationManager
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.BaseConfigurationManager ConfigurationManager { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ConfigurationManager : Microsoft.IdentityModel.Tokens.BaseConfigurationManager with get, set'
  - lang: vb
    values:
    - value: Public Property ConfigurationManager As BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    If set, this property will be used to obtain the issuer and signing keys associated with the metadata endpoint of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration.Issuer"></xref>.

    The obtained issuer and signing keys will then be used along with those present on the TokenValidationParameters for validation of the incoming token.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager*
commentId: Overload:Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
namespace: Microsoft.IdentityModel.Tokens
name: ConfigurationManager
fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
nameWithType: TokenValidationParameters.ConfigurationManager
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.get_ConfigurationManager
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.set_ConfigurationManager
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.ConfigurationManager
  - Microsoft::IdentityModel::Tokens::TokenValidationParameters::ConfigurationManager
  - ConfigurationManager
  - TokenValidationParameters.ConfigurationManager
  - TokenValidationParameters::ConfigurationManager
  helpviewer_keywords:
  - TokenValidationParameters.ConfigurationManager property [.NET]
  - ConfigurationManager property [.NET], class TokenValidationParameters
  monikers:
  - msal-web-dotnet-latest
