### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor
  name: OpenIdConnectConfiguration()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpenIdConnectConfiguration()
  nameWithType: OpenIdConnectConfiguration.OpenIdConnectConfiguration()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public OpenIdConnectConfiguration ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  summary: Initializes an new instance of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref>.
  metadata: {}
- parameters:
  - namesWithMoniker:
    - value: json
    description: a json string containing the metadata
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: If 'json' is null or empty.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor(System.String)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor(System.String)
  name: OpenIdConnectConfiguration(String)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpenIdConnectConfiguration(String)
  nameWithType: OpenIdConnectConfiguration.OpenIdConnectConfiguration(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public OpenIdConnectConfiguration (string json);
  - lang: fsharp
    values:
    - value: 'new Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration : string -> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration'
  - lang: vb
    values:
    - value: Public Sub New (json As String)
  monikers:
  - msal-web-dotnet-latest
  summary: Initializes an new instance of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> from a json string.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: OpenIdConnectConfiguration
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpenIdConnectConfiguration
nameWithType: OpenIdConnectConfiguration.OpenIdConnectConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.#ctor
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::#ctor
  - '#ctor'
  - OpenIdConnectConfiguration.#ctor
  - OpenIdConnectConfiguration::#ctor
  helpviewer_keywords:
  - OpenIdConnectConfiguration class [.NET], constructors
  - OpenIdConnectConfiguration() class [.NET], constructors
  - OpenIdConnectConfiguration(String) class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
