### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.IssuerSigningKeyValidatorUsingConfiguration?alt=Microsoft.IdentityModel.Tokens.IssuerSigningKeyValidatorUsingConfiguration&text=IssuerSigningKeyValidatorUsingConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  name: IssuerSigningKeyValidatorUsingConfiguration
  fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  nameWithType: TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.IssuerSigningKeyValidatorUsingConfiguration IssuerSigningKeyValidatorUsingConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.IssuerSigningKeyValidatorUsingConfiguration : Microsoft.IdentityModel.Tokens.IssuerSigningKeyValidatorUsingConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property IssuerSigningKeyValidatorUsingConfiguration As IssuerSigningKeyValidatorUsingConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets a delegate for validating the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> that signed the token.
  remarks: <p>If set, this delegate will be called to validate the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> that signed the token, instead of default processing. This means that no default <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityKey"></xref> validation will occur. Even if <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.ValidateIssuerSigningKey"></xref> is false, this delegate will still be called. This delegate should be used if properties from the configuration retrieved from the authority are necessary to validate the issuer signing key. If both <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidator"></xref> are set, IssuerSigningKeyValidatorUsingConfiguration takes priority.</p>
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: IssuerSigningKeyValidatorUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
nameWithType: TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.get_IssuerSigningKeyValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.set_IssuerSigningKeyValidatorUsingConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  - Microsoft::IdentityModel::Tokens::TokenValidationParameters::IssuerSigningKeyValidatorUsingConfiguration
  - IssuerSigningKeyValidatorUsingConfiguration
  - TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration
  - TokenValidationParameters::IssuerSigningKeyValidatorUsingConfiguration
  helpviewer_keywords:
  - TokenValidationParameters.IssuerSigningKeyValidatorUsingConfiguration property [.NET]
  - IssuerSigningKeyValidatorUsingConfiguration property [.NET], class TokenValidationParameters
  monikers:
  - msal-web-dotnet-latest
