### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  commentId: F:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  name: MinimumRefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  nameWithType: BaseConfigurationManager.MinimumRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan MinimumRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable MinimumRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly MinimumRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 1 second is the minimum time interval that must pass for <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh"></xref> to  obtain new configuration.
  metadata: {}
namespace: Microsoft.IdentityModel.Tokens
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MinimumRefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::MinimumRefreshInterval
  - MinimumRefreshInterval
  - BaseConfigurationManager.MinimumRefreshInterval
  - BaseConfigurationManager::MinimumRefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.MinimumRefreshInterval field [.NET]
  - MinimumRefreshInterval field [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
