### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
  commentId: P:Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
  name: IsApplicationCache
  fullName: Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
  nameWithType: TokenCacheNotificationArgs.IsApplicationCache
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsApplicationCache { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsApplicationCache : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsApplicationCache As Boolean
  monikers:
  - msal-dotnet-latest
  summary: Indicates whether the cache change occurred in the UserTokenCache or in the AppTokenCache.
  remarks: <p>The Application Cache is used in Client Credential grant,  which is not available on all platforms. See https://aka.ms/msal-net-app-cache-serialization for details.</p>
  metadata: {}
uid: Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache*
commentId: Overload:Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
namespace: Microsoft.Identity.Client
name: IsApplicationCache
fullName: Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
nameWithType: TokenCacheNotificationArgs.IsApplicationCache
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
  - Microsoft.Identity.Client.TokenCacheNotificationArgs.get_IsApplicationCache
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.TokenCacheNotificationArgs.IsApplicationCache
  - Microsoft::Identity::Client::TokenCacheNotificationArgs::IsApplicationCache
  - IsApplicationCache
  - TokenCacheNotificationArgs.IsApplicationCache
  - TokenCacheNotificationArgs::IsApplicationCache
  helpviewer_keywords:
  - TokenCacheNotificationArgs.IsApplicationCache property [.NET]
  - IsApplicationCache property [.NET], class TokenCacheNotificationArgs
  monikers:
  - msal-dotnet-latest
