### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  name: RequireRequestUriRegistration
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  nameWithType: OpenIdConnectConfiguration.RequireRequestUriRegistration
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="require_request_uri_registration", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public bool RequireRequestUriRegistration { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="require_request_uri_registration", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.RequireRequestUriRegistration : bool with get, set
  - lang: vb
    values:
    - value: Public Property RequireRequestUriRegistration As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'require_request_uri_registration'
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: RequireRequestUriRegistration
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
nameWithType: OpenIdConnectConfiguration.RequireRequestUriRegistration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_RequireRequestUriRegistration
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_RequireRequestUriRegistration
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequireRequestUriRegistration
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::RequireRequestUriRegistration
  - RequireRequestUriRegistration
  - OpenIdConnectConfiguration.RequireRequestUriRegistration
  - OpenIdConnectConfiguration::RequireRequestUriRegistration
  helpviewer_keywords:
  - OpenIdConnectConfiguration.RequireRequestUriRegistration property [.NET]
  - RequireRequestUriRegistration property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
