### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Extensions.Configuration.IConfigurationSection?alt=Microsoft.Extensions.Configuration.IConfigurationSection&text=IConfigurationSection" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  commentId: P:Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  name: ConfigurationSection
  fullName: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  nameWithType: MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected Microsoft.Extensions.Configuration.IConfigurationSection? ConfigurationSection { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ConfigurationSection : Microsoft.Extensions.Configuration.IConfigurationSection with get, set'
  - lang: vb
    values:
    - value: Protected Property ConfigurationSection As IConfigurationSection
  monikers:
  - msal-model-dotnet-latest
  summary: Configuration section from which to bind options.
  remarks: <p>It can be null if the configuration happens with delegates rather than configuration.</p>
  metadata: {}
uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection*
commentId: Overload:Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
namespace: Microsoft.Identity.Web
name: ConfigurationSection
fullName: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
nameWithType: MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  - Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.get_ConfigurationSection
  - Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.set_ConfigurationSection
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  - Microsoft::Identity::Web::MicrosoftIdentityBaseAuthenticationBuilder::ConfigurationSection
  - ConfigurationSection
  - MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  - MicrosoftIdentityBaseAuthenticationBuilder::ConfigurationSection
  helpviewer_keywords:
  - MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection property [.NET]
  - ConfigurationSection property [.NET], class MicrosoftIdentityBaseAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
