### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.LogCallback?alt=Microsoft.Identity.Client.LogCallback&text=LogCallback" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.LoggingCallback
  commentId: P:Microsoft.Identity.Client.IAppConfig.LoggingCallback
  name: LoggingCallback
  fullName: Microsoft.Identity.Client.IAppConfig.LoggingCallback
  nameWithType: IAppConfig.LoggingCallback
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.LogCallback LoggingCallback { get; }
  - lang: fsharp
    values:
    - value: 'member this.LoggingCallback : Microsoft.Identity.Client.LogCallback'
  - lang: vb
    values:
    - value: Public ReadOnly Property LoggingCallback As LogCallback
  monikers:
  - msal-dotnet-latest
  summary: >-
    Callback used for logging. It was set with <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLogging(Microsoft.Identity.Client.LogCallback,System.Nullable{Microsoft.Identity.Client.LogLevel},System.Nullable{System.Boolean},System.Nullable{System.Boolean})"></xref>

    See https://aka.ms/msal-net-logging
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.LoggingCallback*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.LoggingCallback
namespace: Microsoft.Identity.Client
name: LoggingCallback
fullName: Microsoft.Identity.Client.IAppConfig.LoggingCallback
nameWithType: IAppConfig.LoggingCallback
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.LoggingCallback
  - Microsoft.Identity.Client.IAppConfig.get_LoggingCallback
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.LoggingCallback
  - Microsoft::Identity::Client::IAppConfig::LoggingCallback
  - LoggingCallback
  - IAppConfig.LoggingCallback
  - IAppConfig::LoggingCallback
  helpviewer_keywords:
  - IAppConfig.LoggingCallback property [.NET]
  - LoggingCallback property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
