### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Client.ApplicationOptions?alt=Microsoft.Identity.Client.ApplicationOptions&text=ApplicationOptions" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.AzureCloudInstance
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientId
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientName
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.ClientSecret
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.ClientVersion
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.Component
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.EnableCacheSynchronization
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.Instance
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.IsDefaultPlatformLoggingEnabled
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.LegacyCacheCompatibilityEnabled
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.LogLevel
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.RedirectUri
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.TenantId
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ApplicationOptions.TicketContainer
  inheritedFrom: Microsoft.Identity.Client.ApplicationOptions
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions
commentId: T:Microsoft.Identity.Client.ConfidentialClientApplicationOptions
namespace: Microsoft.Identity.Client
name: ConfidentialClientApplicationOptions
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationOptions
nameWithType: Microsoft.Identity.Client.ConfidentialClientApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class ConfidentialClientApplicationOptions : Microsoft.Identity.Client.ApplicationOptions'
- lang: fsharp
  values:
  - value: >-
      type ConfidentialClientApplicationOptions = class
          inherit ApplicationOptions
- lang: vb
  values:
  - value: >-
      Public Class ConfidentialClientApplicationOptions

      Inherits ApplicationOptions
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Configuration options for a confidential client application

  (web app / web API / daemon app). See https://aka.ms/msal-net/application-configuration
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions
  - Microsoft::Identity::Client::ConfidentialClientApplicationOptions
  - ConfidentialClientApplicationOptions
  helpviewer_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions class [.NET]
  monikers:
  - msal-dotnet-latest
