### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  name: ClientId
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  nameWithType: IdentityApplicationOptions.ClientId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? ClientId { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ClientId : string with get, set'
  - lang: vb
    values:
    - value: Public Property ClientId As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Gets or sets the 'client_id' (application ID) as it appears in the 

    application registration. This is the string representation of a GUID.
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
namespace: Microsoft.Identity.Abstractions
name: ClientId
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
nameWithType: IdentityApplicationOptions.ClientId
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_ClientId
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_ClientId
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.ClientId
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::ClientId
  - ClientId
  - IdentityApplicationOptions.ClientId
  - IdentityApplicationOptions::ClientId
  helpviewer_keywords:
  - IdentityApplicationOptions.ClientId property [.NET]
  - ClientId property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
