### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultRefreshInterval
  commentId: F:Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultRefreshInterval
  name: DefaultRefreshInterval
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.DefaultRefreshInterval
  nameWithType: ConfigurationManager<T>.DefaultRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan DefaultRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable DefaultRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly DefaultRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 5 minutes is the default time interval that must pass for <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh"></xref> to obtain a new configuration.
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.DefaultRefreshInterval
  - Microsoft::IdentityModel::Protocols::ConfigurationManager`1::DefaultRefreshInterval
  - Microsoft.IdentityModel.Protocols.ConfigurationManager.DefaultRefreshInterval
  - DefaultRefreshInterval
  - ConfigurationManager`1.DefaultRefreshInterval
  - ConfigurationManager`1::DefaultRefreshInterval
  helpviewer_keywords:
  - ConfigurationManager<T>.DefaultRefreshInterval field [.NET]
  - DefaultRefreshInterval field [.NET], class ConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
