### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  name: MetadataAddress
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  nameWithType: BaseConfigurationManager.MetadataAddress
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string MetadataAddress { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.MetadataAddress : string with get, set'
  - lang: vb
    values:
    - value: Public Property MetadataAddress As String
  monikers:
  - msal-web-dotnet-latest
  summary: The metadata address to retrieve the configuration from.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
namespace: Microsoft.IdentityModel.Tokens
name: MetadataAddress
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
nameWithType: BaseConfigurationManager.MetadataAddress
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_MetadataAddress
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_MetadataAddress
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.MetadataAddress
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::MetadataAddress
  - MetadataAddress
  - BaseConfigurationManager.MetadataAddress
  - BaseConfigurationManager::MetadataAddress
  helpviewer_keywords:
  - BaseConfigurationManager.MetadataAddress property [.NET]
  - MetadataAddress property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
