### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  name: Domain
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  nameWithType: MicrosoftIdentityApplicationOptions.Domain
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? Domain { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Domain : string with get, set'
  - lang: vb
    values:
    - value: Public Property Domain As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the domain of the Azure Active Directory tenant, e.g. contoso.onmicrosoft.com.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
namespace: Microsoft.Identity.Abstractions
name: Domain
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
nameWithType: MicrosoftIdentityApplicationOptions.Domain
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_Domain
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_Domain
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Domain
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::Domain
  - Domain
  - MicrosoftIdentityApplicationOptions.Domain
  - MicrosoftIdentityApplicationOptions::Domain
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.Domain property [.NET]
  - Domain property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
