### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  commentId: P:Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  name: RequiredAppPermissionsConfigurationKey
  fullName: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  nameWithType: RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredAppPermissionsConfigurationKey { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredAppPermissionsConfigurationKey : string with get, set'
  - lang: vb
    values:
    - value: Public Property RequiredAppPermissionsConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Fully qualified name of the configuration key containing the required app permissions (separated

    by spaces).
  examples: >-
    If the appsettings.json file contains a section named "AzureAd", in which

    a property named "AppPermissions" contains the required app permissions, the attribute on the

    controller/page/action to protect should be set to the following:


    ```

    [RequiredScopeOrAppPermission(RequiredAppPermissionsConfigurationKey="AzureAd:AppPermissions")]

    ```
  metadata: {}
uid: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
namespace: Microsoft.Identity.Web.Resource
name: RequiredAppPermissionsConfigurationKey
fullName: Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
nameWithType: RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.get_RequiredAppPermissionsConfigurationKey
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.set_RequiredAppPermissionsConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.Resource.RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  - Microsoft::Identity::Web::Resource::RequiredScopeOrAppPermissionAttribute::RequiredAppPermissionsConfigurationKey
  - RequiredAppPermissionsConfigurationKey
  - RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey
  - RequiredScopeOrAppPermissionAttribute::RequiredAppPermissionsConfigurationKey
  helpviewer_keywords:
  - RequiredScopeOrAppPermissionAttribute.RequiredAppPermissionsConfigurationKey property [.NET]
  - RequiredAppPermissionsConfigurationKey property [.NET], class RequiredScopeOrAppPermissionAttribute
  monikers:
  - msal-model-dotnet-latest
