### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.ClientId
  commentId: P:Microsoft.Identity.Client.IAppConfig.ClientId
  name: ClientId
  fullName: Microsoft.Identity.Client.IAppConfig.ClientId
  nameWithType: IAppConfig.ClientId
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string ClientId { get; }
  - lang: fsharp
    values:
    - value: 'member this.ClientId : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property ClientId As String
  monikers:
  - msal-dotnet-latest
  summary: >-
    Client ID (also known as App ID) of the application as registered in the

    application registration portal (https://aka.ms/msal-net-register-app).
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.ClientId*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.ClientId
namespace: Microsoft.Identity.Client
name: ClientId
fullName: Microsoft.Identity.Client.IAppConfig.ClientId
nameWithType: IAppConfig.ClientId
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.ClientId
  - Microsoft.Identity.Client.IAppConfig.get_ClientId
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.ClientId
  - Microsoft::Identity::Client::IAppConfig::ClientId
  - ClientId
  - IAppConfig.ClientId
  - IAppConfig::ClientId
  helpviewer_keywords:
  - IAppConfig.ClientId property [.NET]
  - ClientId property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
