### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  name: GrantTypesSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  nameWithType: OpenIdConnectConfiguration.GrantTypesSupported
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="grant_types_supported", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public System.Collections.Generic.ICollection<string> GrantTypesSupported { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="grant_types_supported", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.GrantTypesSupported : System.Collections.Generic.ICollection<string>
  - lang: vb
    values:
    - value: Public ReadOnly Property GrantTypesSupported As ICollection(Of String)
  monikers:
  - msal-web-dotnet-latest
  summary: Gets the collection of 'grant_types_supported'
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: GrantTypesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
nameWithType: OpenIdConnectConfiguration.GrantTypesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_GrantTypesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.GrantTypesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::GrantTypesSupported
  - GrantTypesSupported
  - OpenIdConnectConfiguration.GrantTypesSupported
  - OpenIdConnectConfiguration::GrantTypesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.GrantTypesSupported property [.NET]
  - GrantTypesSupported property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
