### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  name: AuthorizationEndpoint
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  nameWithType: OpenIdConnectConfiguration.AuthorizationEndpoint
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="authorization_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string AuthorizationEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="authorization_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.AuthorizationEndpoint : string with get, set
  - lang: vb
    values:
    - value: Public Property AuthorizationEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'authorization_endpoint'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: AuthorizationEndpoint
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
nameWithType: OpenIdConnectConfiguration.AuthorizationEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_AuthorizationEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_AuthorizationEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AuthorizationEndpoint
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::AuthorizationEndpoint
  - AuthorizationEndpoint
  - OpenIdConnectConfiguration.AuthorizationEndpoint
  - OpenIdConnectConfiguration::AuthorizationEndpoint
  helpviewer_keywords:
  - OpenIdConnectConfiguration.AuthorizationEndpoint property [.NET]
  - AuthorizationEndpoint property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
