### YamlMime:NetNamespace
classes:
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.AppConfig
commentId: N:Microsoft.Identity.Client.AppConfig
name: Microsoft.Identity.Client.AppConfig
fullName: Microsoft.Identity.Client.AppConfig
devLangs:
- csharp
monikers:
- msal-dotnet-latest
metadata:
  f1_keywords:
  - Microsoft.Identity.Client.AppConfig
  - Microsoft::Identity::Client::AppConfig
  - AppConfig
  - Client.AppConfig
  - Client::AppConfig
  helpviewer_keywords:
  - Microsoft.Identity.Client.AppConfig namespace [.NET]
  monikers:
  - msal-dotnet-latest
