### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.AadAuthorityAudience?alt=Microsoft.Identity.Client.AadAuthorityAudience&text=AadAuthorityAudience" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  name: AadAuthorityAudience
  fullName: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  nameWithType: ApplicationOptions.AadAuthorityAudience
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.AadAuthorityAudience AadAuthorityAudience { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.AadAuthorityAudience : Microsoft.Identity.Client.AadAuthorityAudience with get, set'
  - lang: vb
    values:
    - value: Public Property AadAuthorityAudience As AadAuthorityAudience
  monikers:
  - msal-dotnet-latest
  summary: >-
    Sign-in audience. This property is mutually exclusive with TenantId. If both

    are provided, an exception will be thrown.
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
namespace: Microsoft.Identity.Client
name: AadAuthorityAudience
fullName: Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
nameWithType: ApplicationOptions.AadAuthorityAudience
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  - Microsoft.Identity.Client.ApplicationOptions.get_AadAuthorityAudience
  - Microsoft.Identity.Client.ApplicationOptions.set_AadAuthorityAudience
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.AadAuthorityAudience
  - Microsoft::Identity::Client::ApplicationOptions::AadAuthorityAudience
  - AadAuthorityAudience
  - ApplicationOptions.AadAuthorityAudience
  - ApplicationOptions::AadAuthorityAudience
  helpviewer_keywords:
  - ApplicationOptions.AadAuthorityAudience property [.NET]
  - AadAuthorityAudience property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
