### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>
    description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> object representing the configuration.
  parameters:
  - namesWithMoniker:
    - value: json
    description: json string representing the configuration.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: If 'json' is null or empty.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  - description: If 'json' fails to deserialize.
    type: <xref href="System.ArgumentException" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create(System.String)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create(System.String)
  name: Create(String)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create(String)
  nameWithType: OpenIdConnectConfiguration.Create(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration Create (string json);
  - lang: fsharp
    values:
    - value: 'static member Create : string -> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration'
  - lang: vb
    values:
    - value: Public Shared Function Create (json As String) As OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: Deserializes the json string into an <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> object.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: Create
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create
nameWithType: OpenIdConnectConfiguration.Create
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Create
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::Create
  - Create
  - OpenIdConnectConfiguration.Create
  - OpenIdConnectConfiguration::Create
  helpviewer_keywords:
  - OpenIdConnectConfiguration.Create method [.NET]
  - Create method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.Create(String) method [.NET]
  - Create(String) method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
