### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Net.Http.HttpRequestMessage)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Uri)
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.HttpHost
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.HttpMethod
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.HttpPath
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PopCryptoProvider
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.SignHttpRequest
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
commentId: T:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
namespace: Microsoft.Identity.Client.AppConfig
name: PoPAuthenticationConfiguration
fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
nameWithType: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public class PoPAuthenticationConfiguration
- lang: fsharp
  values:
  - value: type PoPAuthenticationConfiguration = class
- lang: vb
  values:
  - value: Public Class PoPAuthenticationConfiguration
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: Details about the HTTP request and configuration properties used to construct a proof of possession request.
remarks: <p>POP tokens are signed by the process making the request. By default, MSAL will generate a key in memory. To use a hardware key or an external key, implement <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PopCryptoProvider"></xref>.</p>
metadata:
  api_name:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration
  - Microsoft::Identity::Client::AppConfig::PoPAuthenticationConfiguration
  - PoPAuthenticationConfiguration
  helpviewer_keywords:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration class [.NET]
  monikers:
  - msal-dotnet-latest
