### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  name: Audiences
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  nameWithType: IdentityApplicationOptions.Audiences
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<string>? Audiences { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Audiences : seq<string> with get, set'
  - lang: vb
    values:
    - value: Public Property Audiences As IEnumerable(Of String)
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    In a web API, accepted audiences for the tokens received by the web API.

    <p>See also <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audience"></xref>.</p>
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
namespace: Microsoft.Identity.Abstractions
name: Audiences
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
nameWithType: IdentityApplicationOptions.Audiences
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_Audiences
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_Audiences
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Audiences
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::Audiences
  - Audiences
  - IdentityApplicationOptions.Audiences
  - IdentityApplicationOptions::Audiences
  helpviewer_keywords:
  - IdentityApplicationOptions.Audiences property [.NET]
  - Audiences property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
