### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  commentId: F:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  name: IdTokenSigningAlgValuesSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  nameWithType: OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public const string IdTokenSigningAlgValuesSupported;
  - lang: fsharp
    values:
    - value: 'val mutable IdTokenSigningAlgValuesSupported : string'
  - lang: vb
    values:
    - value: 'Public Const IdTokenSigningAlgValuesSupported As String '
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdProviderMetadataNames::IdTokenSigningAlgValuesSupported
  - IdTokenSigningAlgValuesSupported
  - OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported
  - OpenIdProviderMetadataNames::IdTokenSigningAlgValuesSupported
  helpviewer_keywords:
  - OpenIdProviderMetadataNames.IdTokenSigningAlgValuesSupported field [.NET]
  - IdTokenSigningAlgValuesSupported field [.NET], class OpenIdProviderMetadataNames
  monikers:
  - msal-web-dotnet-latest
