### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.DisplayValuesSupported
  commentId: F:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.DisplayValuesSupported
  name: DisplayValuesSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.DisplayValuesSupported
  nameWithType: OpenIdProviderMetadataNames.DisplayValuesSupported
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public const string DisplayValuesSupported;
  - lang: fsharp
    values:
    - value: 'val mutable DisplayValuesSupported : string'
  - lang: vb
    values:
    - value: 'Public Const DisplayValuesSupported As String '
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.DisplayValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.DisplayValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdProviderMetadataNames::DisplayValuesSupported
  - DisplayValuesSupported
  - OpenIdProviderMetadataNames.DisplayValuesSupported
  - OpenIdProviderMetadataNames::DisplayValuesSupported
  helpviewer_keywords:
  - OpenIdProviderMetadataNames.DisplayValuesSupported field [.NET]
  - DisplayValuesSupported field [.NET], class OpenIdProviderMetadataNames
  monikers:
  - msal-web-dotnet-latest
