### YamlMime:NetType
type: interface
implementsWithMoniker:
- value: <xref href="Microsoft.Identity.Client.IClientApplicationBase?alt=Microsoft.Identity.Client.IClientApplicationBase&text=IClientApplicationBase" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.PublicClientApplication
extensionMethods:
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsEmbeddedWebViewAvailable(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsSystemWebViewAvailable(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.IsUserInteractive(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationExtensions.IsProofOfPossessionSupportedByClient(Microsoft.Identity.Client.IPublicClientApplication)
  monikers:
  - msal-dotnet-latest
methods:
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.Prompt,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.Prompt,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String,Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UIParent)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByIntegratedWindowsAuth(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByIntegratedWindowsAuthAsync(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByIntegratedWindowsAuthAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByUsernamePassword(System.Collections.Generic.IEnumerable{System.String},System.String,System.Security.SecureString)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByUsernamePassword(System.Collections.Generic.IEnumerable{System.String},System.String,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenByUsernamePasswordAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Security.SecureString)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenInteractive(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenWithDeviceCode(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task},System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task},System.Threading.CancellationToken)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.AcquireTokenWithDeviceCodeAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.Func{Microsoft.Identity.Client.DeviceCodeResult,System.Threading.Tasks.Task})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetUser(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Remove(Microsoft.Identity.Client.IUser)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.IClientApplicationBase.AppConfig
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Authority
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ClientId
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Component
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RedirectUri
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.SliceParameters
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Users
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.IPublicClientApplication
commentId: T:Microsoft.Identity.Client.IPublicClientApplication
namespace: Microsoft.Identity.Client
name: IPublicClientApplication
fullName: Microsoft.Identity.Client.IPublicClientApplication
nameWithType: Microsoft.Identity.Client.IPublicClientApplication
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public interface IPublicClientApplication : Microsoft.Identity.Client.IClientApplicationBase'
- lang: fsharp
  values:
  - value: >-
      type IPublicClientApplication = interface
          interface IClientApplicationBase
- lang: vb
  values:
  - value: >-
      Public Interface IPublicClientApplication

      Implements IClientApplicationBase
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Interface to be used with desktop or mobile applications (Desktop / UWP / Xamarin.iOS / Xamarin.Android).

  public client applications are not trusted to safely keep application secrets, and therefore they only access web APIs in the name of the user only.

  For details see https://aka.ms/msal-net-client-applications.
metadata:
  api_name:
  - Microsoft.Identity.Client.IPublicClientApplication
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IPublicClientApplication
  - Microsoft::Identity::Client::IPublicClientApplication
  - IPublicClientApplication
  helpviewer_keywords:
  - Microsoft.Identity.Client.IPublicClientApplication interface [.NET]
  monikers:
  - msal-dotnet-latest
