### YamlMime:NetMember
type: method
members:
- type: method
  uid: Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
  commentId: M:Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
  name: RequestRefresh()
  fullName: Microsoft.IdentityModel.Protocols.IConfigurationManager<T>.RequestRefresh()
  nameWithType: IConfigurationManager<T>.RequestRefresh()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public void RequestRefresh ();
  - lang: fsharp
    values:
    - value: 'abstract member RequestRefresh : unit -> unit'
  - lang: vb
    values:
    - value: Public Sub RequestRefresh ()
  monikers:
  - msal-web-dotnet-latest
  summary: Indicate that the configuration may be stale (as indicated by failing to process incoming tokens).
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh*
commentId: Overload:Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
namespace: Microsoft.IdentityModel.Protocols
name: RequestRefresh
fullName: Microsoft.IdentityModel.Protocols.IConfigurationManager<T>.RequestRefresh
nameWithType: IConfigurationManager<T>.RequestRefresh
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
  - Microsoft::IdentityModel::Protocols::IConfigurationManager`1::RequestRefresh
  - Microsoft.IdentityModel.Protocols.IConfigurationManager.RequestRefresh
  - RequestRefresh
  - IConfigurationManager`1.RequestRefresh
  - IConfigurationManager`1::RequestRefresh
  helpviewer_keywords:
  - IConfigurationManager<T>.RequestRefresh method [.NET]
  - RequestRefresh method [.NET], interface IConfigurationManager<T>
  - IConfigurationManager<T>.RequestRefresh() method [.NET]
  - RequestRefresh() method [.NET], interface IConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
