### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  name: LastKnownGoodLifetime
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  nameWithType: BaseConfigurationManager.LastKnownGoodLifetime
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public TimeSpan LastKnownGoodLifetime { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.LastKnownGoodLifetime : TimeSpan with get, set'
  - lang: vb
    values:
    - value: Public Property LastKnownGoodLifetime As TimeSpan
  monikers:
  - msal-web-dotnet-latest
  summary: The length of time that a last known good configuration is valid for.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
namespace: Microsoft.IdentityModel.Tokens
name: LastKnownGoodLifetime
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
nameWithType: BaseConfigurationManager.LastKnownGoodLifetime
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_LastKnownGoodLifetime
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_LastKnownGoodLifetime
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.LastKnownGoodLifetime
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::LastKnownGoodLifetime
  - LastKnownGoodLifetime
  - BaseConfigurationManager.LastKnownGoodLifetime
  - BaseConfigurationManager::LastKnownGoodLifetime
  helpviewer_keywords:
  - BaseConfigurationManager.LastKnownGoodLifetime property [.NET]
  - LastKnownGoodLifetime property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
