### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor
  commentId: M:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor
  name: BaseConfigurationManager()
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.BaseConfigurationManager()
  nameWithType: BaseConfigurationManager.BaseConfigurationManager()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected BaseConfigurationManager ();
  - lang: vb
    values:
    - value: Protected Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor
namespace: Microsoft.IdentityModel.Tokens
name: BaseConfigurationManager
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.BaseConfigurationManager
nameWithType: BaseConfigurationManager.BaseConfigurationManager
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager..ctor
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.#ctor
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::#ctor
  - '#ctor'
  - BaseConfigurationManager.#ctor
  - BaseConfigurationManager::#ctor
  helpviewer_keywords:
  - BaseConfigurationManager class [.NET], constructors
  - BaseConfigurationManager() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
