### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.PublicClientApplicationBuilder?alt=Microsoft.Identity.Client.PublicClientApplicationBuilder&text=PublicClientApplicationBuilder" data-throw-if-not-resolved="True"/>
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: windowFunc
    description: A function to return the current window
    type: <xref href="System.Func`1?alt=System.Func&text=Func" data-throw-if-not-resolved="True"/>&lt;<xref href="System.IntPtr?alt=System.IntPtr&text=IntPtr" data-throw-if-not-resolved="True"/>&gt;
    typePerLanguage:
    - value: <xref href="System.Func`1?alt=System.Func&text=Func" data-throw-if-not-resolved="True"/>&lt;<xref href="System.IntPtr?alt=System.IntPtr&text=IntPtr" data-throw-if-not-resolved="True"/>&gt;
      langs:
      - csharp
      - vb
    - value: <xref href="System.Func`1?alt=System.Func&text=Func" data-throw-if-not-resolved="True"/>&lt;nativeint&gt;
      langs:
      - fsharp
  isNotClsCompliant: true
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.IntPtr})
  commentId: M:Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.IntPtr})
  name: WithParentActivityOrWindow(Func<IntPtr>)
  fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<IntPtr>)
  nameWithType: PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<IntPtr>)
  attributesWithMoniker:
  - value: System.CLSCompliantAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.CLSCompliant(false)]

        public Microsoft.Identity.Client.PublicClientApplicationBuilder WithParentActivityOrWindow (Func<IntPtr> windowFunc);
  - lang: fsharp
    values:
    - value: >-
        [<System.CLSCompliant(false)>]

        member this.WithParentActivityOrWindow : Func<nativeint> -> Microsoft.Identity.Client.PublicClientApplicationBuilder
  - lang: vb
    values:
    - value: Public Function WithParentActivityOrWindow (windowFunc As Func(Of IntPtr)) As PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: >-
    Sets a reference to the IntPtr to a window that triggers the browser to be shown.

    Used to center the browser that pop-up onto this window.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.PublicClientApplicationBuilder?alt=Microsoft.Identity.Client.PublicClientApplicationBuilder&text=PublicClientApplicationBuilder" data-throw-if-not-resolved="True"/>
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: parentActivityOrWindowFunc
    description: The parent as an object, so that it can be used from shared NetStandard assemblies
    type: <xref href="System.Func`1?alt=System.Func&text=Func" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>&gt;
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.Object})
  commentId: M:Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.Object})
  name: WithParentActivityOrWindow(Func<Object>)
  fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<Object>)
  nameWithType: PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<Object>)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.PublicClientApplicationBuilder WithParentActivityOrWindow (Func<object> parentActivityOrWindowFunc);
  - lang: fsharp
    values:
    - value: 'member this.WithParentActivityOrWindow : Func<obj> -> Microsoft.Identity.Client.PublicClientApplicationBuilder'
  - lang: vb
    values:
    - value: Public Function WithParentActivityOrWindow (parentActivityOrWindowFunc As Func(Of Object)) As PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: >-
    Sets a reference to the ViewController (if using Xamarin.iOS), Activity (if using Xamarin.Android)

    IWin32Window or IntPtr (if using .Net Framework). Used for invoking the browser.
  remarks: <p>Mandatory only on Android to be set either from here or from AcquireTokenInteractive builder. See https://aka.ms/msal-net-android-activity for further documentation and details.</p>
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow
namespace: Microsoft.Identity.Client
name: WithParentActivityOrWindow
fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow
nameWithType: PublicClientApplicationBuilder.WithParentActivityOrWindow
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow
  - Microsoft::Identity::Client::PublicClientApplicationBuilder::WithParentActivityOrWindow
  - WithParentActivityOrWindow
  - PublicClientApplicationBuilder.WithParentActivityOrWindow
  - PublicClientApplicationBuilder::WithParentActivityOrWindow
  helpviewer_keywords:
  - PublicClientApplicationBuilder.WithParentActivityOrWindow method [.NET]
  - WithParentActivityOrWindow method [.NET], class PublicClientApplicationBuilder
  - PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<IntPtr>) method [.NET]
  - WithParentActivityOrWindow(Func<IntPtr>) method [.NET], class PublicClientApplicationBuilder
  - PublicClientApplicationBuilder.WithParentActivityOrWindow(Func<Object>) method [.NET]
  - WithParentActivityOrWindow(Func<Object>) method [.NET], class PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
