### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Int32?alt=System.Int32&text=Int32" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  name: MinimumNumberOfKeys
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  nameWithType: OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public int MinimumNumberOfKeys { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.MinimumNumberOfKeys : int with get, set'
  - lang: vb
    values:
    - value: Public Property MinimumNumberOfKeys As Integer
  monikers:
  - msal-web-dotnet-latest
  summary: The minimum number of keys.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
name: MinimumNumberOfKeys
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
nameWithType: OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.get_MinimumNumberOfKeys
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.set_MinimumNumberOfKeys
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::Configuration::OpenIdConnectConfigurationValidator::MinimumNumberOfKeys
  - MinimumNumberOfKeys
  - OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  - OpenIdConnectConfigurationValidator::MinimumNumberOfKeys
  helpviewer_keywords:
  - OpenIdConnectConfigurationValidator.MinimumNumberOfKeys property [.NET]
  - MinimumNumberOfKeys property [.NET], class OpenIdConnectConfigurationValidator
  monikers:
  - msal-web-dotnet-latest
