### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;T&gt;
  parameters:
  - namesWithMoniker:
    - value: address
    description: Address of the discovery document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: retriever
    description: The <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref> to use to read the discovery document.
    type: <xref href="Microsoft.IdentityModel.Protocols.IDocumentRetriever?alt=Microsoft.IdentityModel.Protocols.IDocumentRetriever&text=IDocumentRetriever" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: A cancellation token that can be used by other objects or threads to receive notice of cancellation. <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  name: GetConfigurationAsync(String, IDocumentRetriever, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.IConfigurationRetriever<T>.GetConfigurationAsync(String, IDocumentRetriever, CancellationToken)
  nameWithType: IConfigurationRetriever<T>.GetConfigurationAsync(String, IDocumentRetriever, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<T> GetConfigurationAsync (string address, Microsoft.IdentityModel.Protocols.IDocumentRetriever retriever, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: "abstract member GetConfigurationAsync : string * Microsoft.IdentityModel.Protocols.IDocumentRetriever * System.Threading.CancellationToken -> System.Threading.Tasks.Task<'T>"
  - lang: vb
    values:
    - value: Public Function GetConfigurationAsync (address As String, retriever As IDocumentRetriever, cancel As CancellationToken) As Task(Of T)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated configuration given an address and an <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref>.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync*
commentId: Overload:Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync
namespace: Microsoft.IdentityModel.Protocols
name: GetConfigurationAsync
fullName: Microsoft.IdentityModel.Protocols.IConfigurationRetriever<T>.GetConfigurationAsync
nameWithType: IConfigurationRetriever<T>.GetConfigurationAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync
  - Microsoft::IdentityModel::Protocols::IConfigurationRetriever`1::GetConfigurationAsync
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever.GetConfigurationAsync
  - GetConfigurationAsync
  - IConfigurationRetriever`1.GetConfigurationAsync
  - IConfigurationRetriever`1::GetConfigurationAsync
  helpviewer_keywords:
  - IConfigurationRetriever<T>.GetConfigurationAsync method [.NET]
  - GetConfigurationAsync method [.NET], interface IConfigurationRetriever<T>
  - IConfigurationRetriever<T>.GetConfigurationAsync(String, IDocumentRetriever, CancellationToken) method [.NET]
  - GetConfigurationAsync(String, IDocumentRetriever, CancellationToken) method [.NET], interface IConfigurationRetriever<T>
  monikers:
  - msal-web-dotnet-latest
