### YamlMime:NetType
typeParameters:
- description: The type of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref>.
  name: T
type: interface
derivedClassesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.ConfigurationManager`1
- value: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1
methods:
- uid: Microsoft.IdentityModel.Protocols.IConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.IConfigurationManager`1
commentId: T:Microsoft.IdentityModel.Protocols.IConfigurationManager`1
namespace: Microsoft.IdentityModel.Protocols
name: IConfigurationManager<T>
fullName: Microsoft.IdentityModel.Protocols.IConfigurationManager<T>
nameWithType: Microsoft.IdentityModel.Protocols.IConfigurationManager<T>
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public interface IConfigurationManager<T> where T : class'
- lang: fsharp
  values:
  - value: "type IConfigurationManager<'T (requires 'T : null)> = interface"
- lang: vb
  values:
  - value: Public Interface IConfigurationManager(Of T)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Interface that defines a model for retrieving configuration data.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationManager`1
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationManager`1
  - Microsoft::IdentityModel::Protocols::IConfigurationManager`1
  - Microsoft.IdentityModel.Protocols.IConfigurationManager
  - IConfigurationManager`1
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationManager<T> interface [.NET]
  monikers:
  - msal-web-dotnet-latest
