### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  name: CheckSessionIframe
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  nameWithType: OpenIdConnectConfiguration.CheckSessionIframe
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="check_session_iframe", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string CheckSessionIframe { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="check_session_iframe", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.CheckSessionIframe : string with get, set
  - lang: vb
    values:
    - value: Public Property CheckSessionIframe As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'check_session_iframe'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: CheckSessionIframe
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
nameWithType: OpenIdConnectConfiguration.CheckSessionIframe
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_CheckSessionIframe
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_CheckSessionIframe
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.CheckSessionIframe
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::CheckSessionIframe
  - CheckSessionIframe
  - OpenIdConnectConfiguration.CheckSessionIframe
  - OpenIdConnectConfiguration::CheckSessionIframe
  helpviewer_keywords:
  - OpenIdConnectConfiguration.CheckSessionIframe property [.NET]
  - CheckSessionIframe property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
