### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  name: TokenEndpointAuthMethodsSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  nameWithType: OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="token_endpoint_auth_methods_supported", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public System.Collections.Generic.ICollection<string> TokenEndpointAuthMethodsSupported { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="token_endpoint_auth_methods_supported", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.TokenEndpointAuthMethodsSupported : System.Collections.Generic.ICollection<string>
  - lang: vb
    values:
    - value: Public ReadOnly Property TokenEndpointAuthMethodsSupported As ICollection(Of String)
  monikers:
  - msal-web-dotnet-latest
  summary: Gets the collection of 'token_endpoint_auth_methods_supported'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: TokenEndpointAuthMethodsSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
nameWithType: OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_TokenEndpointAuthMethodsSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::TokenEndpointAuthMethodsSupported
  - TokenEndpointAuthMethodsSupported
  - OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported
  - OpenIdConnectConfiguration::TokenEndpointAuthMethodsSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.TokenEndpointAuthMethodsSupported property [.NET]
  - TokenEndpointAuthMethodsSupported property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
