### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Security.Cryptography.X509Certificates.X509Certificate2?alt=System.Security.Cryptography.X509Certificates.X509Certificate2&text=X509Certificate2" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
  commentId: P:Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
  name: Certificate
  fullName: Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
  nameWithType: ConfidentialClientApplication.Certificate
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Security.Cryptography.X509Certificates.X509Certificate2 Certificate { get; }
  - lang: fsharp
    values:
    - value: 'member this.Certificate : System.Security.Cryptography.X509Certificates.X509Certificate2'
  - lang: vb
    values:
    - value: Public ReadOnly Property Certificate As X509Certificate2
  monikers:
  - msal-dotnet-latest
  summary: The certificate used to create this <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ConfidentialClientApplication"></xref>, if any.
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplication.Certificate*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
namespace: Microsoft.Identity.Client
name: Certificate
fullName: Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
nameWithType: ConfidentialClientApplication.Certificate
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
  - Microsoft.Identity.Client.ConfidentialClientApplication.get_Certificate
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplication.Certificate
  - Microsoft::Identity::Client::ConfidentialClientApplication::Certificate
  - Certificate
  - ConfidentialClientApplication.Certificate
  - ConfidentialClientApplication::Certificate
  helpviewer_keywords:
  - ConfidentialClientApplication.Certificate property [.NET]
  - Certificate property [.NET], class ConfidentialClientApplication
  monikers:
  - msal-dotnet-latest
