### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
    description: json string representing the configuration object.
  parameters:
  - namesWithMoniker:
    - value: configuration
    description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> object to serialize.
    type: <xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: If 'configuration' is null.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  name: Write(OpenIdConnectConfiguration)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write(OpenIdConnectConfiguration)
  nameWithType: OpenIdConnectConfiguration.Write(OpenIdConnectConfiguration)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static string Write (Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration configuration);
  - lang: fsharp
    values:
    - value: 'static member Write : Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration -> string'
  - lang: vb
    values:
    - value: Public Shared Function Write (configuration As OpenIdConnectConfiguration) As String
  monikers:
  - msal-web-dotnet-latest
  summary: Serializes the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> object to a json string.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: Write
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write
nameWithType: OpenIdConnectConfiguration.Write
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Write
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::Write
  - Write
  - OpenIdConnectConfiguration.Write
  - OpenIdConnectConfiguration::Write
  helpviewer_keywords:
  - OpenIdConnectConfiguration.Write method [.NET]
  - Write method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.Write(OpenIdConnectConfiguration) method [.NET]
  - Write(OpenIdConnectConfiguration) method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
