### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ITelemetryConfig?alt=Microsoft.Identity.Client.ITelemetryConfig&text=ITelemetryConfig" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  commentId: P:Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  name: TelemetryConfig
  fullName: Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  nameWithType: IAppConfig.TelemetryConfig
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)]

        public Microsoft.Identity.Client.ITelemetryConfig TelemetryConfig { get; }
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)>]

        member this.TelemetryConfig : Microsoft.Identity.Client.ITelemetryConfig
  - lang: vb
    values:
    - value: Public ReadOnly Property TelemetryConfig As ITelemetryConfig
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.TelemetryConfig*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.TelemetryConfig
namespace: Microsoft.Identity.Client
name: TelemetryConfig
fullName: Microsoft.Identity.Client.IAppConfig.TelemetryConfig
nameWithType: IAppConfig.TelemetryConfig
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  - Microsoft.Identity.Client.IAppConfig.get_TelemetryConfig
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  - Microsoft::Identity::Client::IAppConfig::TelemetryConfig
  - TelemetryConfig
  - IAppConfig.TelemetryConfig
  - IAppConfig::TelemetryConfig
  helpviewer_keywords:
  - IAppConfig.TelemetryConfig property [.NET]
  - TelemetryConfig property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
