### YamlMime:NetMember
type: method
members:
- implementsWithMoniker:
  - value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh?alt=Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh&text=RequestRefresh()" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
  commentId: M:Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
  name: RequestRefresh()
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.RequestRefresh()
  nameWithType: ConfigurationManager<T>.RequestRefresh()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public override void RequestRefresh ();
  - lang: fsharp
    values:
    - value: 'override this.RequestRefresh : unit -> unit'
  - lang: vb
    values:
    - value: Public Overrides Sub RequestRefresh ()
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Requests that then next call to <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync"></xref> obtain new configuration.

    <p>If it is a first force refresh or the last refresh was greater than <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval"></xref> then the next call to <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync"></xref> will retrieve new configuration.</p><p>If <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval"></xref> == <xref data-throw-if-not-resolved="true" uid="System.TimeSpan.MaxValue"></xref> then this method does nothing.</p>
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh*
commentId: Overload:Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
namespace: Microsoft.IdentityModel.Protocols
name: RequestRefresh
fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.RequestRefresh
nameWithType: ConfigurationManager<T>.RequestRefresh
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.RequestRefresh
  - Microsoft::IdentityModel::Protocols::ConfigurationManager`1::RequestRefresh
  - Microsoft.IdentityModel.Protocols.ConfigurationManager.RequestRefresh
  - RequestRefresh
  - ConfigurationManager`1.RequestRefresh
  - ConfigurationManager`1::RequestRefresh
  helpviewer_keywords:
  - ConfigurationManager<T>.RequestRefresh method [.NET]
  - RequestRefresh method [.NET], class ConfigurationManager<T>
  - ConfigurationManager<T>.RequestRefresh() method [.NET]
  - RequestRefresh() method [.NET], class ConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
