### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  commentId: F:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  name: RequestObjectEncryptionEncValuesSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  nameWithType: OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public const string RequestObjectEncryptionEncValuesSupported;
  - lang: fsharp
    values:
    - value: 'val mutable RequestObjectEncryptionEncValuesSupported : string'
  - lang: vb
    values:
    - value: 'Public Const RequestObjectEncryptionEncValuesSupported As String '
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdProviderMetadataNames::RequestObjectEncryptionEncValuesSupported
  - RequestObjectEncryptionEncValuesSupported
  - OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported
  - OpenIdProviderMetadataNames::RequestObjectEncryptionEncValuesSupported
  helpviewer_keywords:
  - OpenIdProviderMetadataNames.RequestObjectEncryptionEncValuesSupported field [.NET]
  - RequestObjectEncryptionEncValuesSupported field [.NET], class OpenIdProviderMetadataNames
  monikers:
  - msal-web-dotnet-latest
