### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  name: ResetPasswordPath
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  nameWithType: MicrosoftIdentityApplicationOptions.ResetPasswordPath
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? ResetPasswordPath { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ResetPasswordPath : string with get, set'
  - lang: vb
    values:
    - value: Public Property ResetPasswordPath As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Sets the ResetPassword route path (from the root of the web site).

    Defaults to /MicrosoftIdentity/Account/ResetPassword,

    which is the value used by Microsoft.Identity.Web.UI.

    If you override it, you need to provide your own controller/actions.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
namespace: Microsoft.Identity.Abstractions
name: ResetPasswordPath
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
nameWithType: MicrosoftIdentityApplicationOptions.ResetPasswordPath
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_ResetPasswordPath
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_ResetPasswordPath
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ResetPasswordPath
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::ResetPasswordPath
  - ResetPasswordPath
  - MicrosoftIdentityApplicationOptions.ResetPasswordPath
  - MicrosoftIdentityApplicationOptions::ResetPasswordPath
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.ResetPasswordPath property [.NET]
  - ResetPasswordPath property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
