### YamlMime:NetType
type: interface
properties:
- uid: Microsoft.Identity.Client.IAppConfig.ClientCapabilities
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ClientCredentialCertificate
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ClientId
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ClientName
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ClientSecret
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ClientVersion
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.EnablePiiLogging
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ExperimentalFeaturesEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ExtraQueryParameters
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.HttpClientFactory
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.IsBrokerEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.LegacyCacheCompatibilityEnabled
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.LoggingCallback
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.LogLevel
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.RedirectUri
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.TelemetryConfig
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IAppConfig.TenantId
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.IAppConfig
commentId: T:Microsoft.Identity.Client.IAppConfig
namespace: Microsoft.Identity.Client
name: IAppConfig
fullName: Microsoft.Identity.Client.IAppConfig
nameWithType: Microsoft.Identity.Client.IAppConfig
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public interface IAppConfig
- lang: fsharp
  values:
  - value: type IAppConfig = interface
- lang: vb
  values:
  - value: Public Interface IAppConfig
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: Configuration properties used to build a public or confidential client application.
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig
  - Microsoft::Identity::Client::IAppConfig
  - IAppConfig
  helpviewer_keywords:
  - Microsoft.Identity.Client.IAppConfig interface [.NET]
  monikers:
  - msal-dotnet-latest
