### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  commentId: P:Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  name: ValidateAuthority
  fullName: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  nameWithType: IClientApplicationBase.ValidateAuthority
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Can be set on AbstractApplicationBuilder<T>.WithAuthority as needed.  See https://aka.ms/msal-net-3-breaking-changes or https://aka.ms/msal-net-application-configuration", true)]

        public bool ValidateAuthority { get; }
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Can be set on AbstractApplicationBuilder<T>.WithAuthority as needed.  See https://aka.ms/msal-net-3-breaking-changes or https://aka.ms/msal-net-application-configuration", true)>]

        member this.ValidateAuthority : bool
  - lang: vb
    values:
    - value: Public ReadOnly Property ValidateAuthority As Boolean
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: Can be set on AbstractApplicationBuilder&lt;T&gt;.WithAuthority as needed.  See https://aka.ms/msal-net-3-breaking-changes or https://aka.ms/msal-net-application-configuration
  summary: >-
    Gets a boolean value telling the application if the authority needs to be verified against a list of known authorities. The default

    value is <code data-dev-comment-type="c">true</code>. It should currently be set to <code data-dev-comment-type="c">false</code> for Azure AD B2C authorities as those are customer specific

    (a list of known B2C authorities cannot be maintained by MSAL.NET)
  metadata: {}
uid: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority*
commentId: Overload:Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
namespace: Microsoft.Identity.Client
name: ValidateAuthority
fullName: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
nameWithType: IClientApplicationBase.ValidateAuthority
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  - Microsoft.Identity.Client.IClientApplicationBase.get_ValidateAuthority
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  - Microsoft::Identity::Client::IClientApplicationBase::ValidateAuthority
  - ValidateAuthority
  - IClientApplicationBase.ValidateAuthority
  - IClientApplicationBase::ValidateAuthority
  helpviewer_keywords:
  - IClientApplicationBase.ValidateAuthority property [.NET]
  - ValidateAuthority property [.NET], interface IClientApplicationBase
  monikers:
  - msal-dotnet-latest
