### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.#ctor
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.Succeeded
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
commentId: T:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
namespace: Microsoft.IdentityModel.Protocols
name: ConfigurationValidationResult
fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
nameWithType: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public class ConfigurationValidationResult
- lang: fsharp
  values:
  - value: type ConfigurationValidationResult = class
- lang: vb
  values:
  - value: Public Class ConfigurationValidationResult
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Represents the result of validation a <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IConfigurationValidator`1"></xref>.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
  - Microsoft::IdentityModel::Protocols::ConfigurationValidationResult
  - ConfigurationValidationResult
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult class [.NET]
  monikers:
  - msal-web-dotnet-latest
