### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  name: AzureRegion
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  nameWithType: MicrosoftIdentityApplicationOptions.AzureRegion
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? AzureRegion { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.AzureRegion : string with get, set'
  - lang: vb
    values:
    - value: Public Property AzureRegion As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Specifies the Azure region. See https://aka.ms/azure-region. To have

    the app attempt to detect the Azure region automatically,

    use "TryAutoDetect".
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
namespace: Microsoft.Identity.Abstractions
name: AzureRegion
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
nameWithType: MicrosoftIdentityApplicationOptions.AzureRegion
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_AzureRegion
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_AzureRegion
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.AzureRegion
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::AzureRegion
  - AzureRegion
  - MicrosoftIdentityApplicationOptions.AzureRegion
  - MicrosoftIdentityApplicationOptions::AzureRegion
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.AzureRegion property [.NET]
  - AzureRegion property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
