### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  name: TokenEndpoint
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  nameWithType: OpenIdConnectConfiguration.TokenEndpoint
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="token_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string TokenEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="token_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.TokenEndpoint : string with get, set
  - lang: vb
    values:
    - value: Public Property TokenEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'token_endpoint'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: TokenEndpoint
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
nameWithType: OpenIdConnectConfiguration.TokenEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_TokenEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_TokenEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.TokenEndpoint
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::TokenEndpoint
  - TokenEndpoint
  - OpenIdConnectConfiguration.TokenEndpoint
  - OpenIdConnectConfiguration::TokenEndpoint
  helpviewer_keywords:
  - OpenIdConnectConfiguration.TokenEndpoint property [.NET]
  - TokenEndpoint property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
