### YamlMime:NetMember
type: method
members:
- implementsWithMoniker:
  - value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh?alt=Microsoft.IdentityModel.Protocols.IConfigurationManager`1.RequestRefresh&text=RequestRefresh()" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh
  commentId: M:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh
  name: RequestRefresh()
  fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.RequestRefresh()
  nameWithType: StaticConfigurationManager<T>.RequestRefresh()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public override void RequestRefresh ();
  - lang: fsharp
    values:
    - value: 'override this.RequestRefresh : unit -> unit'
  - lang: vb
    values:
    - value: Public Overrides Sub RequestRefresh ()
  monikers:
  - msal-web-dotnet-latest
  summary: For the this type, this is a no-op
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh*
commentId: Overload:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh
namespace: Microsoft.IdentityModel.Protocols
name: RequestRefresh
fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.RequestRefresh
nameWithType: StaticConfigurationManager<T>.RequestRefresh
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.RequestRefresh
  - Microsoft::IdentityModel::Protocols::StaticConfigurationManager`1::RequestRefresh
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager.RequestRefresh
  - RequestRefresh
  - StaticConfigurationManager`1.RequestRefresh
  - StaticConfigurationManager`1::RequestRefresh
  helpviewer_keywords:
  - StaticConfigurationManager<T>.RequestRefresh method [.NET]
  - RequestRefresh method [.NET], class StaticConfigurationManager<T>
  - StaticConfigurationManager<T>.RequestRefresh() method [.NET]
  - RequestRefresh() method [.NET], class StaticConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
