### YamlMime:NetMember
type: constructor
members:
- parameters:
  - namesWithMoniker:
    - value: clientId
    description: >-
      Client ID (also known as App ID) of the application as registered in the
                  application registration portal (https://aka.ms/msal-net-register-app)/. REQUIRED
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String)
  commentId: M:Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String)
  name: PublicClientApplication(String)
  fullName: Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication(String)
  nameWithType: PublicClientApplication.PublicClientApplication(String)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public PublicClientApplication (string clientId);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        new Microsoft.Identity.Client.PublicClientApplication : string -> Microsoft.Identity.Client.PublicClientApplication
  - lang: vb
    values:
    - value: Public Sub New (clientId As String)
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. '
  summary: Constructor of the application. It will use https://login.microsoftonline.com/common as the default authority.
  metadata: {}
- parameters:
  - namesWithMoniker:
    - value: clientId
    description: >-
      Client ID (also named Application ID) of the application as registered in the
                  application registration portal (https://aka.ms/msal-net-register-app)/. REQUIRED
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: authority
    description: >-
      Authority of the security token service (STS) from which MSAL.NET will acquire the tokens.
                  Usual authorities are:
                  <ul><li><code data-dev-comment-type="c">https://login.microsoftonline.com/tenant/</code>, where <code data-dev-comment-type="c">tenant</code> is the tenant ID of the Azure AD tenant
                  or a domain associated with this Azure AD tenant, in order to sign-in user of a specific organization only</li><li><code data-dev-comment-type="c">https://login.microsoftonline.com/common/</code> to signing users with any work and school accounts or Microsoft personal account</li><li><code data-dev-comment-type="c">https://login.microsoftonline.com/organizations/</code> to signing users with any work and school accounts</li><li><code data-dev-comment-type="c">https://login.microsoftonline.com/consumers/</code> to signing users with only personal Microsoft account (live)</li></ul>
                  Note that this setting needs to be consistent with what is declared in the application registration portal
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String)
  commentId: M:Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String)
  name: PublicClientApplication(String, String)
  fullName: Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication(String, String)
  nameWithType: PublicClientApplication.PublicClientApplication(String, String)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public PublicClientApplication (string clientId, string authority);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        new Microsoft.Identity.Client.PublicClientApplication : string * string -> Microsoft.Identity.Client.PublicClientApplication
  - lang: vb
    values:
    - value: Public Sub New (clientId As String, authority As String)
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. '
  summary: Constructor of the application.
  metadata: {}
- parameters:
  - namesWithMoniker:
    - value: clientId
    description: Client id of the application
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: authority
    description: Default authority to be used for the application
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: userTokenCache
    description: Instance of TokenCache.
    type: <xref href="Microsoft.Identity.Client.TokenCache?alt=Microsoft.Identity.Client.TokenCache&text=TokenCache" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String,Microsoft.Identity.Client.TokenCache)
  commentId: M:Microsoft.Identity.Client.PublicClientApplication.#ctor(System.String,System.String,Microsoft.Identity.Client.TokenCache)
  name: PublicClientApplication(String, String, TokenCache)
  fullName: Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication(String, String, TokenCache)
  nameWithType: PublicClientApplication.PublicClientApplication(String, String, TokenCache)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public PublicClientApplication (string clientId, string authority, Microsoft.Identity.Client.TokenCache userTokenCache);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        new Microsoft.Identity.Client.PublicClientApplication : string * string * Microsoft.Identity.Client.TokenCache -> Microsoft.Identity.Client.PublicClientApplication
  - lang: vb
    values:
    - value: Public Sub New (clientId As String, authority As String, userTokenCache As TokenCache)
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use PublicClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes. '
  summary: Constructor to create application instance. This constructor is only available for Desktop and NetCore apps
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplication.#ctor*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplication.#ctor
namespace: Microsoft.Identity.Client
name: PublicClientApplication
fullName: Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication
nameWithType: PublicClientApplication.PublicClientApplication
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplication..ctor
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplication.#ctor
  - Microsoft::Identity::Client::PublicClientApplication::#ctor
  - '#ctor'
  - PublicClientApplication.#ctor
  - PublicClientApplication::#ctor
  helpviewer_keywords:
  - PublicClientApplication class [.NET], constructors
  - PublicClientApplication(String) class [.NET], constructors
  - PublicClientApplication(String, String) class [.NET], constructors
  - PublicClientApplication(String, String, TokenCache) class [.NET], constructors
  monikers:
  - msal-dotnet-latest
