### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Protocols.ConfigurationValidationResult?alt=Microsoft.IdentityModel.Protocols.ConfigurationValidationResult&text=ConfigurationValidationResult" data-throw-if-not-resolved="True"/>
    description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationValidationResult"></xref>.
  parameters:
  - namesWithMoniker:
    - value: configuration
    description: Configuration of type T.
    type: T
  type: method
  uid: Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate(`0)
  commentId: M:Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate(`0)
  name: Validate(T)
  fullName: Microsoft.IdentityModel.Protocols.IConfigurationValidator<T>.Validate(T)
  nameWithType: IConfigurationValidator<T>.Validate(T)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Protocols.ConfigurationValidationResult Validate (T configuration);
  - lang: fsharp
    values:
    - value: "abstract member Validate : 'T -> Microsoft.IdentityModel.Protocols.ConfigurationValidationResult"
  - lang: vb
    values:
    - value: Public Function Validate (configuration As T) As ConfigurationValidationResult
  monikers:
  - msal-web-dotnet-latest
  summary: Validate the retrieved configuration.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate*
commentId: Overload:Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate
namespace: Microsoft.IdentityModel.Protocols
name: Validate
fullName: Microsoft.IdentityModel.Protocols.IConfigurationValidator<T>.Validate
nameWithType: IConfigurationValidator<T>.Validate
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate
  - Microsoft::IdentityModel::Protocols::IConfigurationValidator`1::Validate
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator.Validate
  - Validate
  - IConfigurationValidator`1.Validate
  - IConfigurationValidator`1::Validate
  helpviewer_keywords:
  - IConfigurationValidator<T>.Validate method [.NET]
  - Validate method [.NET], interface IConfigurationValidator<T>
  - IConfigurationValidator<T>.Validate(T) method [.NET]
  - Validate(T) method [.NET], interface IConfigurationValidator<T>
  monikers:
  - msal-web-dotnet-latest
