### YamlMime:NetDelegate
returnsWithMoniker:
  type:
  - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  description: The issuer to use when creating the "Claim"(s) in a "ClaimsIdentity".
parameters:
- namesWithMoniker:
  - value: issuer
  description: The issuer to validate.
  type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: securityToken
  description: The <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SecurityToken"></xref> that is being validated.
  type: <xref href="Microsoft.IdentityModel.Tokens.SecurityToken?alt=Microsoft.IdentityModel.Tokens.SecurityToken&text=SecurityToken" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: validationParameters
  description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters"></xref> required for validation.
  type: <xref href="Microsoft.IdentityModel.Tokens.TokenValidationParameters?alt=Microsoft.IdentityModel.Tokens.TokenValidationParameters&text=TokenValidationParameters" data-throw-if-not-resolved="True"/>
- namesWithMoniker:
  - value: configuration
  description: <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration"></xref> required for validation.
  type: <xref href="Microsoft.IdentityModel.Tokens.BaseConfiguration?alt=Microsoft.IdentityModel.Tokens.BaseConfiguration&text=BaseConfiguration" data-throw-if-not-resolved="True"/>
inheritances:
- <xref href="System.Delegate" data-throw-if-not-resolved="True"/>
uid: Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
commentId: T:Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: IssuerValidatorUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
nameWithType: Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public delegate string IssuerValidatorUsingConfiguration(string issuer, SecurityToken securityToken, TokenValidationParameters validationParameters, BaseConfiguration configuration);
- lang: fsharp
  values:
  - value: type IssuerValidatorUsingConfiguration = delegate of string * SecurityToken * TokenValidationParameters * BaseConfiguration -> string
- lang: vb
  values:
  - value: 'Public Delegate Function IssuerValidatorUsingConfiguration(issuer As String, securityToken As SecurityToken, validationParameters As TokenValidationParameters, configuration As BaseConfiguration) As String '
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Definition for IssuerValidatorUsingConfiguration.
remarks: <p>The delegate should return a non null string that represents the 'issuer'. If null a default value will be used. If both <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration"></xref> and <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.IssuerValidator"></xref> are set, IssuerValidatorUsingConfiguration takes priority.</p>
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration..ctor
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration.Invoke
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration.BeginInvoke
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration.EndInvoke
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration
  - Microsoft::IdentityModel::Tokens::IssuerValidatorUsingConfiguration
  - IssuerValidatorUsingConfiguration
  helpviewer_keywords:
  - Microsoft.IdentityModel.Tokens.IssuerValidatorUsingConfiguration delegate [.NET]
  monikers:
  - msal-web-dotnet-latest
