### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Abstractions.CredentialDescription?alt=Microsoft.Identity.Abstractions.CredentialDescription&text=CredentialDescription" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  name: TokenDecryptionCredentials
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  nameWithType: IdentityApplicationOptions.TokenDecryptionCredentials
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<Microsoft.Identity.Abstractions.CredentialDescription>? TokenDecryptionCredentials { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.TokenDecryptionCredentials : seq<Microsoft.Identity.Abstractions.CredentialDescription> with get, set'
  - lang: vb
    values:
    - value: Public Property TokenDecryptionCredentials As IEnumerable(Of CredentialDescription)
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Description of the credentials (usually certificates) used to decrypt an encrypted 

    token in a web API.
  examples: >-
    An example in the appsetting.json:


    ```

    "TokenDecryptionCredentials": [
      {
        "SourceType": "StoreWithDistinguishedName",
         "CertificateStorePath": "CurrentUser/My",
         "CertificateDistinguishedName": "CN=WebAppCallingWebApiCert"
        }
       ]
    ```
                 See also https://aka.ms/ms-id-web-certificates.
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
namespace: Microsoft.Identity.Abstractions
name: TokenDecryptionCredentials
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
nameWithType: IdentityApplicationOptions.TokenDecryptionCredentials
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_TokenDecryptionCredentials
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_TokenDecryptionCredentials
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.TokenDecryptionCredentials
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::TokenDecryptionCredentials
  - TokenDecryptionCredentials
  - IdentityApplicationOptions.TokenDecryptionCredentials
  - IdentityApplicationOptions::TokenDecryptionCredentials
  helpviewer_keywords:
  - IdentityApplicationOptions.TokenDecryptionCredentials property [.NET]
  - TokenDecryptionCredentials property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
