### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  commentId: P:Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  name: RequiredScopesConfigurationKey
  fullName: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  nameWithType: IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredScopesConfigurationKey { get; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredScopesConfigurationKey : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property RequiredScopesConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Fully qualified name of the configuration key containing the required scopes (separated

    by spaces).
  metadata: {}
uid: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
namespace: Microsoft.Identity.Web
name: RequiredScopesConfigurationKey
fullName: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
nameWithType: IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.get_RequiredScopesConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  - Microsoft::Identity::Web::IAuthRequiredScopeOrAppPermissionMetadata::RequiredScopesConfigurationKey
  - RequiredScopesConfigurationKey
  - IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey
  - IAuthRequiredScopeOrAppPermissionMetadata::RequiredScopesConfigurationKey
  helpviewer_keywords:
  - IAuthRequiredScopeOrAppPermissionMetadata.RequiredScopesConfigurationKey property [.NET]
  - RequiredScopesConfigurationKey property [.NET], interface IAuthRequiredScopeOrAppPermissionMetadata
  monikers:
  - msal-model-dotnet-latest
