### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the discovery document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  name: GetAsync(String, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String, CancellationToken)
  nameWithType: OpenIdConnectConfigurationRetriever.GetAsync(String, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration> GetAsync (string address, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, cancel As CancellationToken) As Task(Of OpenIdConnectConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> given an address.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the discovery document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: retriever
    description: the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref> to use to read the discovery document
    type: <xref href="Microsoft.IdentityModel.Protocols.IDocumentRetriever?alt=Microsoft.IdentityModel.Protocols.IDocumentRetriever&text=IDocumentRetriever" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  name: GetAsync(String, IDocumentRetriever, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken)
  nameWithType: OpenIdConnectConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration> GetAsync (string address, Microsoft.IdentityModel.Protocols.IDocumentRetriever retriever, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * Microsoft.IdentityModel.Protocols.IDocumentRetriever * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, retriever As IDocumentRetriever, cancel As CancellationToken) As Task(Of OpenIdConnectConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> given an address and an <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref>.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the discovery document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: httpClient
    description: the <xref data-throw-if-not-resolved="true" uid="System.Net.Http.HttpClient"></xref> to use to read the discovery document.
    type: <xref href="System.Net.Http.HttpClient?alt=System.Net.Http.HttpClient&text=HttpClient" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  name: GetAsync(String, HttpClient, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken)
  nameWithType: OpenIdConnectConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration> GetAsync (string address, System.Net.Http.HttpClient httpClient, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * System.Net.Http.HttpClient * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, httpClient As HttpClient, cancel As CancellationToken) As Task(Of OpenIdConnectConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> given an address and an <xref data-throw-if-not-resolved="true" uid="System.Net.Http.HttpClient"></xref>.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: GetAsync
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync
nameWithType: OpenIdConnectConfigurationRetriever.GetAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfigurationRetriever::GetAsync
  - GetAsync
  - OpenIdConnectConfigurationRetriever.GetAsync
  - OpenIdConnectConfigurationRetriever::GetAsync
  helpviewer_keywords:
  - OpenIdConnectConfigurationRetriever.GetAsync method [.NET]
  - GetAsync method [.NET], class OpenIdConnectConfigurationRetriever
  - OpenIdConnectConfigurationRetriever.GetAsync(String, CancellationToken) method [.NET]
  - GetAsync(String, CancellationToken) method [.NET], class OpenIdConnectConfigurationRetriever
  - OpenIdConnectConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken) method [.NET]
  - GetAsync(String, IDocumentRetriever, CancellationToken) method [.NET], class OpenIdConnectConfigurationRetriever
  - OpenIdConnectConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken) method [.NET]
  - GetAsync(String, HttpClient, CancellationToken) method [.NET], class OpenIdConnectConfigurationRetriever
  monikers:
  - msal-web-dotnet-latest
