### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  name: ClientCapabilities
  fullName: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  nameWithType: ApplicationOptions.ClientCapabilities
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<string> ClientCapabilities { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ClientCapabilities : seq<string> with get, set'
  - lang: vb
    values:
    - value: Public Property ClientCapabilities As IEnumerable(Of String)
  monikers:
  - msal-dotnet-latest
  summary: >-
    Microsoft Identity specific OIDC extension that allows resource challenges to be resolved without interaction. 

    Allows configuration of one or more client capabilities, e.g. "llt"
  remarks: <p>MSAL will transform these into special claims request. See https://openid.net/specs/openid-connect-core-1_0-final.html#ClaimsParameter for details on claim requests. For more details see https://aka.ms/msal-net-claims-request</p>
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
namespace: Microsoft.Identity.Client
name: ClientCapabilities
fullName: Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
nameWithType: ApplicationOptions.ClientCapabilities
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  - Microsoft.Identity.Client.ApplicationOptions.get_ClientCapabilities
  - Microsoft.Identity.Client.ApplicationOptions.set_ClientCapabilities
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.ClientCapabilities
  - Microsoft::Identity::Client::ApplicationOptions::ClientCapabilities
  - ClientCapabilities
  - ApplicationOptions.ClientCapabilities
  - ApplicationOptions::ClientCapabilities
  helpviewer_keywords:
  - ApplicationOptions.ClientCapabilities property [.NET]
  - ClientCapabilities property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
