### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  name: KerberosServicePrincipalName
  fullName: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  nameWithType: ApplicationOptions.KerberosServicePrincipalName
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string KerberosServicePrincipalName { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.KerberosServicePrincipalName : string with get, set'
  - lang: vb
    values:
    - value: Public Property KerberosServicePrincipalName As String
  monikers:
  - msal-dotnet-latest
  summary: Service principal name for Kerberos Service Ticket.
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
namespace: Microsoft.Identity.Client
name: KerberosServicePrincipalName
fullName: Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
nameWithType: ApplicationOptions.KerberosServicePrincipalName
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  - Microsoft.Identity.Client.ApplicationOptions.get_KerberosServicePrincipalName
  - Microsoft.Identity.Client.ApplicationOptions.set_KerberosServicePrincipalName
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.KerberosServicePrincipalName
  - Microsoft::Identity::Client::ApplicationOptions::KerberosServicePrincipalName
  - KerberosServicePrincipalName
  - ApplicationOptions.KerberosServicePrincipalName
  - ApplicationOptions::KerberosServicePrincipalName
  helpviewer_keywords:
  - ApplicationOptions.KerberosServicePrincipalName property [.NET]
  - KerberosServicePrincipalName property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
