### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  name: AllowWebApiToBeAuthorizedByACL
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  nameWithType: IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool AllowWebApiToBeAuthorizedByACL { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.AllowWebApiToBeAuthorizedByACL : bool with get, set'
  - lang: vb
    values:
    - value: Public Property AllowWebApiToBeAuthorizedByACL As Boolean
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Web APIs called by daemon applications can validate a token based on roles (representing app permissions), 

    or using the ACL-based authorization pattern for the client (daemon) to the web API. If using ACL-based authorization,

    the implementation will not throw if roles or scopes are not in the Claims.

    For details see https://aka.ms/ms-identity-web/daemon-ACL.
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
namespace: Microsoft.Identity.Abstractions
name: AllowWebApiToBeAuthorizedByACL
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
nameWithType: IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_AllowWebApiToBeAuthorizedByACL
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_AllowWebApiToBeAuthorizedByACL
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::AllowWebApiToBeAuthorizedByACL
  - AllowWebApiToBeAuthorizedByACL
  - IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL
  - IdentityApplicationOptions::AllowWebApiToBeAuthorizedByACL
  helpviewer_keywords:
  - IdentityApplicationOptions.AllowWebApiToBeAuthorizedByACL property [.NET]
  - AllowWebApiToBeAuthorizedByACL property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
