### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor
  commentId: M:Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor
  name: ConfidentialClientApplicationOptions()
  fullName: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.ConfidentialClientApplicationOptions()
  nameWithType: ConfidentialClientApplicationOptions.ConfidentialClientApplicationOptions()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public ConfidentialClientApplicationOptions ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor
namespace: Microsoft.Identity.Client
name: ConfidentialClientApplicationOptions
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.ConfidentialClientApplicationOptions
nameWithType: ConfidentialClientApplicationOptions.ConfidentialClientApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions..ctor
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions.#ctor
  - Microsoft::Identity::Client::ConfidentialClientApplicationOptions::#ctor
  - '#ctor'
  - ConfidentialClientApplicationOptions.#ctor
  - ConfidentialClientApplicationOptions::#ctor
  helpviewer_keywords:
  - ConfidentialClientApplicationOptions class [.NET], constructors
  - ConfidentialClientApplicationOptions() class [.NET], constructors
  monikers:
  - msal-dotnet-latest
