### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConstants.Types.ApplicationServiceType
  commentId: F:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConstants.Types.ApplicationServiceType
  name: ApplicationServiceType
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConstants.Types.ApplicationServiceType
  nameWithType: WsFederationConstants.Types.ApplicationServiceType
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public const string ApplicationServiceType;
  - lang: fsharp
    values:
    - value: 'val mutable ApplicationServiceType : string'
  - lang: vb
    values:
    - value: 'Public Const ApplicationServiceType As String '
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols.WsFederation
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConstants.Types.ApplicationServiceType
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConstants.Types.ApplicationServiceType
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConstants::Types::ApplicationServiceType
  - ApplicationServiceType
  - Types.ApplicationServiceType
  - Types::ApplicationServiceType
  helpviewer_keywords:
  - WsFederationConstants.Types.ApplicationServiceType field [.NET]
  - ApplicationServiceType field [.NET], class WsFederationConstants.Types
  monikers:
  - msal-web-dotnet-latest
