### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor
  name: OpenIdConnectConfigurationValidator()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.OpenIdConnectConfigurationValidator()
  nameWithType: OpenIdConnectConfigurationValidator.OpenIdConnectConfigurationValidator()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public OpenIdConnectConfigurationValidator ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
name: OpenIdConnectConfigurationValidator
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.OpenIdConnectConfigurationValidator
nameWithType: OpenIdConnectConfigurationValidator.OpenIdConnectConfigurationValidator
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::Configuration::OpenIdConnectConfigurationValidator::#ctor
  - '#ctor'
  - OpenIdConnectConfigurationValidator.#ctor
  - OpenIdConnectConfigurationValidator::#ctor
  helpviewer_keywords:
  - OpenIdConnectConfigurationValidator class [.NET], constructors
  - OpenIdConnectConfigurationValidator() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
