### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  name: Instance
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  nameWithType: MicrosoftIdentityApplicationOptions.Instance
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? Instance { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Instance : string with get, set'
  - lang: vb
    values:
    - value: Public Property Instance As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets or sets the Azure Active Directory instance, e.g. <code data-dev-comment-type="c">"https://login.microsoftonline.com/"</code>.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
namespace: Microsoft.Identity.Abstractions
name: Instance
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
nameWithType: MicrosoftIdentityApplicationOptions.Instance
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_Instance
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_Instance
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::Instance
  - Instance
  - MicrosoftIdentityApplicationOptions.Instance
  - MicrosoftIdentityApplicationOptions::Instance
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.Instance property [.NET]
  - Instance property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
