### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder?alt=Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder&text=AcquireTokenSilentParameterBuilder" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: scopes
    type: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  - namesWithMoniker:
    - value: loginHint
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  implementsWithMoniker:
  - value: <xref href="Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)?alt=Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)&text=AcquireTokenSilent(IEnumerable%3CString%3E%2C+String)" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  commentId: M:Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  name: AcquireTokenSilent(IEnumerable<String>, String)
  fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent(IEnumerable<String>, String)
  nameWithType: IConfidentialClientApplication.AcquireTokenSilent(IEnumerable<String>, String)
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("In confidential client apps use AcquireTokenSilent(scopes, account) instead.")]

        public Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder AcquireTokenSilent (System.Collections.Generic.IEnumerable<string> scopes, string loginHint);
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("In confidential client apps use AcquireTokenSilent(scopes, account) instead.")>]

        abstract member AcquireTokenSilent : seq<string> * string -> Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder
  - lang: vb
    values:
    - value: Public Function AcquireTokenSilent (scopes As IEnumerable(Of String), loginHint As String) As AcquireTokenSilentParameterBuilder
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: In confidential client apps use AcquireTokenSilent(scopes, account) instead.
  summary: In confidential client apps use <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)"></xref> instead.
  metadata: {}
uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent*
commentId: Overload:Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent
namespace: Microsoft.Identity.Client
name: AcquireTokenSilent
fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent
nameWithType: IConfidentialClientApplication.AcquireTokenSilent
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent
  - Microsoft::Identity::Client::IConfidentialClientApplication::AcquireTokenSilent
  - AcquireTokenSilent
  - IConfidentialClientApplication.AcquireTokenSilent
  - IConfidentialClientApplication::AcquireTokenSilent
  helpviewer_keywords:
  - IConfidentialClientApplication.AcquireTokenSilent method [.NET]
  - AcquireTokenSilent method [.NET], interface IConfidentialClientApplication
  - IConfidentialClientApplication.AcquireTokenSilent(IEnumerable<String>, String) method [.NET]
  - AcquireTokenSilent(IEnumerable<String>, String) method [.NET], interface IConfidentialClientApplication
  monikers:
  - msal-dotnet-latest
