### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.Component
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.Component
  name: Component
  fullName: Microsoft.Identity.Client.ApplicationOptions.Component
  nameWithType: ApplicationOptions.Component
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Should use ClientName and ClientVersion properties instead of Component", true)]

        public string Component { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Should use ClientName and ClientVersion properties instead of Component", true)>]

        member this.Component : string with get, set
  - lang: vb
    values:
    - value: Public Property Component As String
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: Should use ClientName and ClientVersion properties instead of Component
  summary: >-
    Identifier of the component (libraries/SDK) consuming MSAL.NET.

    This will allow for disambiguation between MSAL usage by the app vs MSAL usage by component libraries.
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.Component*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.Component
namespace: Microsoft.Identity.Client
name: Component
fullName: Microsoft.Identity.Client.ApplicationOptions.Component
nameWithType: ApplicationOptions.Component
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.Component
  - Microsoft.Identity.Client.ApplicationOptions.get_Component
  - Microsoft.Identity.Client.ApplicationOptions.set_Component
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.Component
  - Microsoft::Identity::Client::ApplicationOptions::Component
  - Component
  - ApplicationOptions.Component
  - ApplicationOptions::Component
  helpviewer_keywords:
  - ApplicationOptions.Component property [.NET]
  - Component property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
