### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  name: ShouldSerializeResponseModesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeResponseModesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeResponseModesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeResponseModesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'response_modes_supported' (ResponseModesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeResponseModesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeResponseModesSupported
  - ShouldSerializeResponseModesSupported
  - OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported
  - OpenIdConnectConfiguration::ShouldSerializeResponseModesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported method [.NET]
  - ShouldSerializeResponseModesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeResponseModesSupported() method [.NET]
  - ShouldSerializeResponseModesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
