### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  name: Authority
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  nameWithType: IdentityApplicationOptions.Authority
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public virtual string? Authority { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Authority : string with get, set'
  - lang: vb
    values:
    - value: Public Overridable Property Authority As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Gets or sets the authority to use when calling the identity provider. 

    For AzureAD or Azure AD B2C, rather use <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.Instance"></xref>

    and <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.TenantId"></xref>
  examples: >-
    ```

    AuthenticationOptions options = new 

    {
     Authority = "https://login.microsoftonline.com/common/"
    };

    ```
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
namespace: Microsoft.Identity.Abstractions
name: Authority
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
nameWithType: IdentityApplicationOptions.Authority
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_Authority
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_Authority
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.Authority
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::Authority
  - Authority
  - IdentityApplicationOptions.Authority
  - IdentityApplicationOptions::Authority
  helpviewer_keywords:
  - IdentityApplicationOptions.Authority property [.NET]
  - Authority property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
