### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: account
    description: Instance of the account that needs to be removed
    type: <xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>
  implementsWithMoniker:
  - value: <xref href="Microsoft.Identity.Client.IClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)?alt=Microsoft.Identity.Client.IClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)&text=RemoveAsync(IAccount)" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  name: RemoveAsync(IAccount)
  fullName: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(IAccount)
  nameWithType: ClientApplicationBase.RemoveAsync(IAccount)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task RemoveAsync (Microsoft.Identity.Client.IAccount account);
  - lang: fsharp
    values:
    - value: >-
        abstract member RemoveAsync : Microsoft.Identity.Client.IAccount -> System.Threading.Tasks.Task

        override this.RemoveAsync : Microsoft.Identity.Client.IAccount -> System.Threading.Tasks.Task
  - lang: vb
    values:
    - value: Public Function RemoveAsync (account As IAccount) As Task
  monikers:
  - msal-dotnet-latest
  summary: Removes all tokens in the cache for the specified account.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: account
    description: Instance of the account that needs to be removed
    type: <xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancellationToken
    description: Cancellation token
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount,System.Threading.CancellationToken)
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount,System.Threading.CancellationToken)
  name: RemoveAsync(IAccount, CancellationToken)
  fullName: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(IAccount, CancellationToken)
  nameWithType: ClientApplicationBase.RemoveAsync(IAccount, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task RemoveAsync (Microsoft.Identity.Client.IAccount account, System.Threading.CancellationToken cancellationToken = default);
  - lang: fsharp
    values:
    - value: 'member this.RemoveAsync : Microsoft.Identity.Client.IAccount * System.Threading.CancellationToken -> System.Threading.Tasks.Task'
  - lang: vb
    values:
    - value: Public Function RemoveAsync (account As IAccount, Optional cancellationToken As CancellationToken = Nothing) As Task
  monikers:
  - msal-dotnet-latest
  summary: Removes all tokens in the cache for the specified account.
  metadata: {}
uid: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync*
commentId: Overload:Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync
namespace: Microsoft.Identity.Client
name: RemoveAsync
fullName: Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync
nameWithType: ClientApplicationBase.RemoveAsync
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync
  - Microsoft::Identity::Client::ClientApplicationBase::RemoveAsync
  - RemoveAsync
  - ClientApplicationBase.RemoveAsync
  - ClientApplicationBase::RemoveAsync
  helpviewer_keywords:
  - ClientApplicationBase.RemoveAsync method [.NET]
  - RemoveAsync method [.NET], class ClientApplicationBase
  - ClientApplicationBase.RemoveAsync(IAccount) method [.NET]
  - RemoveAsync(IAccount) method [.NET], class ClientApplicationBase
  - ClientApplicationBase.RemoveAsync(IAccount, CancellationToken) method [.NET]
  - RemoveAsync(IAccount, CancellationToken) method [.NET], class ClientApplicationBase
  monikers:
  - msal-dotnet-latest
