### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: T
  parameters:
  - namesWithMoniker:
    - value: instanceDiscoveryJson
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.String)
  commentId: M:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.String)
  name: WithInstanceDiscoveryMetadata(String)
  fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(String)
  nameWithType: AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public T WithInstanceDiscoveryMetadata (string instanceDiscoveryJson);
  - lang: fsharp
    values:
    - value: "member this.WithInstanceDiscoveryMetadata : string -> 'T"
  - lang: vb
    values:
    - value: Public Function WithInstanceDiscoveryMetadata (instanceDiscoveryJson As String) As T
  monikers:
  - msal-dotnet-latest
  summary: >-
    Allows developers to configure their own valid authorities. A json string similar to https://aka.ms/aad-instance-discovery should be provided.

    MSAL uses this information to: 

    <ul><li>Call REST APIs on the environment specified in the preferred_network</li><li>Identify an environment under which to save tokens and accounts in the cache</li><li>Use the environment aliases to match tokens issued to other authorities</li></ul>

    For more details see https://aka.ms/msal-net-custom-instance-metadata
  remarks: <p>Developers take responsibility for authority validation if they use this method. Should not be used when the authority is not known in advance. Has no effect on ADFS or B2C authorities, only for AAD authorities</p>
  metadata: {}
- returnsWithMoniker:
    type:
    - value: T
  parameters:
  - namesWithMoniker:
    - value: instanceDiscoveryUri
    type: <xref href="System.Uri?alt=System.Uri&text=Uri" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.Uri)
  commentId: M:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.Uri)
  name: WithInstanceDiscoveryMetadata(Uri)
  fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(Uri)
  nameWithType: AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(Uri)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public T WithInstanceDiscoveryMetadata (Uri instanceDiscoveryUri);
  - lang: fsharp
    values:
    - value: "member this.WithInstanceDiscoveryMetadata : Uri -> 'T"
  - lang: vb
    values:
    - value: Public Function WithInstanceDiscoveryMetadata (instanceDiscoveryUri As Uri) As T
  monikers:
  - msal-dotnet-latest
  summary: >-
    Lets an organization setup their own service to handle instance discovery, which enables better caching for microservice/service environments.

    A Uri that returns a response similar to https://aka.ms/aad-instance-discovery should be provided. MSAL uses this information to: 

    <ul><li>Call REST APIs on the environment specified in the preferred_network</li><li>Identify an environment under which to save tokens and accounts in the cache</li><li>Use the environment aliases to match tokens issued to other authorities</li></ul>

    For more details see https://aka.ms/msal-net-custom-instance-metadata
  remarks: <p>Developers take responsibility for authority validation if they use this method. Should not be used when the authority is not known in advance. Has no effect on ADFS or B2C authorities, only for AAD authorities</p>
  metadata: {}
uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata*
commentId: Overload:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata
namespace: Microsoft.Identity.Client
name: WithInstanceDiscoveryMetadata
fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata
nameWithType: AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata
  - Microsoft::Identity::Client::AbstractApplicationBuilder`1::WithInstanceDiscoveryMetadata
  - Microsoft.Identity.Client.AbstractApplicationBuilder.WithInstanceDiscoveryMetadata
  - WithInstanceDiscoveryMetadata
  - AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata
  - AbstractApplicationBuilder`1::WithInstanceDiscoveryMetadata
  helpviewer_keywords:
  - AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata method [.NET]
  - WithInstanceDiscoveryMetadata method [.NET], class AbstractApplicationBuilder<T>
  - AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(String) method [.NET]
  - WithInstanceDiscoveryMetadata(String) method [.NET], class AbstractApplicationBuilder<T>
  - AbstractApplicationBuilder<T>.WithInstanceDiscoveryMetadata(Uri) method [.NET]
  - WithInstanceDiscoveryMetadata(Uri) method [.NET], class AbstractApplicationBuilder<T>
  monikers:
  - msal-dotnet-latest
