### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  commentId: P:Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  name: EnablePiiLogging
  fullName: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  nameWithType: ApplicationOptions.EnablePiiLogging
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool EnablePiiLogging { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.EnablePiiLogging : bool with get, set'
  - lang: vb
    values:
    - value: Public Property EnablePiiLogging As Boolean
  monikers:
  - msal-dotnet-latest
  seeAlso: >+
    - <xref:Microsoft.Identity.Client.ApplicationOptions.IsDefaultPlatformLoggingEnabled>

  summary: >-
    Flag to enable/disable logging of Personally Identifiable Information (PII).

    PII logs are never written to default outputs like Console, Logcat or NSLog

    Default is set to <code data-dev-comment-type="c">false</code>, which ensures that your application is compliant with GDPR. You can set

    it to <code data-dev-comment-type="c">true</code> for advanced debugging requiring PII. See https://aka.ms/msal-net-logging
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
namespace: Microsoft.Identity.Client
name: EnablePiiLogging
fullName: Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
nameWithType: ApplicationOptions.EnablePiiLogging
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  - Microsoft.Identity.Client.ApplicationOptions.get_EnablePiiLogging
  - Microsoft.Identity.Client.ApplicationOptions.set_EnablePiiLogging
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.EnablePiiLogging
  - Microsoft::Identity::Client::ApplicationOptions::EnablePiiLogging
  - EnablePiiLogging
  - ApplicationOptions.EnablePiiLogging
  - ApplicationOptions::EnablePiiLogging
  helpviewer_keywords:
  - ApplicationOptions.EnablePiiLogging property [.NET]
  - EnablePiiLogging property [.NET], class ApplicationOptions
  monikers:
  - msal-dotnet-latest
