### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.SignatureValidatorUsingConfiguration?alt=Microsoft.IdentityModel.Tokens.SignatureValidatorUsingConfiguration&text=SignatureValidatorUsingConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
  name: SignatureValidatorUsingConfiguration
  fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
  nameWithType: TokenValidationParameters.SignatureValidatorUsingConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.SignatureValidatorUsingConfiguration SignatureValidatorUsingConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.SignatureValidatorUsingConfiguration : Microsoft.IdentityModel.Tokens.SignatureValidatorUsingConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property SignatureValidatorUsingConfiguration As SignatureValidatorUsingConfiguration
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets or sets a delegate that will be used to validate the signature of the token using the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.TokenValidationParameters"></xref> and

    the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfiguration"></xref>.
  remarks: If set, this delegate will be called to signature of the token, instead of default processing.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: SignatureValidatorUsingConfiguration
fullName: Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
nameWithType: TokenValidationParameters.SignatureValidatorUsingConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.get_SignatureValidatorUsingConfiguration
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.set_SignatureValidatorUsingConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.TokenValidationParameters.SignatureValidatorUsingConfiguration
  - Microsoft::IdentityModel::Tokens::TokenValidationParameters::SignatureValidatorUsingConfiguration
  - SignatureValidatorUsingConfiguration
  - TokenValidationParameters.SignatureValidatorUsingConfiguration
  - TokenValidationParameters::SignatureValidatorUsingConfiguration
  helpviewer_keywords:
  - TokenValidationParameters.SignatureValidatorUsingConfiguration property [.NET]
  - SignatureValidatorUsingConfiguration property [.NET], class TokenValidationParameters
  monikers:
  - msal-web-dotnet-latest
