### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  commentId: P:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  name: Nonce
  fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  nameWithType: PoPAuthenticationConfiguration.Nonce
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string Nonce { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.Nonce : string with get, set'
  - lang: vb
    values:
    - value: Public Property Nonce As String
  monikers:
  - msal-dotnet-latest
  summary: >-
    If the protected resource (RP) requires use of a special nonce, they will publish it as part of the WWWAuthenticate header associated with a 401 HTTP response

    or as part of the AuthorityInfo header associated with 200 response. Set it here to make it part of the Signed HTTP Request part of the POP token.
  metadata: {}
uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce*
commentId: Overload:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
namespace: Microsoft.Identity.Client.AppConfig
name: Nonce
fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
nameWithType: PoPAuthenticationConfiguration.Nonce
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.get_Nonce
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.set_Nonce
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.Nonce
  - Microsoft::Identity::Client::AppConfig::PoPAuthenticationConfiguration::Nonce
  - Nonce
  - PoPAuthenticationConfiguration.Nonce
  - PoPAuthenticationConfiguration::Nonce
  helpviewer_keywords:
  - PoPAuthenticationConfiguration.Nonce property [.NET]
  - Nonce property [.NET], class PoPAuthenticationConfiguration
  monikers:
  - msal-dotnet-latest
