### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1?alt=Microsoft.IdentityModel.Protocols.IConfigurationRetriever&text=IConfigurationRetriever" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration?alt=Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration&text=WsFederationConfiguration" data-throw-if-not-resolved="True"/>&gt;
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetConfigurationAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
commentId: T:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: WsFederationConfigurationRetriever
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
nameWithType: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class WsFederationConfigurationRetriever : Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration>'
- lang: fsharp
  values:
  - value: >-
      type WsFederationConfigurationRetriever = class
          interface IConfigurationRetriever<WsFederationConfiguration>
- lang: vb
  values:
  - value: >-
      Public Class WsFederationConfigurationRetriever

      Implements IConfigurationRetriever(Of WsFederationConfiguration)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> given an address.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfigurationRetriever
  - WsFederationConfigurationRetriever
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever class [.NET]
  monikers:
  - msal-web-dotnet-latest
