### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  commentId: P:Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  name: OperatingSystemAccount
  fullName: Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  nameWithType: PublicClientApplication.OperatingSystemAccount
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.Identity.Client.IAccount OperatingSystemAccount { get; }
  - lang: fsharp
    values:
    - value: 'static member OperatingSystemAccount : Microsoft.Identity.Client.IAccount'
  - lang: vb
    values:
    - value: Public Shared ReadOnly Property OperatingSystemAccount As IAccount
  monikers:
  - msal-dotnet-latest
  summary: >-
    Currently only the Windows broker is able to login with the current user, see https://aka.ms/msal-net-wam for details.


    A special account value that indicates that the current Operating System account should be used 

    to login the user. Not all operating systems and authentication flows support this concept, in which 

    case calling `AcquireTokenSilent` will throw an <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.MsalUiRequiredException"></xref>.
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
namespace: Microsoft.Identity.Client
name: OperatingSystemAccount
fullName: Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
nameWithType: PublicClientApplication.OperatingSystemAccount
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  - Microsoft.Identity.Client.PublicClientApplication.get_OperatingSystemAccount
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplication.OperatingSystemAccount
  - Microsoft::Identity::Client::PublicClientApplication::OperatingSystemAccount
  - OperatingSystemAccount
  - PublicClientApplication.OperatingSystemAccount
  - PublicClientApplication::OperatingSystemAccount
  helpviewer_keywords:
  - PublicClientApplication.OperatingSystemAccount property [.NET]
  - OperatingSystemAccount property [.NET], class PublicClientApplication
  monikers:
  - msal-dotnet-latest
