### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  name: Issuer
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  nameWithType: OpenIdConnectConfiguration.Issuer
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="issuer", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public override string Issuer { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="issuer", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.Issuer : string with get, set
  - lang: vb
    values:
    - value: Public Overrides Property Issuer As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'issuer'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: Issuer
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
nameWithType: OpenIdConnectConfiguration.Issuer
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_Issuer
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_Issuer
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.Issuer
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::Issuer
  - Issuer
  - OpenIdConnectConfiguration.Issuer
  - OpenIdConnectConfiguration::Issuer
  helpviewer_keywords:
  - OpenIdConnectConfiguration.Issuer property [.NET]
  - Issuer property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
