### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  name: IntrospectionEndpoint
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  nameWithType: OpenIdConnectConfiguration.IntrospectionEndpoint
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="introspection_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string IntrospectionEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="introspection_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.IntrospectionEndpoint : string with get, set
  - lang: vb
    values:
    - value: Public Property IntrospectionEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'introspection_endpoint'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: IntrospectionEndpoint
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
nameWithType: OpenIdConnectConfiguration.IntrospectionEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_IntrospectionEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_IntrospectionEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.IntrospectionEndpoint
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::IntrospectionEndpoint
  - IntrospectionEndpoint
  - OpenIdConnectConfiguration.IntrospectionEndpoint
  - OpenIdConnectConfiguration::IntrospectionEndpoint
  helpviewer_keywords:
  - OpenIdConnectConfiguration.IntrospectionEndpoint property [.NET]
  - IntrospectionEndpoint property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
