### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Tokens.SecurityKey?alt=Microsoft.IdentityModel.Tokens.SecurityKey&text=SecurityKey" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  name: SigningKeys
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  nameWithType: OpenIdConnectConfiguration.SigningKeys
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonIgnoreAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonIgnore]

        public override System.Collections.Generic.ICollection<Microsoft.IdentityModel.Tokens.SecurityKey> SigningKeys { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonIgnore>]

        member this.SigningKeys : System.Collections.Generic.ICollection<Microsoft.IdentityModel.Tokens.SecurityKey>
  - lang: vb
    values:
    - value: Public Overrides ReadOnly Property SigningKeys As ICollection(Of SecurityKey)
  monikers:
  - msal-web-dotnet-latest
  summary: Gets the <xref data-throw-if-not-resolved="true" uid="System.Collections.Generic.ICollection`1"></xref> that the IdentityProvider indicates are to be used signing tokens.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: SigningKeys
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
nameWithType: OpenIdConnectConfiguration.SigningKeys
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_SigningKeys
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.SigningKeys
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::SigningKeys
  - SigningKeys
  - OpenIdConnectConfiguration.SigningKeys
  - OpenIdConnectConfiguration::SigningKeys
  helpviewer_keywords:
  - OpenIdConnectConfiguration.SigningKeys property [.NET]
  - SigningKeys property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
