### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;T&gt;
    description: Configuration of type T.
  parameters:
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  implementsWithMoniker:
  - value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)?alt=Microsoft.IdentityModel.Protocols.IConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)&text=GetConfigurationAsync(CancellationToken)" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync(System.Threading.CancellationToken)
  name: GetConfigurationAsync(CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.GetConfigurationAsync(CancellationToken)
  nameWithType: StaticConfigurationManager<T>.GetConfigurationAsync(CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<T> GetConfigurationAsync (System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: >-
        abstract member GetConfigurationAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<'T (requires 'T : null)>

        override this.GetConfigurationAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<'T (requires 'T : null)>
  - lang: vb
    values:
    - value: Public Function GetConfigurationAsync (cancel As CancellationToken) As Task(Of T)
  monikers:
  - msal-web-dotnet-latest
  summary: Obtains an updated version of Configuration.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync*
commentId: Overload:Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync
namespace: Microsoft.IdentityModel.Protocols
name: GetConfigurationAsync
fullName: Microsoft.IdentityModel.Protocols.StaticConfigurationManager<T>.GetConfigurationAsync
nameWithType: StaticConfigurationManager<T>.GetConfigurationAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager`1.GetConfigurationAsync
  - Microsoft::IdentityModel::Protocols::StaticConfigurationManager`1::GetConfigurationAsync
  - Microsoft.IdentityModel.Protocols.StaticConfigurationManager.GetConfigurationAsync
  - GetConfigurationAsync
  - StaticConfigurationManager`1.GetConfigurationAsync
  - StaticConfigurationManager`1::GetConfigurationAsync
  helpviewer_keywords:
  - StaticConfigurationManager<T>.GetConfigurationAsync method [.NET]
  - GetConfigurationAsync method [.NET], class StaticConfigurationManager<T>
  - StaticConfigurationManager<T>.GetConfigurationAsync(CancellationToken) method [.NET]
  - GetConfigurationAsync(CancellationToken) method [.NET], class StaticConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
