### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  name: RegistrationEndpoint
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  nameWithType: OpenIdConnectConfiguration.RegistrationEndpoint
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="registration_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string RegistrationEndpoint { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="registration_endpoint", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.RegistrationEndpoint : string with get, set
  - lang: vb
    values:
    - value: Public Property RegistrationEndpoint As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'registration_endpoint'
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: RegistrationEndpoint
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
nameWithType: OpenIdConnectConfiguration.RegistrationEndpoint
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_RegistrationEndpoint
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_RegistrationEndpoint
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RegistrationEndpoint
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::RegistrationEndpoint
  - RegistrationEndpoint
  - OpenIdConnectConfiguration.RegistrationEndpoint
  - OpenIdConnectConfiguration::RegistrationEndpoint
  helpviewer_keywords:
  - OpenIdConnectConfiguration.RegistrationEndpoint property [.NET]
  - RegistrationEndpoint property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
