### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  commentId: F:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  name: DefaultRefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  nameWithType: BaseConfigurationManager.DefaultRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan DefaultRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable DefaultRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly DefaultRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 5 minutes is the default time interval that must pass for <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RequestRefresh"></xref> to obtain a new configuration.
  metadata: {}
namespace: Microsoft.IdentityModel.Tokens
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.DefaultRefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::DefaultRefreshInterval
  - DefaultRefreshInterval
  - BaseConfigurationManager.DefaultRefreshInterval
  - BaseConfigurationManager::DefaultRefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.DefaultRefreshInterval field [.NET]
  - DefaultRefreshInterval field [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
