### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Client.AbstractApplicationBuilder`1?alt=Microsoft.Identity.Client.AbstractApplicationBuilder&text=AbstractApplicationBuilder" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.PublicClientApplicationBuilder?alt=Microsoft.Identity.Client.PublicClientApplicationBuilder&text=PublicClientApplicationBuilder" data-throw-if-not-resolved="True"/>&gt;
extensionMethods:
- uid: Microsoft.Identity.Client.Desktop.DesktopExtensions.WithDesktopFeatures(Microsoft.Identity.Client.PublicClientApplicationBuilder)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.Desktop.WamExtension.WithWindowsBroker(Microsoft.Identity.Client.PublicClientApplicationBuilder,System.Boolean)
  monikers:
  - msal-dotnet-latest
methods:
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.Build
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.Create(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.CreateWithApplicationOptions(Microsoft.Identity.Client.PublicClientApplicationOptions)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAdfsAuthority(System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AadAuthorityAudience,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,Microsoft.Identity.Client.AadAuthorityAudience,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,System.Guid,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(Microsoft.Identity.Client.AzureCloudInstance,System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.Guid,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.String,System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(System.Uri,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithB2CAuthority(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithBroker(System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithCacheOptions(Microsoft.Identity.Client.CacheOptions)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientCapabilities(System.Collections.Generic.IEnumerable{System.String})
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientId(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientName(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithClientVersion(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithDebugLoggingCallback(Microsoft.Identity.Client.LogLevel,System.Boolean,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithDefaultRedirectUri
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExperimentalFeatures(System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExtraQueryParameters(System.Collections.Generic.IDictionary{System.String,System.String})
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithExtraQueryParameters(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDicoveryMetadata(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDicoveryMetadata(System.Uri)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscovery(System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithInstanceDiscoveryMetadata(System.Uri)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithIosKeychainSecurityGroup(System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithKerberosTicketClaim(System.String,Microsoft.Identity.Client.Kerberos.KerberosTicketContainer)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLegacyCacheCompatibility(System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithLogging(Microsoft.Identity.Client.LogCallback,System.Nullable{Microsoft.Identity.Client.LogLevel},System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithMultiCloudSupport(System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithOptions(Microsoft.Identity.Client.ApplicationOptions)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.IntPtr})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithParentActivityOrWindow(System.Func{System.Object})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithRedirectUri(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithTelemetry(Microsoft.Identity.Client.ITelemetryConfig)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithTenantId(System.String)
  inheritedFrom: Microsoft.Identity.Client.AbstractApplicationBuilder`1
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.WithWindowsBrokerOptions(Microsoft.Identity.Client.WindowsBrokerOptions)
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.PublicClientApplicationBuilder
commentId: T:Microsoft.Identity.Client.PublicClientApplicationBuilder
namespace: Microsoft.Identity.Client
name: PublicClientApplicationBuilder
fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder
nameWithType: Microsoft.Identity.Client.PublicClientApplicationBuilder
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public sealed class PublicClientApplicationBuilder : Microsoft.Identity.Client.AbstractApplicationBuilder<Microsoft.Identity.Client.PublicClientApplicationBuilder>'
- lang: fsharp
  values:
  - value: >-
      type PublicClientApplicationBuilder = class
          inherit AbstractApplicationBuilder<PublicClientApplicationBuilder>
- lang: vb
  values:
  - value: >-
      Public NotInheritable Class PublicClientApplicationBuilder

      Inherits AbstractApplicationBuilder(Of PublicClientApplicationBuilder)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder
  - Microsoft::Identity::Client::PublicClientApplicationBuilder
  - PublicClientApplicationBuilder
  helpviewer_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder class [.NET]
  monikers:
  - msal-dotnet-latest
