### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  commentId: P:Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  name: IsDefaultPlatformLoggingEnabled
  fullName: Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  nameWithType: IAppConfig.IsDefaultPlatformLoggingEnabled
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsDefaultPlatformLoggingEnabled { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsDefaultPlatformLoggingEnabled : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsDefaultPlatformLoggingEnabled As Boolean
  monikers:
  - msal-dotnet-latest
  summary: >-
    Flag telling if logging to platform defaults is enabled/disabled for the app.

    In Desktop/UWP, Event Tracing is used. In iOS, NSLog is used.

    In Android, logcat is used. See https://aka.ms/msal-net-logging.
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
namespace: Microsoft.Identity.Client
name: IsDefaultPlatformLoggingEnabled
fullName: Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
nameWithType: IAppConfig.IsDefaultPlatformLoggingEnabled
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  - Microsoft.Identity.Client.IAppConfig.get_IsDefaultPlatformLoggingEnabled
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.IsDefaultPlatformLoggingEnabled
  - Microsoft::Identity::Client::IAppConfig::IsDefaultPlatformLoggingEnabled
  - IsDefaultPlatformLoggingEnabled
  - IAppConfig.IsDefaultPlatformLoggingEnabled
  - IAppConfig::IsDefaultPlatformLoggingEnabled
  helpviewer_keywords:
  - IAppConfig.IsDefaultPlatformLoggingEnabled property [.NET]
  - IsDefaultPlatformLoggingEnabled property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
