### YamlMime:NetType
typeParameters:
- description: The type of the configuration metadata.
  name: T
type: interface
derivedClassesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
- value: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever
methods:
- uid: Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1.GetConfigurationAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1
commentId: T:Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1
namespace: Microsoft.IdentityModel.Protocols
name: IConfigurationRetriever<T>
fullName: Microsoft.IdentityModel.Protocols.IConfigurationRetriever<T>
nameWithType: Microsoft.IdentityModel.Protocols.IConfigurationRetriever<T>
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public interface IConfigurationRetriever<T>
- lang: fsharp
  values:
  - value: type IConfigurationRetriever<'T> = interface
- lang: vb
  values:
  - value: Public Interface IConfigurationRetriever(Of T)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Interface that defines methods to retrieve configuration.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1
  - Microsoft::IdentityModel::Protocols::IConfigurationRetriever`1
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever
  - IConfigurationRetriever`1
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationRetriever<T> interface [.NET]
  monikers:
  - msal-web-dotnet-latest
