### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ITokenCache?alt=Microsoft.Identity.Client.ITokenCache&text=ITokenCache" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  commentId: P:Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  name: UserTokenCache
  fullName: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  nameWithType: IClientApplicationBase.UserTokenCache
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.ITokenCache UserTokenCache { get; }
  - lang: fsharp
    values:
    - value: 'member this.UserTokenCache : Microsoft.Identity.Client.ITokenCache'
  - lang: vb
    values:
    - value: Public ReadOnly Property UserTokenCache As ITokenCache
  monikers:
  - msal-dotnet-latest
  summary: >-
    User token cache. This case holds id tokens, access tokens and refresh tokens for accounts. It's used

    and updated silently if needed when calling <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)"></xref>

    It is updated by each AcquireTokenXXX method, with the exception of <code data-dev-comment-type="c">AcquireTokenForClient</code> which only uses the application

    cache (see <code data-dev-comment-type="c">IConfidentialClientApplication</code>).
  remarks: <p>On .NET Framework and .NET Core you can also customize the token cache serialization. See https://aka.ms/msal-net-token-cache-serialization. This is taken care of by MSAL.NET on other platforms.</p>
  metadata: {}
uid: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache*
commentId: Overload:Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
namespace: Microsoft.Identity.Client
name: UserTokenCache
fullName: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
nameWithType: IClientApplicationBase.UserTokenCache
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  - Microsoft.Identity.Client.IClientApplicationBase.get_UserTokenCache
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  - Microsoft::Identity::Client::IClientApplicationBase::UserTokenCache
  - UserTokenCache
  - IClientApplicationBase.UserTokenCache
  - IClientApplicationBase::UserTokenCache
  helpviewer_keywords:
  - IClientApplicationBase.UserTokenCache property [.NET]
  - UserTokenCache property [.NET], interface IClientApplicationBase
  monikers:
  - msal-dotnet-latest
