### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IClientApplicationBase.ClientId
  commentId: P:Microsoft.Identity.Client.IClientApplicationBase.ClientId
  name: ClientId
  fullName: Microsoft.Identity.Client.IClientApplicationBase.ClientId
  nameWithType: IClientApplicationBase.ClientId
  attributesWithMoniker:
  - value: System.ObsoleteAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [System.Obsolete("Use AppConfig.ClientId instead.See https://aka.ms/msal-net-3-breaking-changes. ", true)]

        public string ClientId { get; }
  - lang: fsharp
    values:
    - value: >-
        [<System.Obsolete("Use AppConfig.ClientId instead.See https://aka.ms/msal-net-3-breaking-changes. ", true)>]

        member this.ClientId : string
  - lang: vb
    values:
    - value: Public ReadOnly Property ClientId As String
  monikers:
  - msal-dotnet-latest
  obsoleteMessagesWithMoniker:
  - value: 'Use AppConfig.ClientId instead.See https://aka.ms/msal-net-3-breaking-changes. '
  summary: >-
    Gets the Client ID (also known as Application ID) of the application as registered in the application registration portal (https://aka.ms/msal-net-register-app)

    and as passed in the constructor of the application.
  metadata: {}
uid: Microsoft.Identity.Client.IClientApplicationBase.ClientId*
commentId: Overload:Microsoft.Identity.Client.IClientApplicationBase.ClientId
namespace: Microsoft.Identity.Client
name: ClientId
fullName: Microsoft.Identity.Client.IClientApplicationBase.ClientId
nameWithType: IClientApplicationBase.ClientId
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IClientApplicationBase.ClientId
  - Microsoft.Identity.Client.IClientApplicationBase.get_ClientId
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IClientApplicationBase.ClientId
  - Microsoft::Identity::Client::IClientApplicationBase::ClientId
  - ClientId
  - IClientApplicationBase.ClientId
  - IClientApplicationBase::ClientId
  helpviewer_keywords:
  - IClientApplicationBase.ClientId property [.NET]
  - ClientId property [.NET], interface IClientApplicationBase
  monikers:
  - msal-dotnet-latest
