### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  name: UseLastKnownGoodConfiguration
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  nameWithType: BaseConfigurationManager.UseLastKnownGoodConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool UseLastKnownGoodConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.UseLastKnownGoodConfiguration : bool with get, set'
  - lang: vb
    values:
    - value: Public Property UseLastKnownGoodConfiguration As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: Indicates whether the last known good feature should be used, true by default.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
namespace: Microsoft.IdentityModel.Tokens
name: UseLastKnownGoodConfiguration
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
nameWithType: BaseConfigurationManager.UseLastKnownGoodConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_UseLastKnownGoodConfiguration
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_UseLastKnownGoodConfiguration
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.UseLastKnownGoodConfiguration
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::UseLastKnownGoodConfiguration
  - UseLastKnownGoodConfiguration
  - BaseConfigurationManager.UseLastKnownGoodConfiguration
  - BaseConfigurationManager::UseLastKnownGoodConfiguration
  helpviewer_keywords:
  - BaseConfigurationManager.UseLastKnownGoodConfiguration property [.NET]
  - UseLastKnownGoodConfiguration property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
