### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor
  commentId: M:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor
  name: MicrosoftIdentityApplicationOptions()
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.MicrosoftIdentityApplicationOptions()
  nameWithType: MicrosoftIdentityApplicationOptions.MicrosoftIdentityApplicationOptions()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public MicrosoftIdentityApplicationOptions ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-model-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor
namespace: Microsoft.Identity.Abstractions
name: MicrosoftIdentityApplicationOptions
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.MicrosoftIdentityApplicationOptions
nameWithType: MicrosoftIdentityApplicationOptions.MicrosoftIdentityApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions..ctor
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.#ctor
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::#ctor
  - '#ctor'
  - MicrosoftIdentityApplicationOptions.#ctor
  - MicrosoftIdentityApplicationOptions::#ctor
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions class [.NET], constructors
  - MicrosoftIdentityApplicationOptions() class [.NET], constructors
  monikers:
  - msal-model-dotnet-latest
