### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  name: RefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  nameWithType: BaseConfigurationManager.RefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public TimeSpan RefreshInterval { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.RefreshInterval : TimeSpan with get, set'
  - lang: vb
    values:
    - value: Public Property RefreshInterval As TimeSpan
  monikers:
  - msal-web-dotnet-latest
  summary: The minimum time between retrievals, in the event that a retrieval failed, or that a refresh was explicitly requested.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
namespace: Microsoft.IdentityModel.Tokens
name: RefreshInterval
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
nameWithType: BaseConfigurationManager.RefreshInterval
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_RefreshInterval
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_RefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.RefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::RefreshInterval
  - RefreshInterval
  - BaseConfigurationManager.RefreshInterval
  - BaseConfigurationManager::RefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.RefreshInterval property [.NET]
  - RefreshInterval property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
