### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationValidator`1?alt=Microsoft.IdentityModel.Protocols.IConfigurationValidator&text=IConfigurationValidator" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>&gt;
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.#ctor
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  monikers:
  - msal-web-dotnet-latest
properties:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.MinimumNumberOfKeys
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
commentId: T:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
name: OpenIdConnectConfigurationValidator
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
nameWithType: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class OpenIdConnectConfigurationValidator : Microsoft.IdentityModel.Protocols.IConfigurationValidator<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>'
- lang: fsharp
  values:
  - value: >-
      type OpenIdConnectConfigurationValidator = class
          interface IConfigurationValidator<OpenIdConnectConfiguration>
- lang: vb
  values:
  - value: >-
      Public Class OpenIdConnectConfigurationValidator

      Implements IConfigurationValidator(Of OpenIdConnectConfiguration)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Defines a class for validating the OpenIdConnectConfiguration by using default policy.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::Configuration::OpenIdConnectConfigurationValidator
  - OpenIdConnectConfigurationValidator
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator class [.NET]
  monikers:
  - msal-web-dotnet-latest
