### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  name: ShouldSerializeClaimsLocalesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeClaimsLocalesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeClaimsLocalesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeClaimsLocalesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'claims_locales_supported' (ClaimsLocalesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeClaimsLocalesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeClaimsLocalesSupported
  - ShouldSerializeClaimsLocalesSupported
  - OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported
  - OpenIdConnectConfiguration::ShouldSerializeClaimsLocalesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported method [.NET]
  - ShouldSerializeClaimsLocalesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeClaimsLocalesSupported() method [.NET]
  - ShouldSerializeClaimsLocalesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
