### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor
  name: WsFederationConfigurationRetriever()
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.WsFederationConfigurationRetriever()
  nameWithType: WsFederationConfigurationRetriever.WsFederationConfigurationRetriever()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public WsFederationConfigurationRetriever ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: WsFederationConfigurationRetriever
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.WsFederationConfigurationRetriever
nameWithType: WsFederationConfigurationRetriever.WsFederationConfigurationRetriever
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.#ctor
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfigurationRetriever::#ctor
  - '#ctor'
  - WsFederationConfigurationRetriever.#ctor
  - WsFederationConfigurationRetriever::#ctor
  helpviewer_keywords:
  - WsFederationConfigurationRetriever class [.NET], constructors
  - WsFederationConfigurationRetriever() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
