### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  name: ShouldSerializeClaimTypesSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeClaimTypesSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeClaimTypesSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeClaimTypesSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'claim_types_supported' (ClaimTypesSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeClaimTypesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeClaimTypesSupported
  - ShouldSerializeClaimTypesSupported
  - OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported
  - OpenIdConnectConfiguration::ShouldSerializeClaimTypesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported method [.NET]
  - ShouldSerializeClaimTypesSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeClaimTypesSupported() method [.NET]
  - ShouldSerializeClaimTypesSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
