### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  name: ShouldSerializeSigningKeys()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeSigningKeys()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeSigningKeys ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeSigningKeys : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeSigningKeys () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'SigningKeys' property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeSigningKeys
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
nameWithType: OpenIdConnectConfiguration.ShouldSerializeSigningKeys
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeSigningKeys
  - ShouldSerializeSigningKeys
  - OpenIdConnectConfiguration.ShouldSerializeSigningKeys
  - OpenIdConnectConfiguration::ShouldSerializeSigningKeys
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeSigningKeys method [.NET]
  - ShouldSerializeSigningKeys method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeSigningKeys() method [.NET]
  - ShouldSerializeSigningKeys() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
