### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Protocols.ConfigurationValidationResult?alt=Microsoft.IdentityModel.Protocols.ConfigurationValidationResult&text=ConfigurationValidationResult" data-throw-if-not-resolved="True"/>
    description: A <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationValidationResult"></xref> that contains validation result.
  parameters:
  - namesWithMoniker:
    - value: openIdConnectConfiguration
    description: The OpenIdConnectConfiguration to validate.
    type: <xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>
  implementsWithMoniker:
  - value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate(`0)?alt=Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate(`0)&text=Validate(T)" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate(Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration)
  name: Validate(OpenIdConnectConfiguration)
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate(OpenIdConnectConfiguration)
  nameWithType: OpenIdConnectConfigurationValidator.Validate(OpenIdConnectConfiguration)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Protocols.ConfigurationValidationResult Validate (Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration openIdConnectConfiguration);
  - lang: fsharp
    values:
    - value: >-
        abstract member Validate : Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration -> Microsoft.IdentityModel.Protocols.ConfigurationValidationResult

        override this.Validate : Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration -> Microsoft.IdentityModel.Protocols.ConfigurationValidationResult
  - lang: vb
    values:
    - value: Public Function Validate (openIdConnectConfiguration As OpenIdConnectConfiguration) As ConfigurationValidationResult
  monikers:
  - msal-web-dotnet-latest
  summary: Validates a OpenIdConnectConfiguration by using current policy.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration
name: Validate
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate
nameWithType: OpenIdConnectConfigurationValidator.Validate
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator.Validate
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::Configuration::OpenIdConnectConfigurationValidator::Validate
  - Validate
  - OpenIdConnectConfigurationValidator.Validate
  - OpenIdConnectConfigurationValidator::Validate
  helpviewer_keywords:
  - OpenIdConnectConfigurationValidator.Validate method [.NET]
  - Validate method [.NET], class OpenIdConnectConfigurationValidator
  - OpenIdConnectConfigurationValidator.Validate(OpenIdConnectConfiguration) method [.NET]
  - Validate(OpenIdConnectConfiguration) method [.NET], class OpenIdConnectConfigurationValidator
  monikers:
  - msal-web-dotnet-latest
