### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.SigningCredentials?alt=Microsoft.IdentityModel.Tokens.SigningCredentials&text=SigningCredentials" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  commentId: P:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  name: SigningCredentials
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  nameWithType: WsFederationConfiguration.SigningCredentials
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.SigningCredentials SigningCredentials { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.SigningCredentials : Microsoft.IdentityModel.Tokens.SigningCredentials with get, set'
  - lang: vb
    values:
    - value: Public Property SigningCredentials As SigningCredentials
  monikers:
  - msal-web-dotnet-latest
  summary: The <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Tokens.SigningCredentials"></xref> that was used to sign the metadata.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: SigningCredentials
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
nameWithType: WsFederationConfiguration.SigningCredentials
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.get_SigningCredentials
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.set_SigningCredentials
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.SigningCredentials
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration::SigningCredentials
  - SigningCredentials
  - WsFederationConfiguration.SigningCredentials
  - WsFederationConfiguration::SigningCredentials
  helpviewer_keywords:
  - WsFederationConfiguration.SigningCredentials property [.NET]
  - SigningCredentials property [.NET], class WsFederationConfiguration
  monikers:
  - msal-web-dotnet-latest
