### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  commentId: P:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  name: ErrorMessage
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  nameWithType: ConfigurationValidationResult.ErrorMessage
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string ErrorMessage { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ErrorMessage : string with get, set'
  - lang: vb
    values:
    - value: Public Property ErrorMessage As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the error message that occurred during validation of the configuration.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage*
commentId: Overload:Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
namespace: Microsoft.IdentityModel.Protocols
name: ErrorMessage
fullName: Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
nameWithType: ConfigurationValidationResult.ErrorMessage
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.get_ErrorMessage
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.set_ErrorMessage
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationValidationResult.ErrorMessage
  - Microsoft::IdentityModel::Protocols::ConfigurationValidationResult::ErrorMessage
  - ErrorMessage
  - ConfigurationValidationResult.ErrorMessage
  - ConfigurationValidationResult::ErrorMessage
  helpviewer_keywords:
  - ConfigurationValidationResult.ErrorMessage property [.NET]
  - ErrorMessage property [.NET], class ConfigurationValidationResult
  monikers:
  - msal-web-dotnet-latest
