### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.IdentityModel.Protocols.IConfigurationRetriever`1?alt=Microsoft.IdentityModel.Protocols.IConfigurationRetriever&text=IConfigurationRetriever" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration?alt=Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration&text=OpenIdConnectConfiguration" data-throw-if-not-resolved="True"/>&gt;
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor
  monikers:
  - msal-web-dotnet-latest
methods:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
eiis:
- uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft#IdentityModel#Protocols#IConfigurationRetriever{Microsoft#IdentityModel#Protocols#OpenIdConnect#OpenIdConnectConfiguration}#GetConfigurationAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
commentId: T:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: OpenIdConnectConfigurationRetriever
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
nameWithType: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class OpenIdConnectConfigurationRetriever : Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>'
- lang: fsharp
  values:
  - value: >-
      type OpenIdConnectConfigurationRetriever = class
          interface IConfigurationRetriever<OpenIdConnectConfiguration>
- lang: vb
  values:
  - value: >-
      Public Class OpenIdConnectConfigurationRetriever

      Implements IConfigurationRetriever(Of OpenIdConnectConfiguration)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration"></xref> given an address.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfigurationRetriever
  - OpenIdConnectConfigurationRetriever
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever class [.NET]
  monikers:
  - msal-web-dotnet-latest
