### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: T
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: httpClientFactory
    description: HTTP client factory
    type: <xref href="Microsoft.Identity.Client.IMsalHttpClientFactory?alt=Microsoft.Identity.Client.IMsalHttpClientFactory&text=IMsalHttpClientFactory" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory)
  commentId: M:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory)
  name: WithHttpClientFactory(IMsalHttpClientFactory)
  fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory)
  nameWithType: AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public T WithHttpClientFactory (Microsoft.Identity.Client.IMsalHttpClientFactory httpClientFactory);
  - lang: fsharp
    values:
    - value: "member this.WithHttpClientFactory : Microsoft.Identity.Client.IMsalHttpClientFactory -> 'T"
  - lang: vb
    values:
    - value: Public Function WithHttpClientFactory (httpClientFactory As IMsalHttpClientFactory) As T
  monikers:
  - msal-dotnet-latest
  summary: >-
    Uses a specific <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IMsalHttpClientFactory"></xref> to communicate

    with the IdP. This enables advanced scenarios such as setting a proxy,

    or setting the Agent.
  remarks: <p>MSAL does not guarantee that it will not modify the HttpClient, for example by adding new headers. Prior to the changes needed in order to make MSAL's httpClients thread safe (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046/files), the httpClient had the possibility of throwing an exception stating "Properties can only be modified before sending the first request". MSAL's httpClient will no longer throw this exception after 4.19.0 (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.19.0) see (https://aka.ms/msal-httpclient-info) for more information.</p>
  metadata: {}
- returnsWithMoniker:
    type:
    - value: T
    description: The builder to chain the .With methods
  parameters:
  - namesWithMoniker:
    - value: httpClientFactory
    description: HTTP client factory
    type: <xref href="Microsoft.Identity.Client.IMsalHttpClientFactory?alt=Microsoft.Identity.Client.IMsalHttpClientFactory&text=IMsalHttpClientFactory" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: retryOnceOn5xx
    description: >-
      Configures MSAL to retry on 5xx server errors. When enabled (on by default), MSAL will wait 1 second after recieving
                  a 5xx error and then retry the http request again.
    type: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory,System.Boolean)
  commentId: M:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory(Microsoft.Identity.Client.IMsalHttpClientFactory,System.Boolean)
  name: WithHttpClientFactory(IMsalHttpClientFactory, Boolean)
  fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory, Boolean)
  nameWithType: AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory, Boolean)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public T WithHttpClientFactory (Microsoft.Identity.Client.IMsalHttpClientFactory httpClientFactory, bool retryOnceOn5xx);
  - lang: fsharp
    values:
    - value: "member this.WithHttpClientFactory : Microsoft.Identity.Client.IMsalHttpClientFactory * bool -> 'T"
  - lang: vb
    values:
    - value: Public Function WithHttpClientFactory (httpClientFactory As IMsalHttpClientFactory, retryOnceOn5xx As Boolean) As T
  monikers:
  - msal-dotnet-latest
  summary: >-
    Uses a specific <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IMsalHttpClientFactory"></xref> to communicate

    with the IdP. This enables advanced scenarios such as setting a proxy,

    or setting the Agent.
  remarks: <p>MSAL does not guarantee that it will not modify the HttpClient, for example by adding new headers. Prior to the changes needed in order to make MSAL's httpClients thread safe (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046/files), the httpClient had the possibility of throwing an exception stating "Properties can only be modified before sending the first request". MSAL's httpClient will no longer throw this exception after 4.19.0 (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.19.0) see (https://aka.ms/msal-httpclient-info) for more information. If you only want to configure the retryOnceOn5xx parameter, set httpClientFactory to null and MSAL will use the default http client.</p>
  metadata: {}
uid: Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory*
commentId: Overload:Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory
namespace: Microsoft.Identity.Client
name: WithHttpClientFactory
fullName: Microsoft.Identity.Client.AbstractApplicationBuilder<T>.WithHttpClientFactory
nameWithType: AbstractApplicationBuilder<T>.WithHttpClientFactory
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithHttpClientFactory
  - Microsoft::Identity::Client::AbstractApplicationBuilder`1::WithHttpClientFactory
  - Microsoft.Identity.Client.AbstractApplicationBuilder.WithHttpClientFactory
  - WithHttpClientFactory
  - AbstractApplicationBuilder`1.WithHttpClientFactory
  - AbstractApplicationBuilder`1::WithHttpClientFactory
  helpviewer_keywords:
  - AbstractApplicationBuilder<T>.WithHttpClientFactory method [.NET]
  - WithHttpClientFactory method [.NET], class AbstractApplicationBuilder<T>
  - AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory) method [.NET]
  - WithHttpClientFactory(IMsalHttpClientFactory) method [.NET], class AbstractApplicationBuilder<T>
  - AbstractApplicationBuilder<T>.WithHttpClientFactory(IMsalHttpClientFactory, Boolean) method [.NET]
  - WithHttpClientFactory(IMsalHttpClientFactory, Boolean) method [.NET], class AbstractApplicationBuilder<T>
  monikers:
  - msal-dotnet-latest
