### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder&text=MicrosoftIdentityAppCallsWebApiAuthenticationBuilder" data-throw-if-not-resolved="True"/>
    description: The authentication builder for chaining.
  parameters:
  - namesWithMoniker:
    - value: initialScopes
    description: Optional initial scopes to request.
    type: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: method
  uid: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(System.Collections.Generic.IEnumerable{System.String})
  commentId: M:Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(System.Collections.Generic.IEnumerable{System.String})
  name: EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<String>)
  fullName: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<String>)
  nameWithType: MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<String>)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder EnableTokenAcquisitionToCallDownstreamApi (System.Collections.Generic.IEnumerable<string>? initialScopes = default);
  - lang: fsharp
    values:
    - value: 'override this.EnableTokenAcquisitionToCallDownstreamApi : seq<string> -> Microsoft.Identity.Web.MicrosoftIdentityAppCallsWebApiAuthenticationBuilder'
  - lang: vb
    values:
    - value: Public Function EnableTokenAcquisitionToCallDownstreamApi (Optional initialScopes As IEnumerable(Of String) = Nothing) As MicrosoftIdentityAppCallsWebApiAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
  summary: Add support for the web app to acquire tokens to call an API.
  metadata: {}
uid: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi*
commentId: Overload:Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
namespace: Microsoft.Identity.Web
name: EnableTokenAcquisitionToCallDownstreamApi
fullName: Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
nameWithType: MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  - Microsoft::Identity::Web::MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration::EnableTokenAcquisitionToCallDownstreamApi
  - EnableTokenAcquisitionToCallDownstreamApi
  - MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  - MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration::EnableTokenAcquisitionToCallDownstreamApi
  helpviewer_keywords:
  - MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi method [.NET]
  - EnableTokenAcquisitionToCallDownstreamApi method [.NET], class MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  - MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<String>) method [.NET]
  - EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<String>) method [.NET], class MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration
  monikers:
  - msal-model-dotnet-latest
