### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor
  commentId: M:Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor
  name: IdentityApplicationOptions()
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.IdentityApplicationOptions()
  nameWithType: IdentityApplicationOptions.IdentityApplicationOptions()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public IdentityApplicationOptions ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-model-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor
namespace: Microsoft.Identity.Abstractions
name: IdentityApplicationOptions
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.IdentityApplicationOptions
nameWithType: IdentityApplicationOptions.IdentityApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions..ctor
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.#ctor
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::#ctor
  - '#ctor'
  - IdentityApplicationOptions.#ctor
  - IdentityApplicationOptions::#ctor
  helpviewer_keywords:
  - IdentityApplicationOptions class [.NET], constructors
  - IdentityApplicationOptions() class [.NET], constructors
  monikers:
  - msal-model-dotnet-latest
