### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  name: WithSpaAuthCode
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  nameWithType: MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool WithSpaAuthCode { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.WithSpaAuthCode : bool with get, set'
  - lang: vb
    values:
    - value: Public Property WithSpaAuthCode As Boolean
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    If set to <code data-dev-comment-type="c">true</code>, when the user signs-in in a web app, the application requests an auth code 

    for the frontend (single page application using MSAL.js for instance). This will allow the front end

    JavaScript code to bypass going to the authoriize endpoint (which requires reloading the page), by 

    directly redeeming the auth code to get access tokens to call APIs.

    See https://aka.ms/msal-net/hybrid-spa-sample for details. Only works for AAD, not B2C.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
namespace: Microsoft.Identity.Abstractions
name: WithSpaAuthCode
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
nameWithType: MicrosoftIdentityApplicationOptions.WithSpaAuthCode
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_WithSpaAuthCode
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_WithSpaAuthCode
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::WithSpaAuthCode
  - WithSpaAuthCode
  - MicrosoftIdentityApplicationOptions.WithSpaAuthCode
  - MicrosoftIdentityApplicationOptions::WithSpaAuthCode
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.WithSpaAuthCode property [.NET]
  - WithSpaAuthCode property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
