### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  name: AutomaticRefreshInterval
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  nameWithType: BaseConfigurationManager.AutomaticRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public TimeSpan AutomaticRefreshInterval { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.AutomaticRefreshInterval : TimeSpan with get, set'
  - lang: vb
    values:
    - value: Public Property AutomaticRefreshInterval As TimeSpan
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the <xref data-throw-if-not-resolved="true" uid="System.TimeSpan"></xref> that controls how often an automatic metadata refresh should occur.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
namespace: Microsoft.IdentityModel.Tokens
name: AutomaticRefreshInterval
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
nameWithType: BaseConfigurationManager.AutomaticRefreshInterval
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_AutomaticRefreshInterval
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.set_AutomaticRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.AutomaticRefreshInterval
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::AutomaticRefreshInterval
  - AutomaticRefreshInterval
  - BaseConfigurationManager.AutomaticRefreshInterval
  - BaseConfigurationManager::AutomaticRefreshInterval
  helpviewer_keywords:
  - BaseConfigurationManager.AutomaticRefreshInterval property [.NET]
  - AutomaticRefreshInterval property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
