### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration?alt=Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration&text=WsFederationConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the metadata document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: if <code data-dev-comment-type="paramref">address</code> is null or empty.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Threading.CancellationToken)
  name: GetAsync(String, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(String, CancellationToken)
  nameWithType: WsFederationConfigurationRetriever.GetAsync(String, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration> GetAsync (string address, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, cancel As CancellationToken) As Task(Of WsFederationConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> given an address.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration?alt=Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration&text=WsFederationConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the metadata document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: retriever
    description: the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref> to use to read the metadata document
    type: <xref href="Microsoft.IdentityModel.Protocols.IDocumentRetriever?alt=Microsoft.IdentityModel.Protocols.IDocumentRetriever&text=IDocumentRetriever" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: if <code data-dev-comment-type="paramref">retriever</code> is null.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,Microsoft.IdentityModel.Protocols.IDocumentRetriever,System.Threading.CancellationToken)
  name: GetAsync(String, IDocumentRetriever, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken)
  nameWithType: WsFederationConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration> GetAsync (string address, Microsoft.IdentityModel.Protocols.IDocumentRetriever retriever, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * Microsoft.IdentityModel.Protocols.IDocumentRetriever * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, retriever As IDocumentRetriever, cancel As CancellationToken) As Task(Of WsFederationConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> given an address and an <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.IDocumentRetriever"></xref>.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration?alt=Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration&text=WsFederationConfiguration" data-throw-if-not-resolved="True"/>&gt;
    description: A populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> instance.
  parameters:
  - namesWithMoniker:
    - value: address
    description: address of the metadata document.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: httpClient
    description: the <xref data-throw-if-not-resolved="true" uid="System.Net.Http.HttpClient"></xref> to use to read the metadata document.
    type: <xref href="System.Net.Http.HttpClient?alt=System.Net.Http.HttpClient&text=HttpClient" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancel
    description: a <xref data-throw-if-not-resolved="true" uid="System.Threading.CancellationToken"></xref>.
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  exceptions:
  - description: if <code data-dev-comment-type="paramref">httpClient</code> is null.
    type: <xref href="System.ArgumentNullException" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  commentId: M:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(System.String,System.Net.Http.HttpClient,System.Threading.CancellationToken)
  name: GetAsync(String, HttpClient, CancellationToken)
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken)
  nameWithType: WsFederationConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration> GetAsync (string address, System.Net.Http.HttpClient httpClient, System.Threading.CancellationToken cancel);
  - lang: fsharp
    values:
    - value: 'static member GetAsync : string * System.Net.Http.HttpClient * System.Threading.CancellationToken -> System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration>'
  - lang: vb
    values:
    - value: Public Shared Function GetAsync (address As String, httpClient As HttpClient, cancel As CancellationToken) As Task(Of WsFederationConfiguration)
  monikers:
  - msal-web-dotnet-latest
  summary: Retrieves a populated <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref> given an address and an <xref data-throw-if-not-resolved="true" uid="System.Net.Http.HttpClient"></xref>.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: GetAsync
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync
nameWithType: WsFederationConfigurationRetriever.GetAsync
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.GetAsync
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfigurationRetriever::GetAsync
  - GetAsync
  - WsFederationConfigurationRetriever.GetAsync
  - WsFederationConfigurationRetriever::GetAsync
  helpviewer_keywords:
  - WsFederationConfigurationRetriever.GetAsync method [.NET]
  - GetAsync method [.NET], class WsFederationConfigurationRetriever
  - WsFederationConfigurationRetriever.GetAsync(String, CancellationToken) method [.NET]
  - GetAsync(String, CancellationToken) method [.NET], class WsFederationConfigurationRetriever
  - WsFederationConfigurationRetriever.GetAsync(String, IDocumentRetriever, CancellationToken) method [.NET]
  - GetAsync(String, IDocumentRetriever, CancellationToken) method [.NET], class WsFederationConfigurationRetriever
  - WsFederationConfigurationRetriever.GetAsync(String, HttpClient, CancellationToken) method [.NET]
  - GetAsync(String, HttpClient, CancellationToken) method [.NET], class WsFederationConfigurationRetriever
  monikers:
  - msal-web-dotnet-latest
