### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
    description: Boolean indicating if Proof-of-Possession is supported
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
  commentId: M:Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
  name: IsProofOfPossessionSupportedByClient()
  fullName: Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient()
  nameWithType: PublicClientApplication.IsProofOfPossessionSupportedByClient()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsProofOfPossessionSupportedByClient ();
  - lang: fsharp
    values:
    - value: 'member this.IsProofOfPossessionSupportedByClient : unit -> bool'
  - lang: vb
    values:
    - value: Public Function IsProofOfPossessionSupportedByClient () As Boolean
  monikers:
  - msal-dotnet-latest
  summary: Used to determine if the currently available broker is able to perform Proof-of-Possession.
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
namespace: Microsoft.Identity.Client
name: IsProofOfPossessionSupportedByClient
fullName: Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
nameWithType: PublicClientApplication.IsProofOfPossessionSupportedByClient
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplication.IsProofOfPossessionSupportedByClient
  - Microsoft::Identity::Client::PublicClientApplication::IsProofOfPossessionSupportedByClient
  - IsProofOfPossessionSupportedByClient
  - PublicClientApplication.IsProofOfPossessionSupportedByClient
  - PublicClientApplication::IsProofOfPossessionSupportedByClient
  helpviewer_keywords:
  - PublicClientApplication.IsProofOfPossessionSupportedByClient method [.NET]
  - IsProofOfPossessionSupportedByClient method [.NET], class PublicClientApplication
  - PublicClientApplication.IsProofOfPossessionSupportedByClient() method [.NET]
  - IsProofOfPossessionSupportedByClient() method [.NET], class PublicClientApplication
  monikers:
  - msal-dotnet-latest
