### YamlMime:NetType
typeParameters:
- description: The type of the configuration metadata.
  name: T
type: interface
derivedClassesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.Configuration.OpenIdConnectConfigurationValidator
methods:
- uid: Microsoft.IdentityModel.Protocols.IConfigurationValidator`1.Validate(`0)
  monikers:
  - msal-web-dotnet-latest
uid: Microsoft.IdentityModel.Protocols.IConfigurationValidator`1
commentId: T:Microsoft.IdentityModel.Protocols.IConfigurationValidator`1
namespace: Microsoft.IdentityModel.Protocols
name: IConfigurationValidator<T>
fullName: Microsoft.IdentityModel.Protocols.IConfigurationValidator<T>
nameWithType: Microsoft.IdentityModel.Protocols.IConfigurationValidator<T>
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public interface IConfigurationValidator<T>
- lang: fsharp
  values:
  - value: type IConfigurationValidator<'T> = interface
- lang: vb
  values:
  - value: Public Interface IConfigurationValidator(Of T)
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
summary: Interface that defines a policy for validating configuration data.
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator`1
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator`1
  - Microsoft::IdentityModel::Protocols::IConfigurationValidator`1
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator
  - IConfigurationValidator`1
  helpviewer_keywords:
  - Microsoft.IdentityModel.Protocols.IConfigurationValidator<T> interface [.NET]
  monikers:
  - msal-web-dotnet-latest
