### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  commentId: P:Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  name: IsSystemWebViewAvailable
  fullName: Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  nameWithType: IPublicClientApplication.IsSystemWebViewAvailable
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsSystemWebViewAvailable { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsSystemWebViewAvailable : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsSystemWebViewAvailable As Boolean
  monikers:
  - msal-dotnet-latest
  summary: >-
    Tells if the application can use the system web browser, therefore getting single-sign-on with web applications.

    By default, MSAL will try to use a system browser on the mobile platforms, if it is available.

    See https://aka.ms/msal-net-uses-web-browser.
  metadata: {}
uid: Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable*
commentId: Overload:Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
namespace: Microsoft.Identity.Client
name: IsSystemWebViewAvailable
fullName: Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
nameWithType: IPublicClientApplication.IsSystemWebViewAvailable
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  - Microsoft.Identity.Client.IPublicClientApplication.get_IsSystemWebViewAvailable
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IPublicClientApplication.IsSystemWebViewAvailable
  - Microsoft::Identity::Client::IPublicClientApplication::IsSystemWebViewAvailable
  - IsSystemWebViewAvailable
  - IPublicClientApplication.IsSystemWebViewAvailable
  - IPublicClientApplication::IsSystemWebViewAvailable
  helpviewer_keywords:
  - IPublicClientApplication.IsSystemWebViewAvailable property [.NET]
  - IsSystemWebViewAvailable property [.NET], interface IPublicClientApplication
  monikers:
  - msal-dotnet-latest
