### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  commentId: P:Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  name: AzureRegion
  fullName: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  nameWithType: ConfidentialClientApplicationOptions.AzureRegion
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string AzureRegion { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.AzureRegion : string with get, set'
  - lang: vb
    values:
    - value: Public Property AzureRegion As String
  monikers:
  - msal-dotnet-latest
  summary: >-
    Instructs MSAL.NET to use an Azure regional token service.

    This setting should be set to either the string with the region (preferred) or to 

    "TryAutoDetect" and MSAL.NET will attempt to auto-detect the region.
  remarks: <p>Region names as per https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet. Not all auth flows can use the regional token service. Service To Service (client credential flow) tokens can be obtained from the regional service. Requires configuration at the tenant level. Auto-detection works on a limited number of Azure artifacts (VMs, Azure functions). If auto-detection fails, the non-regional endpoint will be used. If an invalid region name is provided, the non-regional endpoint MIGHT be used or the token request MIGHT fail. See https://aka.ms/msal-net-region-discovery for more details.</p>
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
namespace: Microsoft.Identity.Client
name: AzureRegion
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
nameWithType: ConfidentialClientApplicationOptions.AzureRegion
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions.get_AzureRegion
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions.set_AzureRegion
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion
  - Microsoft::Identity::Client::ConfidentialClientApplicationOptions::AzureRegion
  - AzureRegion
  - ConfidentialClientApplicationOptions.AzureRegion
  - ConfidentialClientApplicationOptions::AzureRegion
  helpviewer_keywords:
  - ConfidentialClientApplicationOptions.AzureRegion property [.NET]
  - AzureRegion property [.NET], class ConfidentialClientApplicationOptions
  monikers:
  - msal-dotnet-latest
