### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>&gt;&gt;
  parameters:
  - namesWithMoniker:
    - value: userFlow
    description: The identifier is the user flow being targeted by the specific B2C authority/&gt;.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: cancellationToken
    description: Cancellation token
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String,System.Threading.CancellationToken)
  name: GetAccountsAsync(String, CancellationToken)
  fullName: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(String, CancellationToken)
  nameWithType: ClientApplicationBase.GetAccountsAsync(String, CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.Identity.Client.IAccount>> GetAccountsAsync (string userFlow, System.Threading.CancellationToken cancellationToken = default);
  - lang: fsharp
    values:
    - value: 'member this.GetAccountsAsync : string * System.Threading.CancellationToken -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>'
  - lang: vb
    values:
    - value: Public Function GetAccountsAsync (userFlow As String, Optional cancellationToken As CancellationToken = Nothing) As Task(Of IEnumerable(Of IAccount))
  monikers:
  - msal-dotnet-latest
  summary: >-
    Get the <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IAccount"></xref> collection by its identifier among the accounts available in the token cache,

    based on the user flow. This is for Azure AD B2C scenarios.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>&gt;&gt;
  parameters:
  - namesWithMoniker:
    - value: cancellationToken
    type: <xref href="System.Threading.CancellationToken?alt=System.Threading.CancellationToken&text=CancellationToken" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.Threading.CancellationToken)
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.Threading.CancellationToken)
  name: GetAccountsAsync(CancellationToken)
  fullName: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(CancellationToken)
  nameWithType: ClientApplicationBase.GetAccountsAsync(CancellationToken)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.Identity.Client.IAccount>> GetAccountsAsync (System.Threading.CancellationToken cancellationToken = default);
  - lang: fsharp
    values:
    - value: 'member this.GetAccountsAsync : System.Threading.CancellationToken -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>'
  - lang: vb
    values:
    - value: Public Function GetAccountsAsync (Optional cancellationToken As CancellationToken = Nothing) As Task(Of IEnumerable(Of IAccount))
  monikers:
  - msal-dotnet-latest
  summary: Returns all the available <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IAccount" href="Microsoft.Identity.Client.IAccount?text=accounts"></xref> in the user token cache for the application.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>&gt;&gt;
  parameters:
  - namesWithMoniker:
    - value: userFlow
    description: The identifier is the user flow being targeted by the specific B2C authority/&gt;.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  implementsWithMoniker:
  - value: <xref href="Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync(System.String)?alt=Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync(System.String)&text=GetAccountsAsync(String)" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String)
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(System.String)
  name: GetAccountsAsync(String)
  fullName: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(String)
  nameWithType: ClientApplicationBase.GetAccountsAsync(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.Identity.Client.IAccount>> GetAccountsAsync (string userFlow);
  - lang: fsharp
    values:
    - value: >-
        abstract member GetAccountsAsync : string -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>

        override this.GetAccountsAsync : string -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>
  - lang: vb
    values:
    - value: Public Function GetAccountsAsync (userFlow As String) As Task(Of IEnumerable(Of IAccount))
  monikers:
  - msal-dotnet-latest
  summary: >-
    Get the <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IAccount"></xref> collection by its identifier among the accounts available in the token cache,

    based on the user flow. This is for Azure AD B2C scenarios.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="System.Threading.Tasks.Task`1?alt=System.Threading.Tasks.Task&text=Task" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.Identity.Client.IAccount?alt=Microsoft.Identity.Client.IAccount&text=IAccount" data-throw-if-not-resolved="True"/>&gt;&gt;
  implementsWithMoniker:
  - value: <xref href="Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync?alt=Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync&text=GetAccountsAsync()" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  commentId: M:Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  name: GetAccountsAsync()
  fullName: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync()
  nameWithType: ClientApplicationBase.GetAccountsAsync()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.Identity.Client.IAccount>> GetAccountsAsync ();
  - lang: fsharp
    values:
    - value: >-
        abstract member GetAccountsAsync : unit -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>

        override this.GetAccountsAsync : unit -> System.Threading.Tasks.Task<seq<Microsoft.Identity.Client.IAccount>>
  - lang: vb
    values:
    - value: Public Function GetAccountsAsync () As Task(Of IEnumerable(Of IAccount))
  monikers:
  - msal-dotnet-latest
  summary: Returns all the available <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IAccount" href="Microsoft.Identity.Client.IAccount?text=accounts"></xref> in the user token cache for the application.
  metadata: {}
uid: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync*
commentId: Overload:Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
namespace: Microsoft.Identity.Client
name: GetAccountsAsync
fullName: Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
nameWithType: ClientApplicationBase.GetAccountsAsync
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync
  - Microsoft::Identity::Client::ClientApplicationBase::GetAccountsAsync
  - GetAccountsAsync
  - ClientApplicationBase.GetAccountsAsync
  - ClientApplicationBase::GetAccountsAsync
  helpviewer_keywords:
  - ClientApplicationBase.GetAccountsAsync method [.NET]
  - GetAccountsAsync method [.NET], class ClientApplicationBase
  - ClientApplicationBase.GetAccountsAsync(String, CancellationToken) method [.NET]
  - GetAccountsAsync(String, CancellationToken) method [.NET], class ClientApplicationBase
  - ClientApplicationBase.GetAccountsAsync(CancellationToken) method [.NET]
  - GetAccountsAsync(CancellationToken) method [.NET], class ClientApplicationBase
  - ClientApplicationBase.GetAccountsAsync(String) method [.NET]
  - GetAccountsAsync(String) method [.NET], class ClientApplicationBase
  - ClientApplicationBase.GetAccountsAsync() method [.NET]
  - GetAccountsAsync() method [.NET], class ClientApplicationBase
  monikers:
  - msal-dotnet-latest
