### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.IdentityModel.Tokens.SecurityKey?alt=Microsoft.IdentityModel.Tokens.SecurityKey&text=SecurityKey" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  name: SigningKeys
  fullName: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  nameWithType: BaseConfiguration.SigningKeys
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public virtual System.Collections.Generic.ICollection<Microsoft.IdentityModel.Tokens.SecurityKey> SigningKeys { get; }
  - lang: fsharp
    values:
    - value: 'member this.SigningKeys : System.Collections.Generic.ICollection<Microsoft.IdentityModel.Tokens.SecurityKey>'
  - lang: vb
    values:
    - value: Public Overridable ReadOnly Property SigningKeys As ICollection(Of SecurityKey)
  monikers:
  - msal-web-dotnet-latest
  summary: Gets the <xref data-throw-if-not-resolved="true" uid="System.Collections.Generic.ICollection`1"></xref> that the IdentityProvider indicates are to be used in order to sign tokens.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
namespace: Microsoft.IdentityModel.Tokens
name: SigningKeys
fullName: Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
nameWithType: BaseConfiguration.SigningKeys
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  - Microsoft.IdentityModel.Tokens.BaseConfiguration.get_SigningKeys
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfiguration.SigningKeys
  - Microsoft::IdentityModel::Tokens::BaseConfiguration::SigningKeys
  - SigningKeys
  - BaseConfiguration.SigningKeys
  - BaseConfiguration::SigningKeys
  helpviewer_keywords:
  - BaseConfiguration.SigningKeys property [.NET]
  - SigningKeys property [.NET], class BaseConfiguration
  monikers:
  - msal-web-dotnet-latest
