### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Func`1?alt=System.Func&text=Func" data-throw-if-not-resolved="True"/>&lt;<xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  commentId: P:Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  name: ParentActivityOrWindowFunc
  fullName: Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  nameWithType: IAppConfig.ParentActivityOrWindowFunc
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Func<object> ParentActivityOrWindowFunc { get; }
  - lang: fsharp
    values:
    - value: 'member this.ParentActivityOrWindowFunc : Func<obj>'
  - lang: vb
    values:
    - value: Public ReadOnly Property ParentActivityOrWindowFunc As Func(Of Object)
  monikers:
  - msal-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc*
commentId: Overload:Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
namespace: Microsoft.Identity.Client
name: ParentActivityOrWindowFunc
fullName: Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
nameWithType: IAppConfig.ParentActivityOrWindowFunc
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  - Microsoft.Identity.Client.IAppConfig.get_ParentActivityOrWindowFunc
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IAppConfig.ParentActivityOrWindowFunc
  - Microsoft::Identity::Client::IAppConfig::ParentActivityOrWindowFunc
  - ParentActivityOrWindowFunc
  - IAppConfig.ParentActivityOrWindowFunc
  - IAppConfig::ParentActivityOrWindowFunc
  helpviewer_keywords:
  - IAppConfig.ParentActivityOrWindowFunc property [.NET]
  - ParentActivityOrWindowFunc property [.NET], interface IAppConfig
  monikers:
  - msal-dotnet-latest
