### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  name: OpPolicyUri
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  nameWithType: OpenIdConnectConfiguration.OpPolicyUri
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="op_policy_uri", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public string OpPolicyUri { get; set; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="op_policy_uri", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.OpPolicyUri : string with get, set
  - lang: vb
    values:
    - value: Public Property OpPolicyUri As String
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the 'op_policy_uri'
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: OpPolicyUri
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
nameWithType: OpenIdConnectConfiguration.OpPolicyUri
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_OpPolicyUri
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_OpPolicyUri
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.OpPolicyUri
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::OpPolicyUri
  - OpPolicyUri
  - OpenIdConnectConfiguration.OpPolicyUri
  - OpenIdConnectConfiguration::OpPolicyUri
  helpviewer_keywords:
  - OpenIdConnectConfiguration.OpPolicyUri property [.NET]
  - OpPolicyUri property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
