### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval
  commentId: F:Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval
  name: MinimumAutomaticRefreshInterval
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.MinimumAutomaticRefreshInterval
  nameWithType: ConfigurationManager<T>.MinimumAutomaticRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan MinimumAutomaticRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable MinimumAutomaticRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly MinimumAutomaticRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 5 minutes is the minimum value for automatic refresh. <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval"></xref> can not be set less than this value.
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumAutomaticRefreshInterval
  - Microsoft::IdentityModel::Protocols::ConfigurationManager`1::MinimumAutomaticRefreshInterval
  - Microsoft.IdentityModel.Protocols.ConfigurationManager.MinimumAutomaticRefreshInterval
  - MinimumAutomaticRefreshInterval
  - ConfigurationManager`1.MinimumAutomaticRefreshInterval
  - ConfigurationManager`1::MinimumAutomaticRefreshInterval
  helpviewer_keywords:
  - ConfigurationManager<T>.MinimumAutomaticRefreshInterval field [.NET]
  - MinimumAutomaticRefreshInterval field [.NET], class ConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
