### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  name: ShouldSerializeIntrospectionEndpointAuthMethodsSupported()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported()
  nameWithType: OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool ShouldSerializeIntrospectionEndpointAuthMethodsSupported ();
  - lang: fsharp
    values:
    - value: 'member this.ShouldSerializeIntrospectionEndpointAuthMethodsSupported : unit -> bool'
  - lang: vb
    values:
    - value: Public Function ShouldSerializeIntrospectionEndpointAuthMethodsSupported () As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: >-
    Gets a bool that determines if the 'introspection_endpoint_auth_methods_supported' (IntrospectionEndpointAuthMethodsSupported) property should be serialized.

    This is used by Json.NET in order to conditionally serialize properties.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: ShouldSerializeIntrospectionEndpointAuthMethodsSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
nameWithType: OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  - ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  - OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  - OpenIdConnectConfiguration::ShouldSerializeIntrospectionEndpointAuthMethodsSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported method [.NET]
  - ShouldSerializeIntrospectionEndpointAuthMethodsSupported method [.NET], class OpenIdConnectConfiguration
  - OpenIdConnectConfiguration.ShouldSerializeIntrospectionEndpointAuthMethodsSupported() method [.NET]
  - ShouldSerializeIntrospectionEndpointAuthMethodsSupported() method [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
