### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  name: ErrorPath
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  nameWithType: MicrosoftIdentityApplicationOptions.ErrorPath
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? ErrorPath { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ErrorPath : string with get, set'
  - lang: vb
    values:
    - value: Public Property ErrorPath As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Sets the Error route path.

    Defaults to the value /MicrosoftIdentity/Account/Error,

    which is the value used by Microsoft.Identity.Web.UI.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
namespace: Microsoft.Identity.Abstractions
name: ErrorPath
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
nameWithType: MicrosoftIdentityApplicationOptions.ErrorPath
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_ErrorPath
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_ErrorPath
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ErrorPath
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::ErrorPath
  - ErrorPath
  - MicrosoftIdentityApplicationOptions.ErrorPath
  - MicrosoftIdentityApplicationOptions::ErrorPath
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.ErrorPath property [.NET]
  - ErrorPath property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
