### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  commentId: P:Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  name: RequiredScopesConfigurationKey
  fullName: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  nameWithType: ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredScopesConfigurationKey { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredScopesConfigurationKey : string with get, set'
  - lang: vb
    values:
    - value: Public Property RequiredScopesConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets the optional list of scope values from configuration.
  metadata: {}
uid: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
namespace: Microsoft.Identity.Web
name: RequiredScopesConfigurationKey
fullName: Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
nameWithType: ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.get_RequiredScopesConfigurationKey
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.set_RequiredScopesConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  - Microsoft::Identity::Web::ScopeOrAppPermissionAuthorizationRequirement::RequiredScopesConfigurationKey
  - RequiredScopesConfigurationKey
  - ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey
  - ScopeOrAppPermissionAuthorizationRequirement::RequiredScopesConfigurationKey
  helpviewer_keywords:
  - ScopeOrAppPermissionAuthorizationRequirement.RequiredScopesConfigurationKey property [.NET]
  - RequiredScopesConfigurationKey property [.NET], class ScopeOrAppPermissionAuthorizationRequirement
  monikers:
  - msal-model-dotnet-latest
