### YamlMime:NetType
type: interface
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ConfidentialClientApplication
methods:
- uid: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate.AcquireTokenForClientWithCertificateAsync(System.Collections.Generic.IEnumerable{System.String},System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate.AcquireTokenForClientWithCertificateAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate.AcquireTokenOnBehalfOfWithCertificateAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate.AcquireTokenOnBehalfOfWithCertificateAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion)
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
commentId: T:Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
namespace: Microsoft.Identity.Client
name: IConfidentialClientApplicationWithCertificate
fullName: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
nameWithType: Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public interface IConfidentialClientApplicationWithCertificate
- lang: fsharp
  values:
  - value: type IConfidentialClientApplicationWithCertificate = interface
- lang: vb
  values:
  - value: Public Interface IConfidentialClientApplicationWithCertificate
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: >-
  Component to be used with confidential client applications like web apps/APIs.

  This component supports Subject Name + Issuer authentication in order to help, in the future,

  Azure AD certificates rollover.
metadata:
  api_name:
  - Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate
  - Microsoft::Identity::Client::IConfidentialClientApplicationWithCertificate
  - IConfidentialClientApplicationWithCertificate
  helpviewer_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplicationWithCertificate interface [.NET]
  monikers:
  - msal-dotnet-latest
