### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.TelemetryAudienceType?alt=Microsoft.Identity.Client.TelemetryAudienceType&text=TelemetryAudienceType" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  commentId: P:Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  name: AudienceType
  fullName: Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  nameWithType: ITelemetryConfig.AudienceType
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.TelemetryAudienceType AudienceType { get; }
  - lang: fsharp
    values:
    - value: 'member this.AudienceType : Microsoft.Identity.Client.TelemetryAudienceType'
  - lang: vb
    values:
    - value: Public ReadOnly Property AudienceType As TelemetryAudienceType
  monikers:
  - msal-dotnet-latest
  summary: >-
    Communicates which audience the telemetry is for (e.g. Production or Pre-Production) so that MSAL.NET can change sampling

    and filtering behavior.
  remarks: This API is experimental and it may change in future versions of the library without an major version increment
  metadata: {}
uid: Microsoft.Identity.Client.ITelemetryConfig.AudienceType*
commentId: Overload:Microsoft.Identity.Client.ITelemetryConfig.AudienceType
namespace: Microsoft.Identity.Client
name: AudienceType
fullName: Microsoft.Identity.Client.ITelemetryConfig.AudienceType
nameWithType: ITelemetryConfig.AudienceType
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  - Microsoft.Identity.Client.ITelemetryConfig.get_AudienceType
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  - Microsoft::Identity::Client::ITelemetryConfig::AudienceType
  - AudienceType
  - ITelemetryConfig.AudienceType
  - ITelemetryConfig::AudienceType
  helpviewer_keywords:
  - ITelemetryConfig.AudienceType property [.NET]
  - AudienceType property [.NET], interface ITelemetryConfig
  monikers:
  - msal-dotnet-latest
