### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration?alt=Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration&text=PoPAuthenticationConfiguration" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
  commentId: P:Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
  name: PoPConfiguration
  fullName: Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
  nameWithType: TokenAcquisitionOptions.PoPConfiguration
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration? PoPConfiguration { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.PoPConfiguration : Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration with get, set'
  - lang: vb
    values:
    - value: Public Property PoPConfiguration As PoPAuthenticationConfiguration
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Modifies the token acquisition request so that the acquired token is a Proof of Possession token (PoP),

    rather than a Bearer token.

    PoP tokens are similar to Bearer tokens, but are bound to the HTTP request and to a cryptographic key,

    which MSAL can manage. See https://aka.ms/msal-net-pop.
  metadata: {}
uid: Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration*
commentId: Overload:Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
namespace: Microsoft.Identity.Web
name: PoPConfiguration
fullName: Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
nameWithType: TokenAcquisitionOptions.PoPConfiguration
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
  - Microsoft.Identity.Web.TokenAcquisitionOptions.get_PoPConfiguration
  - Microsoft.Identity.Web.TokenAcquisitionOptions.set_PoPConfiguration
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.TokenAcquisitionOptions.PoPConfiguration
  - Microsoft::Identity::Web::TokenAcquisitionOptions::PoPConfiguration
  - PoPConfiguration
  - TokenAcquisitionOptions.PoPConfiguration
  - TokenAcquisitionOptions::PoPConfiguration
  helpviewer_keywords:
  - TokenAcquisitionOptions.PoPConfiguration property [.NET]
  - PoPConfiguration property [.NET], class TokenAcquisitionOptions
  monikers:
  - msal-model-dotnet-latest
