### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  commentId: P:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  name: IsLastKnownGoodValid
  fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  nameWithType: BaseConfigurationManager.IsLastKnownGoodValid
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsLastKnownGoodValid { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsLastKnownGoodValid : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsLastKnownGoodValid As Boolean
  monikers:
  - msal-web-dotnet-latest
  summary: Indicates whether the last known good configuration is still fresh, depends on when the LKG was first used and it's lifetime.
  metadata: {}
uid: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid*
commentId: Overload:Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
namespace: Microsoft.IdentityModel.Tokens
name: IsLastKnownGoodValid
fullName: Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
nameWithType: BaseConfigurationManager.IsLastKnownGoodValid
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Tokens.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Tokens v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.get_IsLastKnownGoodValid
  api_location:
  - Microsoft.IdentityModel.Tokens.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Tokens.BaseConfigurationManager.IsLastKnownGoodValid
  - Microsoft::IdentityModel::Tokens::BaseConfigurationManager::IsLastKnownGoodValid
  - IsLastKnownGoodValid
  - BaseConfigurationManager.IsLastKnownGoodValid
  - BaseConfigurationManager::IsLastKnownGoodValid
  helpviewer_keywords:
  - BaseConfigurationManager.IsLastKnownGoodValid property [.NET]
  - IsLastKnownGoodValid property [.NET], class BaseConfigurationManager
  monikers:
  - msal-web-dotnet-latest
