### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  name: DefaultUserFlow
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  nameWithType: MicrosoftIdentityApplicationOptions.DefaultUserFlow
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? DefaultUserFlow { get; }
  - lang: fsharp
    values:
    - value: 'member this.DefaultUserFlow : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property DefaultUserFlow As String
  monikers:
  - msal-model-dotnet-latest
  summary: Gets the default user flow (which is signUpsignIn).
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
namespace: Microsoft.Identity.Abstractions
name: DefaultUserFlow
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
nameWithType: MicrosoftIdentityApplicationOptions.DefaultUserFlow
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_DefaultUserFlow
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.DefaultUserFlow
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::DefaultUserFlow
  - DefaultUserFlow
  - MicrosoftIdentityApplicationOptions.DefaultUserFlow
  - MicrosoftIdentityApplicationOptions::DefaultUserFlow
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.DefaultUserFlow property [.NET]
  - DefaultUserFlow property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
