### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IDictionary`2?alt=System.Collections.Generic.IDictionary&text=IDictionary" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>,<xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  name: AdditionalData
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  nameWithType: OpenIdConnectConfiguration.AdditionalData
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonExtensionDataAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonExtensionData]

        public virtual System.Collections.Generic.IDictionary<string,object> AdditionalData { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonExtensionData>]

        member this.AdditionalData : System.Collections.Generic.IDictionary<string, obj>
  - lang: vb
    values:
    - value: Public Overridable ReadOnly Property AdditionalData As IDictionary(Of String, Object)
  monikers:
  - msal-web-dotnet-latest
  summary: When deserializing from JSON any properties that are not defined will be placed here.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: AdditionalData
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
nameWithType: OpenIdConnectConfiguration.AdditionalData
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_AdditionalData
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.AdditionalData
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::AdditionalData
  - AdditionalData
  - OpenIdConnectConfiguration.AdditionalData
  - OpenIdConnectConfiguration::AdditionalData
  helpviewer_keywords:
  - OpenIdConnectConfiguration.AdditionalData property [.NET]
  - AdditionalData property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
