### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Client.PublicClientApplicationOptions.#ctor
  commentId: M:Microsoft.Identity.Client.PublicClientApplicationOptions.#ctor
  name: PublicClientApplicationOptions()
  fullName: Microsoft.Identity.Client.PublicClientApplicationOptions.PublicClientApplicationOptions()
  nameWithType: PublicClientApplicationOptions.PublicClientApplicationOptions()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public PublicClientApplicationOptions ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplicationOptions.#ctor*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplicationOptions.#ctor
namespace: Microsoft.Identity.Client
name: PublicClientApplicationOptions
fullName: Microsoft.Identity.Client.PublicClientApplicationOptions.PublicClientApplicationOptions
nameWithType: PublicClientApplicationOptions.PublicClientApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationOptions..ctor
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationOptions.#ctor
  - Microsoft::Identity::Client::PublicClientApplicationOptions::#ctor
  - '#ctor'
  - PublicClientApplicationOptions.#ctor
  - PublicClientApplicationOptions::#ctor
  helpviewer_keywords:
  - PublicClientApplicationOptions class [.NET], constructors
  - PublicClientApplicationOptions() class [.NET], constructors
  monikers:
  - msal-dotnet-latest
