### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
  commentId: M:Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
  name: IsBrokerAvailable()
  fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable()
  nameWithType: PublicClientApplicationBuilder.IsBrokerAvailable()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsBrokerAvailable ();
  - lang: fsharp
    values:
    - value: 'member this.IsBrokerAvailable : unit -> bool'
  - lang: vb
    values:
    - value: Public Function IsBrokerAvailable () As Boolean
  monikers:
  - msal-dotnet-latest
  summary: >-
    Returns <code data-dev-comment-type="c">true</code> if a broker can be used.

    This method is only needed to be used in mobile scenarios which support Mobile Application Management. In other supported scenarios, use <code data-dev-comment-type="c">WithBroker</code> by itself, which will fall back to use a browser if broker is unavailable.
  remarks: <ul><li>On Windows, the broker (WAM) can be used on Windows 10 and is always installed. See https://aka.ms/msal-net-wam </li><li>On Mac, Linux, and older versions of Windows a broker is not available.</li><li>In .NET 6 apps, target <code data-dev-comment-type="c">net6.0-windows10.0.17763.0</code> for all Windows versions and target <code data-dev-comment-type="c">net6.0</code> for Linux and Mac.</li><li>In .NET classic or .NET Core 3.1 apps, install Microsoft.Identity.Client.Desktop first and call <code data-dev-comment-type="c">WithDesktopFeatures()</code>.</li><li>In mobile apps, the device must be Intune joined and Authenticator or Company Portal must be installed. See https://aka.ms/msal-brokers </li></ul>
  metadata: {}
uid: Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable*
commentId: Overload:Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
namespace: Microsoft.Identity.Client
name: IsBrokerAvailable
fullName: Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
nameWithType: PublicClientApplicationBuilder.IsBrokerAvailable
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.PublicClientApplicationBuilder.IsBrokerAvailable
  - Microsoft::Identity::Client::PublicClientApplicationBuilder::IsBrokerAvailable
  - IsBrokerAvailable
  - PublicClientApplicationBuilder.IsBrokerAvailable
  - PublicClientApplicationBuilder::IsBrokerAvailable
  helpviewer_keywords:
  - PublicClientApplicationBuilder.IsBrokerAvailable method [.NET]
  - IsBrokerAvailable method [.NET], class PublicClientApplicationBuilder
  - PublicClientApplicationBuilder.IsBrokerAvailable() method [.NET]
  - IsBrokerAvailable() method [.NET], class PublicClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
