### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  commentId: P:Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  name: EnablePiiLogging
  fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  nameWithType: IdentityApplicationOptions.EnablePiiLogging
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool EnablePiiLogging { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.EnablePiiLogging : bool with get, set'
  - lang: vb
    values:
    - value: Public Property EnablePiiLogging As Boolean
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Flag used to enable/disable logging of Personally Identifiable Information (PII).

    PII logs are never written to default outputs.

    Default is set to <code data-dev-comment-type="c">false</code>, which ensures that your application is compliant with GDPR. You can set

    it to <code data-dev-comment-type="c">true</code> for advanced debugging requiring PII.
  metadata: {}
uid: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging*
commentId: Overload:Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
namespace: Microsoft.Identity.Abstractions
name: EnablePiiLogging
fullName: Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
nameWithType: IdentityApplicationOptions.EnablePiiLogging
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.get_EnablePiiLogging
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.set_EnablePiiLogging
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.IdentityApplicationOptions.EnablePiiLogging
  - Microsoft::Identity::Abstractions::IdentityApplicationOptions::EnablePiiLogging
  - EnablePiiLogging
  - IdentityApplicationOptions.EnablePiiLogging
  - IdentityApplicationOptions::EnablePiiLogging
  helpviewer_keywords:
  - IdentityApplicationOptions.EnablePiiLogging property [.NET]
  - EnablePiiLogging property [.NET], class IdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
