### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor
  commentId: M:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor
  name: PoPAuthenticationConfiguration()
  fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PoPAuthenticationConfiguration()
  nameWithType: PoPAuthenticationConfiguration.PoPAuthenticationConfiguration()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public PoPAuthenticationConfiguration ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-dotnet-latest
  summary: >-
    Creates a configuration using the default key management - an RSA key will be created in memory and rotated every 8h.

    Uses <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.HttpMethod"></xref>, <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.HttpHost"></xref> etc. to control which elements of the request should be included in the POP token.
  remarks: See https://datatracker.ietf.org/doc/html/draft-ietf-oauth-signed-http-request-03#page-3 for details about signed HTTP requests.
  metadata: {}
- parameters:
  - namesWithMoniker:
    - value: httpRequestMessage
    type: <xref href="System.Net.Http.HttpRequestMessage?alt=System.Net.Http.HttpRequestMessage&text=HttpRequestMessage" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Net.Http.HttpRequestMessage)
  commentId: M:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Net.Http.HttpRequestMessage)
  name: PoPAuthenticationConfiguration(HttpRequestMessage)
  fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PoPAuthenticationConfiguration(HttpRequestMessage)
  nameWithType: PoPAuthenticationConfiguration.PoPAuthenticationConfiguration(HttpRequestMessage)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public PoPAuthenticationConfiguration (System.Net.Http.HttpRequestMessage httpRequestMessage);
  - lang: fsharp
    values:
    - value: 'new Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration : System.Net.Http.HttpRequestMessage -> Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration'
  - lang: vb
    values:
    - value: Public Sub New (httpRequestMessage As HttpRequestMessage)
  monikers:
  - msal-dotnet-latest
  summary: Creates a configuration using the default key management, and which binds all the details of the HttpRequestMessage.
  remarks: Currently only the HttpMethod (m), UrlHost (u) and UrlPath (p) are used to create the signed HTTP request - see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-signed-http-request-03#page-3
  metadata: {}
- parameters:
  - namesWithMoniker:
    - value: requestUri
    type: <xref href="System.Uri?alt=System.Uri&text=Uri" data-throw-if-not-resolved="True"/>
  type: constructor
  uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Uri)
  commentId: M:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor(System.Uri)
  name: PoPAuthenticationConfiguration(Uri)
  fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PoPAuthenticationConfiguration(Uri)
  nameWithType: PoPAuthenticationConfiguration.PoPAuthenticationConfiguration(Uri)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public PoPAuthenticationConfiguration (Uri requestUri);
  - lang: fsharp
    values:
    - value: 'new Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration : Uri -> Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration'
  - lang: vb
    values:
    - value: Public Sub New (requestUri As Uri)
  monikers:
  - msal-dotnet-latest
  summary: Creates a configuration using the default key management, and which binds only the Uri part of the HTTP request.
  remarks: The UrlHost (u) and UrlPath (p) are used to create the signed HTTP request - see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-signed-http-request-03#page-3
  metadata: {}
uid: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor*
commentId: Overload:Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor
namespace: Microsoft.Identity.Client.AppConfig
name: PoPAuthenticationConfiguration
fullName: Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.PoPAuthenticationConfiguration
nameWithType: PoPAuthenticationConfiguration.PoPAuthenticationConfiguration
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration..ctor
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.AppConfig.PoPAuthenticationConfiguration.#ctor
  - Microsoft::Identity::Client::AppConfig::PoPAuthenticationConfiguration::#ctor
  - '#ctor'
  - PoPAuthenticationConfiguration.#ctor
  - PoPAuthenticationConfiguration::#ctor
  helpviewer_keywords:
  - PoPAuthenticationConfiguration class [.NET], constructors
  - PoPAuthenticationConfiguration() class [.NET], constructors
  - PoPAuthenticationConfiguration(HttpRequestMessage) class [.NET], constructors
  - PoPAuthenticationConfiguration(Uri) class [.NET], constructors
  monikers:
  - msal-dotnet-latest
