### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  commentId: P:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  name: ClientCapabilities
  fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  nameWithType: MicrosoftIdentityApplicationOptions.ClientCapabilities
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<string>? ClientCapabilities { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.ClientCapabilities : seq<string> with get, set'
  - lang: vb
    values:
    - value: Public Property ClientCapabilities As IEnumerable(Of String)
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Specifies the capabilities of the client (for instance {"cp1", "cp2"}). This is

    useful to express that the Client is capable of handling claims challenge.
  metadata: {}
uid: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities*
commentId: Overload:Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
namespace: Microsoft.Identity.Abstractions
name: ClientCapabilities
fullName: Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
nameWithType: MicrosoftIdentityApplicationOptions.ClientCapabilities
assembliesWithMoniker:
- value: Microsoft.Identity.Abstractions.dll
packagesWithMoniker:
- value: Microsoft.Identity.Abstractions v1.1.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.get_ClientCapabilities
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.set_ClientCapabilities
  api_location:
  - Microsoft.Identity.Abstractions.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Abstractions.MicrosoftIdentityApplicationOptions.ClientCapabilities
  - Microsoft::Identity::Abstractions::MicrosoftIdentityApplicationOptions::ClientCapabilities
  - ClientCapabilities
  - MicrosoftIdentityApplicationOptions.ClientCapabilities
  - MicrosoftIdentityApplicationOptions::ClientCapabilities
  helpviewer_keywords:
  - MicrosoftIdentityApplicationOptions.ClientCapabilities property [.NET]
  - ClientCapabilities property [.NET], class MicrosoftIdentityApplicationOptions
  monikers:
  - msal-model-dotnet-latest
