### YamlMime:NetType
type: interface
implementsWithMoniker:
- value: <xref href="Microsoft.Identity.Client.IClientApplicationBase?alt=Microsoft.Identity.Client.IClientApplicationBase&text=IClientApplicationBase" data-throw-if-not-resolved="True"/>
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.ConfidentialClientApplication
extensionMethods:
- uid: Microsoft.Identity.Client.OsCapabilitiesExtensions.GetCertificate(Microsoft.Identity.Client.IConfidentialClientApplication)
  monikers:
  - msal-dotnet-latest
methods:
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenByAuthorizationCode(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenByAuthorizationCodeAsync(System.String,System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenForClient(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenForClientAsync(System.Collections.Generic.IEnumerable{System.String},System.Boolean)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenForClientAsync(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOf(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.UserAssertion)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenSilent(System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount,System.String,System.Boolean)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.AcquireTokenSilentAsync(System.Collections.Generic.IEnumerable{System.String},Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.GetAccountsAsync
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetAccountsAsync(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.GetAuthorizationRequestUrl(System.Collections.Generic.IEnumerable{System.String})
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.GetAuthorizationRequestUrlAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.GetAuthorizationRequestUrlAsync(System.Collections.Generic.IEnumerable{System.String},System.String,System.String)
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.GetUser(System.String)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Remove(Microsoft.Identity.Client.IUser)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RemoveAsync(Microsoft.Identity.Client.IAccount)
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.IClientApplicationBase.AppConfig
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Authority
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ClientId
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Component
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.RedirectUri
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.SliceParameters
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.Users
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.UserTokenCache
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.IClientApplicationBase.ValidateAuthority
  inheritedFrom: Microsoft.Identity.Client.IClientApplicationBase
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.IConfidentialClientApplication
commentId: T:Microsoft.Identity.Client.IConfidentialClientApplication
namespace: Microsoft.Identity.Client
name: IConfidentialClientApplication
fullName: Microsoft.Identity.Client.IConfidentialClientApplication
nameWithType: Microsoft.Identity.Client.IConfidentialClientApplication
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public interface IConfidentialClientApplication : Microsoft.Identity.Client.IClientApplicationBase'
- lang: fsharp
  values:
  - value: >-
      type IConfidentialClientApplication = interface
          interface IClientApplicationBase
- lang: vb
  values:
  - value: >-
      Public Interface IConfidentialClientApplication

      Implements IClientApplicationBase
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
summary: Component to be used with confidential client applications like web apps/API.
metadata:
  api_name:
  - Microsoft.Identity.Client.IConfidentialClientApplication
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplication
  - Microsoft::Identity::Client::IConfidentialClientApplication
  - IConfidentialClientApplication
  helpviewer_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplication interface [.NET]
  monikers:
  - msal-dotnet-latest
