### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder&text=MicrosoftIdentityBaseAuthenticationBuilder" data-throw-if-not-resolved="True"/>
  - <xref href="Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder?alt=Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder&text=MicrosoftIdentityWebApiAuthenticationBuilder" data-throw-if-not-resolved="True"/>
methods:
- uid: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.EnableTokenAcquisitionToCallDownstreamApi
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder.EnableTokenAcquisitionToCallDownstreamApi(System.Action{Microsoft.Identity.Client.ConfidentialClientApplicationOptions})
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
properties:
- uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.ConfigurationSection
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
- uid: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder.Services
  inheritedFrom: Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder
  monikers:
  - msal-model-dotnet-latest
uid: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
commentId: T:Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
namespace: Microsoft.Identity.Web
name: MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
fullName: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
nameWithType: Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
syntaxWithMoniker:
- lang: csharp
  values:
  - value: 'public class MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration : Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder'
- lang: fsharp
  values:
  - value: >-
      type MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration = class
          inherit MicrosoftIdentityWebApiAuthenticationBuilder
- lang: vb
  values:
  - value: >-
      Public Class MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration

      Inherits MicrosoftIdentityWebApiAuthenticationBuilder
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
summary: Builder for web API authentication with configuration.
metadata:
  api_name:
  - Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  - Microsoft::Identity::Web::MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  - MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration
  helpviewer_keywords:
  - Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration class [.NET]
  monikers:
  - msal-model-dotnet-latest
