### YamlMime:NetType
type: class
implementsWithMoniker:
- value: <xref href="Microsoft.Identity.Client.ITelemetryConfig?alt=Microsoft.Identity.Client.ITelemetryConfig&text=ITelemetryConfig" data-throw-if-not-resolved="True"/>
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.Identity.Client.TraceTelemetryConfig.#ctor
  monikers:
  - msal-dotnet-latest
properties:
- uid: Microsoft.Identity.Client.TraceTelemetryConfig.AllowedScopes
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.TraceTelemetryConfig.AudienceType
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.TraceTelemetryConfig.DispatchAction
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.TraceTelemetryConfig.SessionId
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.TraceTelemetryConfig
commentId: T:Microsoft.Identity.Client.TraceTelemetryConfig
namespace: Microsoft.Identity.Client
name: TraceTelemetryConfig
fullName: Microsoft.Identity.Client.TraceTelemetryConfig
nameWithType: Microsoft.Identity.Client.TraceTelemetryConfig
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
attributesWithMoniker:
- value: System.ObsoleteAttribute
syntaxWithMoniker:
- lang: csharp
  values:
  - value: >-
      [System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)]

      public class TraceTelemetryConfig : Microsoft.Identity.Client.ITelemetryConfig
- lang: fsharp
  values:
  - value: >-
      [<System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)>]

      type TraceTelemetryConfig = class
          interface ITelemetryConfig
- lang: vb
  values:
  - value: >-
      Public Class TraceTelemetryConfig

      Implements ITelemetryConfig
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
obsoleteMessagesWithMoniker:
- value: Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.
summary: A simple <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.ITelemetryConfig"></xref> implementation that writes data using System.Diagnostics.Trace.
remarks: This API is experimental and it may change in future versions of the library without an major version increment
metadata:
  api_name:
  - Microsoft.Identity.Client.TraceTelemetryConfig
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.TraceTelemetryConfig
  - Microsoft::Identity::Client::TraceTelemetryConfig
  - TraceTelemetryConfig
  helpviewer_keywords:
  - Microsoft.Identity.Client.TraceTelemetryConfig class [.NET]
  monikers:
  - msal-dotnet-latest
