### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  commentId: P:Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  name: RequiredAppPermissionsConfigurationKey
  fullName: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  nameWithType: IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string? RequiredAppPermissionsConfigurationKey { get; }
  - lang: fsharp
    values:
    - value: 'member this.RequiredAppPermissionsConfigurationKey : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property RequiredAppPermissionsConfigurationKey As String
  monikers:
  - msal-model-dotnet-latest
  summary: >-
    Fully qualified name of the configuration key containing the required

    app permissions (separated by spaces).
  metadata: {}
uid: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey*
commentId: Overload:Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
namespace: Microsoft.Identity.Web
name: RequiredAppPermissionsConfigurationKey
fullName: Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
nameWithType: IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
assembliesWithMoniker:
- value: Microsoft.Identity.Web.dll
packagesWithMoniker:
- value: Microsoft.Identity.Web v1.25.10
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-model-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.get_RequiredAppPermissionsConfigurationKey
  api_location:
  - Microsoft.Identity.Web.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Web.IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  - Microsoft::Identity::Web::IAuthRequiredScopeOrAppPermissionMetadata::RequiredAppPermissionsConfigurationKey
  - RequiredAppPermissionsConfigurationKey
  - IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey
  - IAuthRequiredScopeOrAppPermissionMetadata::RequiredAppPermissionsConfigurationKey
  helpviewer_keywords:
  - IAuthRequiredScopeOrAppPermissionMetadata.RequiredAppPermissionsConfigurationKey property [.NET]
  - RequiredAppPermissionsConfigurationKey property [.NET], interface IAuthRequiredScopeOrAppPermissionMetadata
  monikers:
  - msal-model-dotnet-latest
