### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor
  name: WsFederationConfiguration()
  fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.WsFederationConfiguration()
  nameWithType: WsFederationConfiguration.WsFederationConfiguration()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public WsFederationConfiguration ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  summary: Initializes an new instance of <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration"></xref>.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor
namespace: Microsoft.IdentityModel.Protocols.WsFederation
name: WsFederationConfiguration
fullName: Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.WsFederationConfiguration
nameWithType: WsFederationConfiguration.WsFederationConfiguration
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.WsFederation v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.WsFederation.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration.#ctor
  - Microsoft::IdentityModel::Protocols::WsFederation::WsFederationConfiguration::#ctor
  - '#ctor'
  - WsFederationConfiguration.#ctor
  - WsFederationConfiguration::#ctor
  helpviewer_keywords:
  - WsFederationConfiguration class [.NET], constructors
  - WsFederationConfiguration() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
