### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ITokenCache?alt=Microsoft.Identity.Client.ITokenCache&text=ITokenCache" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  commentId: P:Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  name: AppTokenCache
  fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  nameWithType: IConfidentialClientApplication.AppTokenCache
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.ITokenCache AppTokenCache { get; }
  - lang: fsharp
    values:
    - value: 'member this.AppTokenCache : Microsoft.Identity.Client.ITokenCache'
  - lang: vb
    values:
    - value: Public ReadOnly Property AppTokenCache As ITokenCache
  monikers:
  - msal-dotnet-latest
  summary: >-
    Application token cache. This case holds access tokens for the application. It's maintained

    and updated silently if needed when calling <xref data-throw-if-not-resolved="true" uid="Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenForClient(System.Collections.Generic.IEnumerable{System.String})"></xref>
  remarks: <p>On .NET Framework and .NET Core you can also customize the token cache serialization. See https://aka.ms/msal-net-token-cache-serialization. This is taken care of by MSAL.NET on other platforms.</p>
  metadata: {}
uid: Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache*
commentId: Overload:Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
namespace: Microsoft.Identity.Client
name: AppTokenCache
fullName: Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
nameWithType: IConfidentialClientApplication.AppTokenCache
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  - Microsoft.Identity.Client.IConfidentialClientApplication.get_AppTokenCache
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.IConfidentialClientApplication.AppTokenCache
  - Microsoft::Identity::Client::IConfidentialClientApplication::AppTokenCache
  - AppTokenCache
  - IConfidentialClientApplication.AppTokenCache
  - IConfidentialClientApplication::AppTokenCache
  helpviewer_keywords:
  - IConfidentialClientApplication.AppTokenCache property [.NET]
  - AppTokenCache property [.NET], interface IConfidentialClientApplication
  monikers:
  - msal-dotnet-latest
