### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor
  commentId: M:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor
  name: OpenIdConnectConfigurationRetriever()
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.OpenIdConnectConfigurationRetriever()
  nameWithType: OpenIdConnectConfigurationRetriever.OpenIdConnectConfigurationRetriever()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public OpenIdConnectConfigurationRetriever ();
  - lang: vb
    values:
    - value: Public Sub New ()
  monikers:
  - msal-web-dotnet-latest
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: OpenIdConnectConfigurationRetriever
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.OpenIdConnectConfigurationRetriever
nameWithType: OpenIdConnectConfigurationRetriever.OpenIdConnectConfigurationRetriever
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever..ctor
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.#ctor
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfigurationRetriever::#ctor
  - '#ctor'
  - OpenIdConnectConfigurationRetriever.#ctor
  - OpenIdConnectConfigurationRetriever::#ctor
  helpviewer_keywords:
  - OpenIdConnectConfigurationRetriever class [.NET], constructors
  - OpenIdConnectConfigurationRetriever() class [.NET], constructors
  monikers:
  - msal-web-dotnet-latest
