### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.TimeSpan?alt=System.TimeSpan&text=TimeSpan" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval
  commentId: F:Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval
  name: MinimumRefreshInterval
  fullName: Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.MinimumRefreshInterval
  nameWithType: ConfigurationManager<T>.MinimumRefreshInterval
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static readonly TimeSpan MinimumRefreshInterval;
  - lang: fsharp
    values:
    - value: ' staticval mutable MinimumRefreshInterval : TimeSpan'
  - lang: vb
    values:
    - value: 'Public Shared ReadOnly MinimumRefreshInterval As TimeSpan '
  monikers:
  - msal-web-dotnet-latest
  summary: 1 second is the minimum time interval that must pass for <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval"></xref> to  obtain new configuration.
  metadata: {}
namespace: Microsoft.IdentityModel.Protocols
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval
  api_location:
  - Microsoft.IdentityModel.Protocols.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.ConfigurationManager`1.MinimumRefreshInterval
  - Microsoft::IdentityModel::Protocols::ConfigurationManager`1::MinimumRefreshInterval
  - Microsoft.IdentityModel.Protocols.ConfigurationManager.MinimumRefreshInterval
  - MinimumRefreshInterval
  - ConfigurationManager`1.MinimumRefreshInterval
  - ConfigurationManager`1::MinimumRefreshInterval
  helpviewer_keywords:
  - ConfigurationManager<T>.MinimumRefreshInterval field [.NET]
  - MinimumRefreshInterval field [.NET], class ConfigurationManager<T>
  monikers:
  - msal-web-dotnet-latest
