### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.IdentityModel.Tokens.JsonWebKeySet?alt=Microsoft.IdentityModel.Tokens.JsonWebKeySet&text=JsonWebKeySet" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  name: JsonWebKeySet
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  nameWithType: OpenIdConnectConfiguration.JsonWebKeySet
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.IdentityModel.Tokens.JsonWebKeySet JsonWebKeySet { get; set; }
  - lang: fsharp
    values:
    - value: 'member this.JsonWebKeySet : Microsoft.IdentityModel.Tokens.JsonWebKeySet with get, set'
  - lang: vb
    values:
    - value: Public Property JsonWebKeySet As JsonWebKeySet
  monikers:
  - msal-web-dotnet-latest
  summary: Gets or sets the <xref data-throw-if-not-resolved="true" uid="Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet"></xref>
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: JsonWebKeySet
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
nameWithType: OpenIdConnectConfiguration.JsonWebKeySet
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_JsonWebKeySet
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.set_JsonWebKeySet
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.JsonWebKeySet
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::JsonWebKeySet
  - JsonWebKeySet
  - OpenIdConnectConfiguration.JsonWebKeySet
  - OpenIdConnectConfiguration::JsonWebKeySet
  helpviewer_keywords:
  - OpenIdConnectConfiguration.JsonWebKeySet property [.NET]
  - JsonWebKeySet property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
