### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.ICollection`1?alt=System.Collections.Generic.ICollection&text=ICollection" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  commentId: P:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  name: RequestObjectSigningAlgValuesSupported
  fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  nameWithType: OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  attributesWithMoniker:
  - value: Microsoft.IdentityModel.Json.JsonPropertyAttribute
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: >-
        [Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="request_object_signing_alg_values_supported", Required=Microsoft.IdentityModel.Json.Required.Default)]

        public System.Collections.Generic.ICollection<string> RequestObjectSigningAlgValuesSupported { get; }
  - lang: fsharp
    values:
    - value: >-
        [<Microsoft.IdentityModel.Json.JsonProperty(DefaultValueHandling=Microsoft.IdentityModel.Json.DefaultValueHandling.Ignore, NullValueHandling=Microsoft.IdentityModel.Json.NullValueHandling.Ignore, PropertyName="request_object_signing_alg_values_supported", Required=Microsoft.IdentityModel.Json.Required.Default)>]

        member this.RequestObjectSigningAlgValuesSupported : System.Collections.Generic.ICollection<string>
  - lang: vb
    values:
    - value: Public ReadOnly Property RequestObjectSigningAlgValuesSupported As ICollection(Of String)
  monikers:
  - msal-web-dotnet-latest
  summary: Gets the collection of 'request_object_signing_alg_values_supported'.
  metadata: {}
uid: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported*
commentId: Overload:Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
namespace: Microsoft.IdentityModel.Protocols.OpenIdConnect
name: RequestObjectSigningAlgValuesSupported
fullName: Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
nameWithType: OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
assembliesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
packagesWithMoniker:
- value: Microsoft.IdentityModel.Protocols.OpenIdConnect v6.25.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-web-dotnet-latest
metadata:
  api_name:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_RequestObjectSigningAlgValuesSupported
  api_location:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  - Microsoft::IdentityModel::Protocols::OpenIdConnect::OpenIdConnectConfiguration::RequestObjectSigningAlgValuesSupported
  - RequestObjectSigningAlgValuesSupported
  - OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported
  - OpenIdConnectConfiguration::RequestObjectSigningAlgValuesSupported
  helpviewer_keywords:
  - OpenIdConnectConfiguration.RequestObjectSigningAlgValuesSupported property [.NET]
  - RequestObjectSigningAlgValuesSupported property [.NET], class OpenIdConnectConfiguration
  monikers:
  - msal-web-dotnet-latest
