### YamlMime:NetType
type: interface
derivedClassesWithMoniker:
- value: Microsoft.Identity.Client.TraceTelemetryConfig
properties:
- uid: Microsoft.Identity.Client.ITelemetryConfig.AudienceType
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ITelemetryConfig.DispatchAction
  monikers:
  - msal-dotnet-latest
- uid: Microsoft.Identity.Client.ITelemetryConfig.SessionId
  monikers:
  - msal-dotnet-latest
uid: Microsoft.Identity.Client.ITelemetryConfig
commentId: T:Microsoft.Identity.Client.ITelemetryConfig
namespace: Microsoft.Identity.Client
name: ITelemetryConfig
fullName: Microsoft.Identity.Client.ITelemetryConfig
nameWithType: Microsoft.Identity.Client.ITelemetryConfig
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
attributesWithMoniker:
- value: System.ObsoleteAttribute
syntaxWithMoniker:
- lang: csharp
  values:
  - value: >-
      [System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)]

      public interface ITelemetryConfig
- lang: fsharp
  values:
  - value: >-
      [<System.Obsolete("Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.", false)>]

      type ITelemetryConfig = interface
- lang: vb
  values:
  - value: Public Interface ITelemetryConfig
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
obsoleteMessagesWithMoniker:
- value: Telemetry is sent automatically by MSAL.NET. See https://aka.ms/msal-net-telemetry.
remarks: This API is experimental and it may change in future versions of the library without an major version increment
metadata:
  api_name:
  - Microsoft.Identity.Client.ITelemetryConfig
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ITelemetryConfig
  - Microsoft::Identity::Client::ITelemetryConfig
  - ITelemetryConfig
  helpviewer_keywords:
  - Microsoft.Identity.Client.ITelemetryConfig interface [.NET]
  monikers:
  - msal-dotnet-latest
