### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.Identity.Client.ConfidentialClientApplicationBuilder?alt=Microsoft.Identity.Client.ConfidentialClientApplicationBuilder&text=ConfidentialClientApplicationBuilder" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: clientSecret
    description: >-
      Secret string previously shared with AAD at application registration to prove the identity
                  of the application (the client) requesting the tokens
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret(System.String)
  commentId: M:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret(System.String)
  name: WithClientSecret(String)
  fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret(String)
  nameWithType: ConfidentialClientApplicationBuilder.WithClientSecret(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.Identity.Client.ConfidentialClientApplicationBuilder WithClientSecret (string clientSecret);
  - lang: fsharp
    values:
    - value: 'member this.WithClientSecret : string -> Microsoft.Identity.Client.ConfidentialClientApplicationBuilder'
  - lang: vb
    values:
    - value: Public Function WithClientSecret (clientSecret As String) As ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
  summary: Sets the application secret
  metadata: {}
uid: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret*
commentId: Overload:Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret
namespace: Microsoft.Identity.Client
name: WithClientSecret
fullName: Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret
nameWithType: ConfidentialClientApplicationBuilder.WithClientSecret
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret
  - Microsoft::Identity::Client::ConfidentialClientApplicationBuilder::WithClientSecret
  - WithClientSecret
  - ConfidentialClientApplicationBuilder.WithClientSecret
  - ConfidentialClientApplicationBuilder::WithClientSecret
  helpviewer_keywords:
  - ConfidentialClientApplicationBuilder.WithClientSecret method [.NET]
  - WithClientSecret method [.NET], class ConfidentialClientApplicationBuilder
  - ConfidentialClientApplicationBuilder.WithClientSecret(String) method [.NET]
  - WithClientSecret(String) method [.NET], class ConfidentialClientApplicationBuilder
  monikers:
  - msal-dotnet-latest
