### YamlMime:NetMember
type: constructor
members:
- type: constructor
  uid: Microsoft.Identity.Client.ApplicationOptions.#ctor
  commentId: M:Microsoft.Identity.Client.ApplicationOptions.#ctor
  name: ApplicationOptions()
  fullName: Microsoft.Identity.Client.ApplicationOptions.ApplicationOptions()
  nameWithType: ApplicationOptions.ApplicationOptions()
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected ApplicationOptions ();
  - lang: vb
    values:
    - value: Protected Sub New ()
  monikers:
  - msal-dotnet-latest
  metadata: {}
uid: Microsoft.Identity.Client.ApplicationOptions.#ctor*
commentId: Overload:Microsoft.Identity.Client.ApplicationOptions.#ctor
namespace: Microsoft.Identity.Client
name: ApplicationOptions
fullName: Microsoft.Identity.Client.ApplicationOptions.ApplicationOptions
nameWithType: ApplicationOptions.ApplicationOptions
assembliesWithMoniker:
- value: Microsoft.Identity.Client.dll
packagesWithMoniker:
- value: Microsoft.Identity.Client v4.49.1
devLangs:
- csharp
- vb
monikers:
- msal-dotnet-latest
metadata:
  api_name:
  - Microsoft.Identity.Client.ApplicationOptions..ctor
  api_location:
  - Microsoft.Identity.Client.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.Identity.Client.ApplicationOptions.#ctor
  - Microsoft::Identity::Client::ApplicationOptions::#ctor
  - '#ctor'
  - ApplicationOptions.#ctor
  - ApplicationOptions::#ctor
  helpviewer_keywords:
  - ApplicationOptions class [.NET], constructors
  - ApplicationOptions() class [.NET], constructors
  monikers:
  - msal-dotnet-latest
